### ISSUE TITLE
Merging problem: Backend Plugin 1.1.3 has trash lines in it

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#105]
line 392 <<<<<<< HEAD
line 404 =======
line 413 >>>>>>> a8640399987a121b7963accdd333300f16f56961

Same problem several lines below.

Or is that just a local github problem?

**Comment by psilo909** [comment]
where do u see those in https://github.com/smarthomeNG/smarthome/blob/develop/plugins/backend/__init__.py

**Comment by onkelandy** [comment]
Hmmm, actually nowhere. As exactly the same thing happened after merging release-1.2 with the latest develop on two separate installations (only in the backend plugin and nowhere else) I thought that somehow somewhere there might be a problem. But actually just after merging.

Github is still a mystery for me - so if it only happens for me just delete the issue ;)

**Comment by i-am-offline** [comment]
That's a merge conflict that git can not solve automatically. Between <<<<<<< HEAD and ======= you can find the coding from your current version, between ======= and >>>>>>> a864039 is the coding change from commit a864039. You need to resolve the conflict manually (e.g. by choosing which of both versions you want to use, or combine both versions) and remove the markers. Then you can "git add" the conflict file and "git commit" to continue the merge.

**Comment by onkelandy** [comment]
Sometimes reading helps.. thanks alot ;)

**Comment by ohinckel** [comment]
So I think we can close this.
