### ISSUE TITLE
tools.ping not working?

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#111]
Hi!

Is it possible that with the newer develop releases (1.2.584) the sh.tools.ping() doesn't work anymore? I've been using the function quite alot and it always worked like this:
test=sh.tools.ping('www.google.at') # optional: 192.168.0.1 or 10.0.0.1
logger.info("Ping: {}".format(test))

When I now trigger this I always receive "False" no matter what URL or IP I use (also internal ones). A standard ping from the linux commandline works flawlessly.

**Comment by psilo909** [comment]
I am using it for this part in SV. As you can see, it is working. Item e.g.:
`[[nas]]
        type = bool
        cycle = 200 =1
		eval = sh.tools.ping('192.168.178.100')
        sqlite = yes
        database = yes`

![gdfg](https://cloud.githubusercontent.com/assets/15831643/17957837/52de933a-6a95-11e6-9bc8-53932d5f5f03.PNG)

**Comment by onkelandy** [comment]
Thanks alot for your feedback. Figured out it was a permission problem :(
Sorry
