### ISSUE TITLE
KNX Plugin: Support user defined data types with packet/compound knx data types?

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#113]
A user reports here 
[https://knx-user-forum.de/forum/supportforen/smarthome-py/980966-feature-vorschlag-custom-dpts-in-knx-plugin](https://knx-user-forum.de/forum/supportforen/smarthome-py/980966-feature-vorschlag-custom-dpts-in-knx-plugin) that he is running on TEBIS system which encodes its DPT in a strange way. It won't make sense to support all custom implementations but it might be well possible to have a kind of plugin for the knx plugin.
Another question is how to support packed knx data types within a single item. This might be easy for example for a four byte value that implements an RGB value but can be complicated for an item that uses two bytes to include a packet information structure. Any ideas?

**Comment by msinn** [comment]
I think the knx plugin should only support knx standard datatypes. Further encoding/decoding for manufacturer-specials should be done in logics or in eval statements.

Should we close this issue?

**Comment by bmxp** [comment]
As long as there is no further need of such a feature which is of general interest we should close it.
