### ISSUE TITLE
Configure additional module pathes (e.g. for 3rd party modules)

### ISSUE THREAD

**Issue by lgb-this** [smarthomeNG/smarthome#120]
I wrote some common modules for my system and stored them in /lib/3rd. Please add the line in smarthome.py again.

**Comment by ohinckel** [comment]
What about having an option in `smarthome.conf` to specify additional pathes which will be added as import directories? So it is configurabe and not hardcoded in the code.

**Comment by lgb-this** [comment]
Good idea with smarthome.conf - ok for me.

**Comment by ohinckel** [comment]
I create PR #193 for this feature request. If you want you can try it or provide feedback in the PR before we merge it.

**Comment by ohinckel** [comment]
The documentation for this was added to https://github.com/smarthomeNG/smarthome/wiki/Configuration
