### ISSUE TITLE
RTR Plugin does not work with more than one controller

### ISSUE THREAD

**Issue by paularndt** [smarthomeNG/smarthome#135]
It seems for me that there is something wrong with the initialization of the controller data structure. As you can see in the attached logfile extract, the values of the first controller are taken for the second controller instead of the empty template.
[logfile_extract.txt](https://github.com/smarthomeNG/smarthome/files/538271/logfile_extract.txt)

**Comment by bmxp** [comment]
I got an idea. Do you have a test case for me you frequently use?

**Comment by paularndt** [comment]
Attached you find striped down parts of my config files. Use different values (e.g. 22°C and 18°C
) for simulation of the set point temperature and/or room temperature and you will see, only the first controller works well.
[kinderzimmer1.conf.txt](https://github.com/smarthomeNG/smarthome/files/539976/kinderzimmer1.conf.txt)
[kinderzimmer2.conf.txt](https://github.com/smarthomeNG/smarthome/files/539975/kinderzimmer2.conf.txt)
[plugin.conf.txt](https://github.com/smarthomeNG/smarthome/files/539974/plugin.conf.txt)

**Comment by bmxp** [comment]
Thank you. I checked it: **replacing self._controller[c] = self._defaults** with **self._controller[c] = self._defaults.copy()** throughout the plugin should fix it.

**Comment by ohinckel** [comment]
Btw. the fix in develop branch is commit https://github.com/smarthomeNG/smarthome/commit/d4eecb4442649d0ad342f6b2b5a7ca2187d39ff7.
