### ISSUE TITLE
sv_page overview issue in plugin visu_smartvisu

### ISSUE THREAD

**Issue by sharktooth2** [smarthomeNG/smarthome#136]
I had issues with generating the overview pages. Please find attached my patch which solves the issue at least for me.
[sv_overview_patch.txt](https://github.com/smarthomeNG/smarthome/files/545686/sv_overview_patch.txt)

**Comment by bmxp** [comment]
Which version did you apply your patch to? And what branch? 1.2 develop?

**Comment by sharktooth2** [comment]
I have applied the patch against the SmartHomeNG Version 1.2 release (which was the same code as 1.2 develop at this time). The overview pages weren't generated. Looking at the code before I also don't see where this should happen?

**Comment by msinn** [comment]
Integrated patch into plugin in develop branch

**Comment by msinn** [comment]
Released to master with v1.3
