### ISSUE TITLE
Sunrise sunset 

### ISSUE THREAD

**Issue by Bonze255** [smarthomeNG/smarthome#15]
Integration der Sunrise/ sunset/ altitude /azimut Berechnung als Standart-Items. Da viele Leute das Sowieso vorhaben könnte man das Standartmaessig auch integrieren.

**Comment by Bonze255** [comment]
gerade gefunden steht in der env.location.cnf 

> [env]
    [[location]]
        [[[day]]]
            type = bool
        [[[night]]]
            type = bool
        [[[sunrise]]]
            type = foo
        [[[sunset]]]
            type = foo
        [[[moonrise]]]
            type = foo
        [[[moonset]]]
            type = foo
        [[[moonphase]]]
            type = num
        [[[moonlight]]]
            type = num

**Comment by Bonze255** [comment]
Hab hier mal die 2 Dateien abgeändert, das müsste so passen, allerdings sollte man dann im Wiki drauf verweisen
[location.conf.txt](https://github.com/smarthomeNG/smarthome/files/214864/location.conf.txt)
[location.py.txt](https://github.com/smarthomeNG/smarthome/files/214865/location.py.txt)

**Comment by psilo909** [comment]
Das Ding ist zwar Closed aber ich habe gerade gemerkt, dass die Werte in RADIANS (Bogenmaß) sind. Ich hätte lieber / zusätzlich gerne Degree. Wie sind hier die Meinungen?

**Comment by Bonze255** [comment]
Jepp, waere wohl besser

**Comment by psilo909** [comment]
wir bauen die items jetzt auf .degrees und .radians um, dann habt ihr beides

**Comment by psilo909** [comment]
Doku siehe https://github.com/smarthomeNG/smarthome/wiki/env

Bitte nachtesten!

**Comment by psilo909** [comment]
Ich schließe dann mal, bei Problemen bitte erneut öffnen.

**Comment by Bonze255** [comment]
Was steht eigentlich in der orb.py ? Haben wir jetzt nich die berechnungen doppelt ?

**Comment by schloessl** [comment]
Ich arbeite mit der Master, habe jetzt aus der Dev-Version aus der lib/env  die location.- Daten ubernommen. Leider bekomme ich einen Fehler:
2016-05-11 02:26:38 INFO     env_loc      Item env.location.sunrise = 2016-05-11 05:37:38.892197+02:00 via Logic None None
2016-05-11 02:26:38 ERROR    env_loc      Logic: env_loc, File: /usr/local/smarthome/lib/env/location.py, Line: 8, Method: <module>, Exception: pos() got an unexpected keyword argument 'dt'
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 346, in _task
    exec(obj.bytecode)
  File "/usr/local/smarthome/lib/env/location.py", line 8, in <module>
    azimut_rise, elevation_rise = sh.sun.pos(dt=sunrise)
TypeError: pos() got an unexpected keyword argument 'dt'

Wo finde ich sh.sun oder was habe ich vergesen zu übernehmen?

**Comment by Bonze255** [comment]
Hast du auch die location_conf uebernommen, da gab es auch anpassungen der items

**Comment by cstrassburg** [comment]
@schloessl : lib/orb.py musst du auch aus develop nehmen. da hat sich die Methode  pos() geändert, 
```
ERROR env_loc Logic: env_loc, File: /usr/local/smarthome/lib/env/location.py, Line: 8, Method: , Exception: pos() got an unexpected keyword argument 'dt'
```

**Comment by psilo909** [comment]
die frage zur orb.py verstehe ich nicht, die daten die in der location.py berechnet werden werden dort nicht berechnet.

**Comment by schloessl** [comment]
Dank an alle Helfer!
Die lib/orb.py hat die Lösung gebracht. Hier ist tatsächlich die pos()-Berechnung geändert.
An @bonze255: location.- Daten  hatte die location.conf eingschlossen. Sorrey, unklar von mir.
Trotzden Danke!
