### ISSUE TITLE
Network Plugin Timout Problem

### ISSUE THREAD

**Issue by patrickhener** [smarthomeNG/smarthome#163]
Hi there,

when using the Network Plugin with http get you would not receive an 200 ok. So the get will end in endless and wont timeout. If using it with php fsockopen for example the fsock will never close and code will not continue.

This has to be fixed somehow.

**Comment by patrickhener** [comment]
It got stuck every time I user a Browser to invoke the command or when using a php script. But to reproduce just use a browser an browse to http://ip.of.smarthome/item|path|state

Works for me every time. Browser is invoking command, light turns on/off and browser is running into timeout. Same with the script. The script invokes a get command and is waiting for response. Nothing is happening so the script gets hooked up in an endless loop.

**Comment by psilo909** [comment]
issue seems to be somewhere here: https://github.com/smarthomeNG/smarthome/blob/master/lib/connection.py#CL277

function not running into the close_after_end block

**Comment by psilo909** [comment]
for my point of view self.connected is always true.. there is no way to be set for false, as the function does not reach the close method.

**Comment by psilo909** [comment]
i get a huge load of these: https://github.com/smarthomeNG/smarthome/blob/master/lib/connection.py#CL294

**Comment by psilo909** [comment]
the indexerror occurs in https://github.com/smarthomeNG/smarthome/blob/master/lib/connection.py#CL282 when doing an self.outbuffer.pop()

from my understanding the connection should be close in the except block in line 294

**Comment by psilo909** [comment]
i propose this change - however changes to this central part could lead to severe problems

        except IndexError:  # buffer empty
            if self._close_after_send:
                logger.debug("close after send")
                self.close()
            return

**Comment by ohinckel** [comment]
Do you know why there is a `if not frame:` and a `if frame is None` check?

The `IndexError` is be a problem, right. The stream is not closed in this case. I would suggest to do a cleanup on any exception. But I would prefer to avoid an `IndexError` and check if the queue is not empty (e.g. using `len(self.outbuffer)`) instead of just trying to pop an element and do a "program flow execution based on exceptions". Controlling the program flow using exceptions is always a bad practice.

But maybe there was a reason by just poping elements and catching exceptions (e.g. thread-safety). Still I sugges to
* always clean up on any exception (not handling special cases)
* checking for emptiness of dequeu

For the quick-fix the suggestion from @psilo909 is enough.

**Comment by cstrassburg** [comment]
I  prefer to move the 
```
if self._close_after_send:
            logger.debug("close after send")
            self.close()
```
block from `try:` 
down to `finally:`

finally ist allways called after executing the try block and after an error.
An `if len(self.outbuffer) >0:` before pop() can't be wrong

**Comment by psilo909** [comment]
if i insert if len(self.outbuffer) > 0: nothing is working anymore :)

**Comment by psilo909** [comment]
i mean in this block:
```
        try:
            while self.connected:
                if len(self.outbuffer) > 0:
                    frame = self.outbuffer.pop()
                if not frame:
                    if frame is None:
                        self.close()
                        return
                    continue  # ignore empty frames
                sent = self.socket.send(frame)
                if sent < len(frame):
                    self.outbuffer.append(frame[sent:])
            if self._close_after_send:
                logger.debug("close after send")
                self.close()
        except IndexError:  # buffer empty
            return
        except socket.error:
            self.outbuffer.append(frame)
        except Exception as e:  # noqa
            logger.exception("{}: {}".format(self._name, e))
            self.close()
        finally:
            if self._close_after_send:
                logger.debug("close after send")
                self.close()
            self.__olock.release()

**Comment by psilo909** [comment]
https://github.com/smarthomeNG/smarthome/commit/c3154da05062ef597579a866f4e9b071e1bc8326

**Comment by onkelandy** [comment]
plugin wasn't working with the outbuffer-code (I guess).. Gladfully you've updated quite fast - right now everything seems to work fine.

Right now there is a separate logic necessary to sync 2 instances - it would be much more convenient if the plugin could exchange item values "out of the box" somehow ;)

**Comment by psilo909** [comment]
@onkelandy i suppose you pulled the bug with the to_bool method. for my opinion i dont want to adjust the network plugin to do anything out of the box. the connection.py file which is used is pretty ugly, so any larger "feature" improvement should be part a total rewriting of the network plugin.

did you read my post about integrating multi instance to the network plugin?

**Comment by psilo909** [comment]
@patrickhener please also retest.. the browser calls are now working fine here

**Comment by psilo909** [comment]
@patrickhener did u retest? my retest is ok (no timeout anymore). in case i dont get feedback from your side, i will close the issue end of next week

**Comment by ohinckel** [comment]
@psilo909, I think we can close this since our tests are positive and we still got no negative feedback from reporter @patrickhener.

**Comment by psilo909** [comment]
@ohinckel ok, closing now.. but at least one sentence of feedback by @patrickhener  could have been worth the efforts for this issue ;-)
anyway: using the fix for months stable now -> close
