### ISSUE TITLE
Backend plugin:  user-specific username value is ignored

### ISSUE THREAD

**Issue by pfischi** [smarthomeNG/smarthome#171]
When a user-specific username for authentication is set, this value will be ignored. No login to the webpage is possible (error 401). If it is changed back to 'admin' everything work fine.

**Comment by psilo909** [comment]
Cant confirm that. with "user = test" the login test is working here

**Comment by pfischi** [comment]
I've retried the login and now the username value is accepted. Strange. I've double-checked the config before i've posted the issue. I'll observe this behavior.

**Comment by psilo909** [comment]
@pfischi perhaps the browser was caching something?
