### ISSUE TITLE
Item: evaluation of initial value

### ISSUE THREAD

**Issue by 4d4mu** [smarthomeNG/smarthome#175]
Initial item `value` AFAIK is casted straight to item `type`. It would be nice to be able to calculate initial value, like with `eval` attribute. For example: I have motion sensor that switches hall light, but is blocked during the day. I would like to init blocking Item like this:
```
[my_blocking_item]
    type = bool
    value = sh.env.location.day()
    ...
```
or alternatively:
```
[my_blocking_item]
    type = bool
    crontab = init = sh.env.location.day()
    ...
```
Or maybe there is a way to do this that I don't know? (I mean without external logics)

**Comment by ohinckel** [comment]
Why not using `eval` and`eval_trigger`? Someting like this:
```
[block]
  eval = sh.env.location.day()
  eval_trigger = env.location.day
```

**Comment by 4d4mu** [comment]
But it will eval even if I change this Item manually, right? Considering this as a workaround

**Comment by cstrassburg** [comment]
this behavior  is already implemented through eval and eval_trigger like described by ohinckel

**Comment by 4d4mu** [comment]
But what happens when I change value from smartvisu?
