### ISSUE TITLE
automatisch geschlossene PRs 

### ISSUE THREAD

**Issue by cstrassburg** [smarthomeNG/smarthome#181]
Diese PR wurden automatisch durch die Trennung der Repos geschlossen.
Damit sie nicht untergehen:

https://github.com/smarthomeNG/smarthome/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20closed%3A2016-12-10

- [x] https://github.com/smarthomeNG/smarthome/pull/118 - change lists/dict via CLI will be implemented for v1.5

- [x] https://github.com/smarthomeNG/smarthome/pull/159 - mail plugin, gmail support will be implemented for v1.5
- [x] https://github.com/smarthomeNG/smarthome/pull/168 -> #186 - already [integrated](https://github.com/smarthomeNG/smarthome/commit/41d0110ba4b105f964746641b0f20fbf403bf618) in develop branch

- [x] https://github.com/smarthomeNG/smarthome/pull/169 -> in between last_update(), last_change(), prev_update() and prev_change() have been implemented

- [x] https://github.com/smarthomeNG/smarthome/pull/173 -> in the meantime there have been so many changes to alexa...

- [x] https://github.com/smarthomeNG/smarthome/pull/176 -> no real use case for env.season and calculation might be wrong for some countries.

**Comment by msinn** [comment]
#169 , #173 have been implemented.

Still three to go (check).

**Comment by msinn** [comment]
All 5 PRs that are going to bi implemented will bi in SmatHomeNG v1.4.1

**Comment by msinn** [comment]
SmartHomeNG v1.4.1 is released
