### ISSUE TITLE
Version determination not working in Develop anymore

### ISSUE THREAD

**Issue by psilo909** [smarthomeNG/smarthome#183]
Currently in Develop i get version "Version: 1.3.0.man" -> Version detection from git not working.

we should either fix that or remove the feature and just stay with 1.3.0.dev.

**Comment by cstrassburg** [comment]
gefixt, bitte noch mal testen

**Comment by psilo909** [comment]
war das früher nicht 3stellig?

Jetzt: 1.3.8523012.dev

**Comment by cstrassburg** [comment]
War 4 stellig. Beim trennen der Plugins ist der Bezug zu den Tags anscheinend abhanden gekommen. Es kann sein, dass es dann bei der nächsten Version wieder so wird wie vorher. Ein neues Tag hat auf anhieb auch keine Besserung gebracht. :-(

Wünsche auch schöne Weihnachten
