### ISSUE TITLE
start smarthomeng with parameter -l (reload logics) gives error

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#187]
doing the above we get an error.

```
2017-01-01 20:36:20 ERROR    smarthome    Main         Connection polling failed: [Errno 4] Unterbrechung während des Betriebssystemaufrufs -- smarthome.py:start:353
Traceback (most recent call last):
  File "./smarthome.py", line 351, in start
    self.connections.poll()
  File "/home/bernie/shdevelop/smartHome/lib/connection.py", line 101, in poll
    for fileno, event in self._epoll.poll(timeout=1):
InterruptedError: [Errno 4] Unterbrechung während des Betriebssystemaufrufs
```
I would suggest to mark the option -l to reload logics as deprecated and remove it with release version 1.4.
If there is the need to reload a logic then this can be achieved via backend due to the excellent work of @psilo909 and @msinn

**Comment by cstrassburg** [comment]
This is not a bug. `smarthome -l` send a SIGHUP to the running process and interrupts `self._epoll.poll(timeout=1)`

**Comment by bmxp** [comment]
If it's not a bug then why is there this exception? If it's a tolerable situation then the exception should be catched I think, unless there is an alternative implementation of connection.py in nearer future ...

**Comment by cstrassburg** [comment]
exception is already catched and only logged:
```
  while self.alive:
            try:
                self.connections.poll()
            except Exception as e:
                self.logger.exception("Connection polling failed: {}".format(e))
```
This is the main loop from SmartHomeNG (see bin/smarthome.py)
