### ISSUE TITLE
Missing import "psutil" / smarthomeNG crash

### ISSUE THREAD

**Issue by pfischi** [smarthomeNG/smarthome#194]
After a fresh git clone of the project (dev-branch) the psutil package is missing and SmarthomeNG crashes with an import error. In the file "requirements/all.txt" this requirement is missing.

Thx,

Stefan

**Comment by ohinckel** [comment]
I just [regenerated and updated](https://github.com/smarthomeNG/smarthome/commit/41ac385010ace9bd5d61eedfdfb57dbffd674453) the requirements file. The module is now included.
