### ISSUE TITLE
Enhancement: Change log level for eval returning None

### ISSUE THREAD

**Issue by Tom-Bom-badil** [smarthomeNG/smarthome#195]
I would appreciate if the log level for evals returning None could be set to 'debug' ([see here](https://github.com/smarthomeNG/smarthome/blob/master/lib/item.py#L344) --> currently at 'info' level).

In practise returning none isn't always an error, but sometimes on purpose. One example is an eval that is not returning a value for the item itself, but updating a foreign item. At the moment this would lead to spammed log files on frequently used items.

Example from smai: [here](https://knx-user-forum.de/forum/supportforen/smarthome-py/1015498-eval_update_item-update-auf-fremde-items?p=1016065#post1016065). The first eval in [boost] will always trigger a log entry, although it is valid code. I do know that at least onkelandy has the same issue, too (likely even more people).

Thank you for considering, and for all your work!

/tom

**Comment by cstrassburg** [comment]
fixed

**Comment by Tom-Bom-badil** [comment]
Thanks. :)
