### ISSUE TITLE
logic.conf in lib/env gets parsed into items tree

### ISSUE THREAD

**Issue by psilo909** [smarthomeNG/smarthome#200]
These lines affect, that logic.conf in lib/env is added to items tree, which is, according to my opinion, a bug, as logics are separate from items tree
https://github.com/smarthomeNG/smarthome/blob/develop/bin/smarthome.py#L322
https://github.com/smarthomeNG/smarthome/blob/develop/lib/config.py#L66

**Comment by msinn** [comment]
You are right. That logic.conf should not be added to the items tree. It is parsed, because it is located in a directory which contains item configurations. Maybe we should move the item definitions to a new directory /env/items instead mixing them with Python files and a logic configuration file.

**Comment by psilo909** [comment]
we could also think about detecting somehow, if we have an item or a logics in a .conf or .yaml file

**Comment by ohinckel** [comment]
We could
* add a top-level setting to the configuration file `type = logic|items` which can be used to detect the type of file
* use some postifxes like `my.items.conf`, `other.items.conf` or `my.logics.conf` or `other.logics.conf`
* separate different type by using different directories
* configure a pattern in the main configuration file for item and logic filenames
* detect file type by checking on configuration settings, for logic a `filename` attribute needs to be set on the 2nd level

I like the 1st idea.

**Comment by msinn** [comment]
In the past, item configs where seperated in the items folder but mknx broke his own rule in the lib/env folder.
We could do all that and probably it is the right way to be able to detect the contents of a config file.
But: We would implement it for yaml files only. My idea of moving the item definitions to a sub folder is the simplest fix AND it works for the old conf files too. (Up to now those files are still conf files).

**Comment by msinn** [comment]
@ohinckel I could add the global type to the converter. This way, all converted files are tagged, but I don't think honoring the filetype is something to be implemented for Release 1.3.

We have more types than items and logics: plugins, logging, smarthome-globals and a filetype with the extension .conf that doesn't fit in at the moment: The scenes.

So we have to do some more thinking and discussing to get to a good solution.

**Comment by bmxp** [comment]
I would prefer to have separate directories for items and logics so I second @msinn suggestion:
>Maybe we should move the item definitions to a new directory /env/items instead mixing them with Python files and a logic configuration file.

If we are going to support dynamically generated items one day then we will need to have a kind of system attribute anyway so that users can't delete system relevant items.

**Comment by msinn** [comment]
**logic.conf in lib/env gets parsed into items tree** is fixed in the actual develop branch. Will go into master with the next release.

**Comment by msinn** [comment]
Has been fixed in v1.4.
