### ISSUE TITLE
plugins/dlms wrong serialport error

### ISSUE THREAD

**Issue by lgb-this** [smarthomeNG/smarthome#203]
I started with the dlms plugin (develop) with a wrong serialport. The code crashed with the line:

`self._serial = serial.Serial(serialport, 300, bytesize=serial.SEVENBITS, parity=serial.PARITY_EVEN, timeout=2)`

**Comment by bmxp** [comment]
You should have got an error message as this error should be caught and reported. What else would you expect how it should behave?

**Comment by lgb-this** [comment]
The code crashs and does not show an error message.

**Comment by bmxp** [comment]
Did you test in standalone mode oder as plugin in SmartHomeNG?
If SmartHomeNG: What does it tell with SmartHomeNG in Debug Mode?

**Comment by lgb-this** [comment]
Here the error (plugin in SmartHomeNG Develop):
`2017-03-10  20:30:47 ERROR    Main         Plugin dlmsx exception: could not open port /dev/ttyUSB4: [Errno 2] No such file or directory: '/dev/ttyUSB4'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 275, in open
    self.fd = os.open(self.portstr, os.O_RDWR|os.O_NOCTTY|os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/smarthome/lib/plugin.py", line 90, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance)
  File "/usr/local/smarthome/lib/plugin.py", line 144, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthome/plugins/dlms/__init__.py", line 49, in __init__
    self._serial = serial.Serial(serialport, 300, bytesize=serial.SEVENBITS, parity=serial.PARITY_EVEN, timeout=2)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 261, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 278, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
serial.serialutil.SerialException: could not open port /dev/ttyUSB4: [Errno 2] No such file or directory: '/dev/ttyUSB4'
`

**Comment by bmxp** [comment]
Ok, some stacked exceptions. I'll change it to give some better error message. But anyhow it should not simply crash and say nothing...

**Comment by bmxp** [comment]
I've fixed this and some other minor annoyance. Have to make a PR somehow ...

**Comment by ohinckel** [comment]
@bmxp / @lgb-this, is here still something open?

**Comment by lgb-this** [comment]
Solved for me.

**Comment by bmxp** [comment]
I pushed the latest changes to develop. Please reopen if you find anything else.
