### ISSUE TITLE
yaml parse error with "*" as value

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#204]
Ich nutze für das Network Plugin den Eintrag port: * und erhalte beim Start folgenden Fehler:

```
2017-03-26  19:55:46 ERROR    Main         YAML-file load error in /usr/smarthome/etc/plugin.yaml:
while scanning an alias
  in "<unicode string>", line 69, column 14:
        udp_acl: *
                 ^
expected alphabetic or numeric character, but found '\n'
  in "<unicode string>", line 69, column 15:
        udp_acl: *
                  ^
```

**Comment by onkelandy** [comment]
Und gleich noch ein Problem zB beim Operationlog Plugin.. ich vermute, da müsste das Plugin umgeschrieben werden..?
```
2017-03-26  20:36:13 ERROR    Main         YAML-file load error in /usr/smarthome/etc/plugin.yaml:
while scanning a plain scalar
  in "<unicode string>", line 157, column 19:
        filepattern: {year:04}-{month:02}-{day:02}-{na ...
                      ^
found unexpected ':'
  in "<unicode string>", line 157, column 23:
        filepattern: {year:04}-{month:02}-{day:02}-{name}.log
                          ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
```

**Comment by msinn** [comment]
String sind in yaml in Anführungszeichen zu setzen. Darauf knn verzichtet werden, wenn die Strings keine Sonderzeichen enthalten, die yaml zu interpretieren versucht (wie * oder : ).

Also:

    udp_acl: '*'

oder:

    Filepattern: '{year:04}-{month:02}-{day:02}-{name}.log'

**Comment by onkelandy** [comment]
Ah, perfekt.. hatte mich gewundert, weil eben normale Strings auch einfach so funzten..
Danke für die Info, in dem Fall kein Issue ;)
