### ISSUE TITLE
New database plugin: final architecture

### ISSUE THREAD

**Issue by psilo909** [smarthomeNG/smarthome#208]
This issue is for discussing if the database plugin by @ohinckel and the database support in general can stay part of the SmartHomeNG core or should be moved to a single plugin. We could also think of solutions in between, as to provide a DatabasePlugin superclass allowing to inherit database support by plugins.

Please contribute your opinion to the following parts of the current implementation.

## 1. Core: General database support provided by lib.db.Database class
To support general database acces using a common interface the `Database` class can be used. This supports any database driver implementing the DB-API2 specification. It can be used anywhere in the shNG context (like plugins, core parts, user logics, etc) by importing the class from the `lib.db` module.

```
import sqlite3
import lib.db.Database
db = lib.db.Database('name', sqlite3, { 'database':'/path/to/sqlite.db' })
db.connect()
db.fetchall(...)
db.close()
```
For this no configuration in any config file is required for this. The `Database` class can be used as standalone class like other utility classes (e.g. `utils.py` or `tools.py`).

### Options:
1. Can stay as it is as core functionality or utility class (does not affect anything else of the core)
2. Can be moved to the database plugin (only location where this is used currently, *but* may become more important later in other stuff like logics or cire directly)
3. ...

### Votes:
* ohinckel: 1
* psilo909: 1
* foxi352: 1

### Status
Thanks for your feedback. Method will be kept.

- [x] Keep method.

## 2. Core: Map database drivers to names in `smarthome.conf`

For easier access to database drivers you can configure a mapping between a simple name (like 'sqlite' or 'mysql') and a driver module (like 'sqlite3' or 'pymysql'). This mapping can be used to configure other stuff (e.g. the database plugin) to specify which driver should be used.

In `smarthome.conf` setup the name and driver mapping (the `sqlite:sqlite3` mapping is always configured and does not need to be explicitly configured - only listed here for documenting purpose):
```
db = sqlite:sqlite3 | mysql:pymysql
```
In `plugin.conf` for the database plugin (which uses this currently - but could be changed):
```
[database]
    class_name = Database
    class_path = plugins.database
    db = sqlite   # <-- this is referencing the sqlite3 module with the name sqlite
    connect = database:/path/to/log.db | check_same_thread:0
    #prefix = log
```
The setting `db = <name>` is referencing the driver module configured in the main configuration file. To access the available configured driver mapping the method `sh.dbapi('<name>')` can be used which returns the driver implementation package. This can be passed to the `Database` class: `db = Database('name', sh.dbapi('mysql'), ...)`

### Options:
1. Can stay as it is since it eases the access to the driver modules (only the name is used anywhere and by just pointing the name to another driver module the application will use the other driver - no need to adjust other config files, just the main configuration)
2. Can be removed completely, mapping and `sh.dbapi()` method and instead of registering and using a mapped name use the driver modules directly (e.g. in sqlite and database plugin).
3. ...

### Votes:
* ohinckel: 2
* psilo909: 2
* foxi352: 2 (imho easier for end user, and compatibility testing is easier as fewer drivers in the field)

### Status:
Thanks for your feedback. The `dbapi` method will be removed completely.

- [x] Remove documentation of this parameter of `smarthome.conf` in [Wiki](https://github.com/smarthomeNG/smarthome/wiki/Configuration)
- [x] [Replace](https://github.com/smarthomeNG/plugins/commit/eef326beb552f357327328c52cb57753f15cb5ec) method call in `sqlite` and `sqlite_visu2_8` plugin with direct module import and usage
- [x] [Remove](https://github.com/smarthomeNG/smarthome/commit/a4caba8b38c3edbe5507a556a28fe67933638dc5) method `sh.dbapi()` and initialization completely

## 3. Database plugin: Configuration locally/globally
The database plugin is currently using both of the mentioned topics above (sqlite plugin only the second one). Since python is supporting sqlite3 per default users do not need to configure something when sticking on sqlite. Plugins can be configured by using the driver name `sqlite` - which is registered by SmartHome per default.

Using other drivers need adjustments in the main configuration file and the plugin configuration (e.g. you ned to set `db = mysql:pymysql` and the plugin config `db = mysql`).

### Options:
1. Can stay as it is but requires two configuration files to be adjusted in the worst case.
2. Can `db` setting to reference the driver module directly instead of the driver name from main configuration file (will also make the `db` setting and the `sh.dbapi()` method obsolete)
3. ...

### Votes:
* ohinckel: 2
* psilo909: 2
* foxi352: 2 (cf previous point)

### Status:
Thanks for your feedback. The configuration will be locally in the plugin configuration.

- [x] [Make](https://github.com/smarthomeNG/plugins/commit/eef326beb552f357327328c52cb57753f15cb5ec) `database` plugin configurable with driver name / module instead of using `dbapi` method

**Comment by psilo909** [comment]
@ohinckel @msinn @cstrassburg @bmxp ...

**Comment by onkelandy** [comment]
I would recommend to implement it completely in the core so it gets configured in smarthome.yaml only and the files move to the lib folder. If that's not possible or advisable regarding the multi instance feature a "plugin only" implementation would be okay, too. Don't know if that's possible right now. 

I'd also remove the sqlite plugins or clearly mark them as deprecated as it might be very confusing for beginners why there are different options to use sqlite.

**Comment by psilo909** [comment]
@onkelandy the sqlite plugin now uses the database layer in the core. so in my view it at first can be kept. however we have to think of users not using database at all. we need to find a way how they can continue using shNG without anything database related in config files.

**Comment by ohinckel** [comment]
>  we need to find a way how they can continue using shNG without anything database related in config files.

There is no need to configure anything if you still want to use the sqlite plugin. Only if you want to use other drivers you need to configure them - sqlite is supported by default.

**Comment by psilo909** [comment]
and if you dont want to use anything? i thought there was some dependency in every case? its long ago so i could be wrong in theory

**Comment by ohinckel** [comment]
To clarify this a little bit I updated the description. We are discussing different things here: common usable database layer/class, DB-API mapping configuration and database plugin configuration.

Please tell me if you don't understand these things to let me provide a better description. In case everything is clear, just comment here and add your opinion. Additionally give some votes in the description. If you have other solution options please feel free to add them to the description.

**Comment by bmxp** [comment]
Are there any instructions to `upgrade` somewhere? Otherwise it will be nearly impossible to get opinions of other power users ...

**Comment by psilo909** [comment]
i thought there was a migration script somewhere... -looking-

**Comment by ohinckel** [comment]
@psilo909, of course: one can still use the `sqlite` plugin.

Current status:
* SQLite plugins does not use `dbapi()` method anymore, instead they import the module directly.
* The database plugin replaced the `db` parameter (for the DB-API name) with the new `driver` parameter containing the name of driver module (e.g. `driver = sqlite3` or `driver = pymysql`)
* Remove the `dbapi()` method from core.

**Comment by ohinckel** [comment]
Since all is done here, I'll close this. Thanks to all providing feedback!
