### ISSUE TITLE
Readme.md should have the plugin name as title only

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#209]
I have been working on the doc/ directory and put some effort to the english documentation besides the German Wiki. I have found that the most plugins have not a single title headline but many entries with the same level.
Since the plugin directory can be scanned automatically by the Sphinx documentation for all Readme.md the TOC of the resulting html is flooded with unnecessary headlines.

**Comment by psilo909** [comment]
Title in diesem Sinne, oder?

"single = is styled as the article title and should not be used within an article." (https://en.wikipedia.org/wiki/Help:Wiki_markup)

Stelle meine Plugins nächste Woche (Urlaub) mal um.

**Comment by bmxp** [comment]
Old Way:
```
# My Plugin <- put the name of your plugin here

# Requirements

List the requirements of your plugin. Does it need special software or hardware?

## Supported Hardware

* list
* the
* supported
* hardware

# Configuration

## plugin.conf

Please provide a plugin.conf snippet for your plugin with ever option your plugin supports. Optional attributes should be commented out......

## items.conf

List and describe the possible item attributes.

### my_attr

Description of the attribute(s)...

### my_attr2

### Example

# items/my.conf

..... some more ....

```

IMHO Better way:
```
# My Plugin <- put the name of your plugin here

## Requirements

List the requirements of your plugin. Does it need special software or hardware?

## Supported Hardware

* list
* the
* supported
* hardware

## Configuration

### plugin.conf

Please provide a plugin.conf snippet for your plugin with ever option your plugin supports. Optional attributes should be commented out.....

#### items.conf

List and describe the possible item attributes.

#### my_attr

Description of the attribute(s)...

#### my_attr2

#### Example
```
Thus everything except the title has a lower heading level. This way we can use the markdown of all README.md from the plugins to simply include that into Sphinx docu.
I will create a new branch for doc and push that so you can see.

**Comment by bmxp** [comment]
This is how the html build of doc looks like currently:
![grafik](https://user-images.githubusercontent.com/3002409/27000543-3d5d4c50-4db5-11e7-8ff3-67b26693e319.png)

As an example what should be shown only I've circled in red the entries that _should_ be visible only in second level. All the other entries of the Alexa plugin should be lower level.

I have however no idea how many users really need the english documentation and if it's worth the efforts...

**Comment by psilo909** [comment]
AVM und ENIGMA2 angepasst.

**Comment by psilo909** [comment]
added it to (most) of the smartplugin plugins

**Comment by bmxp** [comment]
Since almost any Plugin Readme was already worked over I will close this issued here.
