### ISSUE TITLE
Core: Item functions using config for search not instance aware?

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#211]
In SmartHomeNG 1.2 there was introduced SmartPlugin as parent of all plugins. There are however some functions in the core that return items by search for attributes: 
``sh.find_items(configattribute)`` and ``find_children(self, parent, conf)``

e.g. ``avm_data_type@fritzbox_7490 = wan_connection_status`` 
a call to ``sh.find_items('avm_data_type')`` will likely match nothing.

Any ideas how we should deal with the instance attributes?

**Comment by ohinckel** [comment]
IMHO I would like to see something like an expression language which can be used to define a match query. This could also be the standard query language for other things: settings like `eval_trigger` or `watch_item` for configuration stuff or when used in code for the method mentioned in the description or the `return_items()`.

Parts of this query language could be
* query items by name
* query items by attribute (like in the example above)
* query items by attribute value - something like https://github.com/smarthomeNG/smarthome/pull/80
* query for structure parents/children (e.g query items by name and then query for children items by attribute) - something like https://github.com/smarthomeNG/smarthome/pull/94
* ... and other thing to be defined.

I don't like the idea of having different implementations for the same thing (some supports attributes, other relative references). But this could be discussed in a separate issue.

For this issue: when nothing is specified I think all items should be returned. I guess this was the old behaviour too. If one only want specific items for a given instance `avm_data_type@fritzbox_7490` should be used instead.

**Comment by msinn** [comment]
If it has some kind of urgency, I could think of a fix like this:

`sh.find_items('avm_data_type@')` would return all items called `avm__datatype` for all instances

and

`sh.find_items('@fritzbox_7490')` would return all items for instance `fritzbox_7490`

Otherwise I would say, It has to wait until we define an Item-API. But that is not going to happen in the near future. (Right now, the logics-API is mostly done and the next API to come would be for plugins)

**Comment by bmxp** [comment]
Nothing too urgent. Just wanted to point out that someday we might need some change here.

**Comment by msinn** [comment]
@bmxp Ich habe die Methoden ```find_items(conf)``` (wobei conf ein Attribut ist) und ```find_children(self, parent, conf)```(wobei parent die Position im Tree und conf ein Attribut ist) erweitert, so dass die Suche *instance aware* ist.

Dabei kann als Attribut (conf) folgendes angegeben werden:
<Attribut>  -  findet das Attribut nur, wenn es im Item ohne Instanz angegeben ist
<Attribut@> - findet das Attribut, wenn es im Item mit oder ohne Instanz angegeben ist
\<Attribut@Instanz> - Findet nur die Attribut/Instanz Kombination
<@Instanz> - Findet alls Attribute, die in Kombination mit Instanz im Item angegeben sind.

In Commit https://github.com/smarthomeNG/smarthome/commit/9b15777be0e240067b27a3f6152f0cd7a70238b3 hinzugefügt

**Comment by bmxp** [comment]
Documentation updated for next release and as far as I tested it, it works. So I'll close this issue.
