### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by bernd-wechner** [smarthomeNG/smarthome#214]
Yep, I'm stuck. What is SmartHomeNG? How might I use it? Clueless and not feeling less so from the README. Want too ask kindly for a summary of such burning questions.

As it stands, it looks like a ion club of sorts, in which those involved know what's going on and no-one else has a clue. 

So how did I come upon it? And why am I here to offer this experience up? Becasue I found this:

https://github.com/rthill/yamaha

While looking for any implementations of control panels for Yamaha AV receivers. I have one, and it has a cool phone app, but nothing on the PC. I know it's possible, there's a great sample with Mopidy, and I'm on the edge of building one from what I've seen there. But I loathe wasted energy and reinvented wheels so look around first and found that repo. 

And it leads here. And this, by name and notion, looks pretty cool, and maybe someone is controlling their Yamaha AV receiver using this (SmartHome NG). But seriously, could the README be any more hostile to a casual surf in than it is? And check this out:

https://www.facebook.com/smarthomeng
https://sourceforge.net/projects/smarthomeng-raspi-image/

Only deepening the mystery.

What say someone explain it to me, and I might take the time to write a better README intro for you from what I learn? An offer.

**Comment by psilo909** [comment]
=> https://github.com/smarthomeNG/smarthome/wiki ? 

The Facebook page is not related to us.

**Comment by bernd-wechner** [comment]
Awesome! Thank you immensely!

I read German well enough so can benefit from that in time, and doH! I should perhaps have thought to check the wiki but truth be told am familiar with GiutHub projects introduced on the README. The one I refer to is the README.md on this project visible at:

https://github.com/smarthomeNG/smarthome

Which super technical and disorienting for a README entry doc.

So now I have to do is read up on smarthomeNG in the wiki and assess whether it and I are mutually helpful and if so, indeed I'd probably stat with PR on the README.md. 

Thanks enormously for the rapid and helpful pointers to a blind newb. ...

**Comment by psilo909** [comment]
@bernd-wechner good hint.. i will set a LINK to the WIKI at least in the DEV branch, which should be transferred to master in the near future.

In case you have questions check the gitter chat or the knx-user-forum.

**Comment by psilo909** [comment]
bye the way: in the DEVELOP the wiki is already linked:
https://github.com/smarthomeNG/smarthome/tree/develop

anyway thx to my focus there i will push an updated version of the README

**Comment by bernd-wechner** [comment]
OK, cursory read reveals much to me. In the short term it means that smarthomeNG gets bookmarked under  my smarthome folders where I'm keeping the links to the stuff I need for projects I'm slowly working on and hope to build in coming years (alas it is that slow with dozens of projects, three kids, a day job, and various other responsibilities, but hey) which includes a solar hot water monitoring and perhaps control system, a power metering systems, a parcel delivery notification system and more ;-). I worry that I have visions beyond my ability to construct, but hey, I have a mass of hard and software in a mini mini workshop just lack the time to focus on it much. Was working on this with a 2 month only bouncing on my lap much of the time with on hand on him and the other working the PC  reading and tapping out comments with one hand ;-).

Thanks enormously for the prompt courteous and informative responses!

**Comment by psilo909** [comment]
just to compare: 2 kids, 2-3 hours of traveling to/from work each day, long working hours.. but well, it's a passion...

i think you can realize most with the framework. just working on a mail detection on basis of an ESP32 which sends data via the network plugin to the central server. similar approach running with a raspi (as bluetooth hub) for collecting xiaomi flower sensor data..

well but that does not contribute to the issue. i think i can close now, right?

**Comment by bernd-wechner** [comment]
Yep! 

That's a lot of travel. I hope it's by train or such and you can read or work, driving's a pain. I commute on a bicycle and under an hour all up each day and am pleased I can.
