### ISSUE TITLE
Database plugin: Provide migration support

### ISSUE THREAD

**Issue by ohinckel** [smarthomeNG/smarthome#215]
To migrate from sqlite plugin to the database plugin we need to have
* a migration script which converts the items conf/yaml files
* a documentation how to migrate

(leftover from #165)

**Comment by psilo909** [comment]
will we really need a migration script for the CONF / YAML Files? wont an "extended replace" function of a good editor like notepad++ fit to the requirement?

**Comment by psilo909** [comment]
what we should do is a wiki page for the lesser technical people in here, e.g. how to install maria db, how to set a dedicated smarthome user, etc. i can start with that the next days.

**Comment by ohinckel** [comment]
Sure, one can just do a search replace magic. But I remember somebody asking for a migration script (like the `conf` to `yaml` converter). I'm think a migration is an easy step in the configuration file, too.

But what about the existing data in the databases. Do we need a script for dumping the old SQLite database and importing it into a new RDBMS database?

**Comment by psilo909** [comment]
@ohinckel didnt the "someone" mean a migration from sqlite .db file to e.g. maria db database?

**Comment by bmxp** [comment]
We actually alread have a "migration script" from conf to yaml since @msinn put it into tools/conf_to_yaml_converter.py. One just has to know about and use it. So we really just need a migration manual like the Komplettanleitung.

**Comment by psilo909** [comment]
@bmxp u get it wrong, @ohinckel means that we need a script like that to convert e.g. sqlite = yes to database = xyz

**Comment by ohinckel** [comment]
Added a simple script which converts conf/yaml files using sqlite settings to database settings. Because only the `sqlite` setting needs to be converted (also the possible values `yes` and `init` are supported by the database backend) it can be done be using a simple regex magic.
