### ISSUE TITLE
plugin influxdb

### ISSUE THREAD

**Issue by kr2** [smarthomeNG/smarthome#217]
If there are spaces or commas in the tags (also source, dest, ...) if fails "silently" since UDP is used by design, but the errors show in the influx log. I think the reason is the influxdb syntax, which uses comma and spaces for formatting. A quick hack that works for me is:
```python
tags = {
    'caller': str(caller).replace(',', '').replace(' ', ''),
    'source': str(source).replace(',', '').replace(' ', ''),
    'dest': str(dest).replace(',', '').replace(' ', '')
}
```
I guess someone with more understanding of it should fix it, because the other tags should be checked too or maybe there is some escape sequenz.

**Comment by onkelandy** [comment]
There is something going on for the influxdb plugin right now:
https://knx-user-forum.de/forum/supportforen/smarthome-py/1229450-umfrage-zur-nutzung-der-time-series-datenbank-influxdb?p=1255587#post1255587

And I've pushed an update for the simple influxdata plugin:
https://github.com/smarthomeNG/plugins/pull/151

**Comment by bmxp** [comment]
@kr2 it seems as if commit  b67dd52 has fixed this problem. Feel free to reopen this issue if the problem still somewhat exists.
