### ISSUE TITLE
visu_websocket new series identifier 'val'

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#218]
I wished that visu_websocket plugin could provide also real values for a series (instead of only ``sum``, ``avg``, ``min`` or ``max``). 

Just ``val`` to provide a real measurement. Together with the new database plugin we could then e.g. display correct measurements.

**Comment by msinn** [comment]
The visu_websocket plugin can't do it by itself. It has to be coordinated with the database plugins (sqlite, sqlite_2_8, database).

**Comment by ohinckel** [comment]
This request could be integrated into the #235 (adding `sum` and `count`).

AFAIS, this is not an enhancement for the `visu_websocket` plugin, since it only passes the aggregation method to the backend plugin (database, sqlite, ...).

**Comment by msinn** [comment]
Übertragen in Issue https://github.com/smarthomeNG/smarthome/issues/235
