### ISSUE TITLE
 smarthome/etc/smarthome.yaml.default : syntax error

### ISSUE THREAD

**Issue by lgb-this** [smarthomeNG/smarthome#219]
The following example in the file smarthome/etc/smarthome.yaml.default (develop) is not correct for a yaml-file:

# module_paths = /usr/local/python/lib    # list of path-entries is possible

It should be:

# module_paths: /usr/local/python/lib    # list of path-entries is possible

I assume, that the following line is also wrong:

# assign_compatibility = latest            # latest or compat_1.2 (compat_1.2 is default for shNG v1.3)

**Comment by psilo909** [comment]
that is right.. the conversion was not made with the tool in the backend plugin because the line is commented.. i will correct that.

**Comment by psilo909** [comment]
fixed: https://github.com/smarthomeNG/smarthome/commit/c07a42d547d469241ed5ba758d7ba1229f9cb8ed
