### ISSUE TITLE
Documentation enhancements / fixes for 1.4

### ISSUE THREAD

**Issue by ohinckel** [smarthomeNG/smarthome#221]
This is an aggregation issue to finalize and fix the current documentation. Just write some comments with points you want to fix/discuss to the description field.

@psilo909 suggestions:
* [x] http://smarthomeng.msinn.de/config.html contains strange symbol "¶" (e.g. behind of `logic.yaml` and others)
* [x] we should check if all enhancements are listed in the documentation (for example the relative item addressing in configurations)
* [x] a lot is still showing the configuration in `conf` format instead of `yaml` (e.g. http://smarthomeng.msinn.de/items.html)
* [x] the "Web / Cloud Plugins" section is listing some nginx files and a "Install (debian)" in the navigation tree

@ohinckel suggestions:
* [ ] the code blocks are using a too large font, should be a little bit smaller
* [x] a lot of typos (how can I fix this by myself?)
* [ ] the code blocks - mostly used for deprecated stuff - shows the filename in the header which is nicer than the code blocks showing just the filename above the box (like the example plugin or logic configuration)
* [x] instead of listing the directory structure in a simple code block we could list them and describe them in short in sections, additionally I would always write "Logics directory" or "Plugin directory" instead of `logics/` or `plugins/` and link them to the describing section (look the the plugin or logic page)
* [x] the different sections listing the plugins could also show the a short description of the plugin instead of only the name (instead of just showing "CLI" it could show "CLI - A simple telnet command line interface")
* [x] the "Index" link in the navigation shows empty page

**Comment by msinn** [comment]
@ohinckel To fix typos, go to the develop branch of smarthomeNG and look for the file where the typo is in:

- In doc/source: find the file that corresponds to the navigation entry (e.g. release.rst) In that file you'll find the text or a reference to the file containing the test. This can be another rst file or maybe README.md from the plugins.

Fix the error in the appropriate file and commit the changes. 

To be seen in the documentation, the html documentation has to be built again.

**Comment by msinn** [comment]
For correcting documentation about plugins (e.g. CLI), modify the README.md of that plugin.

**Comment by msinn** [comment]
@psilo909 The NGINX stuff comes from a file (NGINX.md) within the alexa plugin. Which does not follow the formatting conventions. I removed it from the list in **plugins_web.rst**.

**Comment by msinn** [comment]
@ohinckel can you reproduce the empty index page?

**Comment by Foxi352** [comment]
http://smarthomeng.msinn.de/plugins/knx/README.html

items.conf / knx_dpt section: DPT table not formatted correctly

**Comment by ohinckel** [comment]
@msinn, no can not reproduce using other browser (Chrome instead of Firefox).

**Comment by msinn** [comment]
@Foxi352 Sphinx (the code generator) doesn't seem to convert markdown tables correctly. The markdown formatted table is yust dumped into the html code.

For the moment I have no idea what to do about it.

**Comment by msinn** [comment]
The developer documentation is now available under **www.smarthomeNG.de**

**Comment by msinn** [comment]
Documentation reads the plugin metadata on build an generates Information tables for plugins. So:

> the different sections listing the plugins could also show the a short description of the plugin instead of only the name

is done.

**Comment by msinn** [comment]
Since v1.4 is released an only two minor points are still open: Should wo close this issue?

- Font size is quite om (in my opinion)
- Most code blocks have a header and a comment with the filename in it by now

**Comment by ohinckel** [comment]
I think the documentation is really great now. The remaining minor options are not a show blocker, so I'll close this.
