### ISSUE TITLE
Plugin development made hard on invalid syntax

### ISSUE THREAD

**Issue by ThomasCr** [smarthomeNG/smarthome#224]
Hi, today I updated my develop branch and also started to made some changes on plugins.
But now, it is hard to find plugin code typos, because code-errors will not display in logfile like before.

Any way, to get this error messages back?

### To clarify what I talk about
Before:
```
2017-08-13  12:04:08 ERROR    Main         Plugin po exception: invalid syntax (__init__.py, line 100)
Traceback (most recent call last):
  File "/usr/local/smarthomeng-dev/lib/plugin.py", line 90, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance)
  File "/usr/local/smarthomeng-dev/lib/plugin.py", line 127, in __init__
    exec("import {0}".format(classpath))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthomeng-dev/plugins/pushover/__init__.py", line 100
    elif (resp.status == 429)
                            ^
SyntaxError: invalid syntax
```
Now only:
```
2017-08-13  14:15:14 ERROR    Main         Module 'po' configuration error: Plugin 'plugins.pushover' not found or class 'Pushover' not found in module file
```

**Comment by ThomasCr** [comment]
Möglicherweise nach diesem Commit?
https://github.com/smarthomeNG/smarthome/commit/e391e28331331b8170931809e10a96e4ea067b8e#diff-a1cf5c8e4e0bd5020f6115b82a4b8e80

**Comment by ThomasCr** [comment]
I found a other way to do syntax check (as a workaround):

```
root@zentrale:/usr/local/smarthome-dev/plugins/pushover# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import __init__.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__init__.py", line 63
    if priority.isdigit() and priority => -2 and priority <= 2:
                                       ^
SyntaxError: invalid syntax
>>>

```

**Comment by msinn** [comment]
Hi,

I changed the exception handling for the plugin loading process. Take a look if it is now sufficient for you.

**Comment by msinn** [comment]
@ThomasCr Did you have a chance to take a look at the changed exception handling (in develop branch)?

**Comment by msinn** [comment]
@ThomasCr Did you have a chance to take a look at the changed exception handling (in develop branch)?

**Comment by ThomasCr** [comment]
Hi, today I had time to take a look at it.

```
2017-12-03  21:04:50 ERROR    Main         Plugin 'zwave' exception during import of __init__.py: invalid syntax (__init__.py, line 169)
Traceback (most recent call last):
  File "/usr/local/smarthomeng-dev/lib/plugin.py", line 364, in __init__
    exec("import {0}".format(classpath))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthomeng-dev/plugins/zwave/__init__.py", line 169
    def OnNotification(self, )
                             ^
```
It works. Thanks - seems to be fixed.

**Comment by ThomasCr** [comment]
we cant add also a handling for exceptions which are not caught, like we have discussed last time?

**Comment by ThomasCr** [comment]
Oh, also one thing, which you dont find easly:

> 2017-12-03  21:21:05 ERROR    Main         Plugin 'zwave' from section 'zwave' exception: 'str' object has no attribute 'getLogger'
> Traceback (most recent call last):
>   File "/usr/local/smarthomeng-dev/lib/plugin.py", line 111, in __init__
>     plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance, self.meta)
>   File "/usr/local/smarthomeng-dev/lib/plugin.py", line 413, in __init__
>     exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
>   File "<string>", line 1, in <module>
>   File "/usr/local/smarthomeng-dev/plugins/zwave/__init__.py", line 71, in __init__
>     self.logger = logging.getLogger(__name__)   # get a unique logger for the plugin and provide it internally
> AttributeError: 'str' object has no attribute 'getLogger'
> 

and the same file on python shell:
```
>>> import plugins.zwave.__init__.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plugins/zwave/__init__.py", line 37, in <module>
    from openzwave.network import ZWaveNetwork
ImportError: No module named openzwave.network
```

**Comment by bmxp** [comment]
IMHO you should at first install an editor which checks syntax prior to any code running. E.g. PyCharm Community edition will do it...

**Comment by msinn** [comment]
@ThomasCr 

> we cant add also a handling for exceptions which are not caught, like we have discussed last time?

```
2017-12-03  21:04:50 ERROR    Main         Plugin 'zwave' exception during import of __init__.py: invalid syntax (__init__.py, line 169)
Traceback (most recent call last):
  File "/usr/local/smarthomeng-dev/lib/plugin.py", line 364, in __init__
    exec("import {0}".format(classpath))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthomeng-dev/plugins/zwave/__init__.py", line 169
    def OnNotification(self, )
                             ^
```
 This ist the handling for exceptions that have not been caught. It is implemented in bin/smarthome.py

What is wrong about that?

**Comment by msinn** [comment]
Should we close this issue or is there. Eed for further discussion?

**Comment by msinn** [comment]
Since no one commented it for half a year, I close the issue

**Comment by ThomasCr** [comment]
Hi, today I came again to the problem:

this simple error was not shown on output and execution just stops without any error/warning on logfile. 

```
name, c = path.split('_')
```
where path is not set. correct is should be filename.splitt.... but it was hard to find where I made the typo.

if I execute it on the shell:

```
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> name, c = path.split('_')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'path' is not defined
>>> 
```

**Comment by ThomasCr** [comment]
also the following call was not giveing any output:

`self._createTrigger(filename, c, datetime.fromtimestamp(ts))`

on shell:
```
Python 3.6.6 (default, Sep 12 2018, 18:26:19)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> ts=1541102879
>>> print("datetime is {}".format(datetime.fromtimestamp(ts)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'datetime' has no attribute 'fromtimestamp'
>>> 

```

**Comment by ohinckel** [comment]
Where are all these calls you mentioned which are not logging errors? Want to know to test myself.

**Comment by ThomasCr** [comment]
yes, no one has created a error message

**Comment by msinn** [comment]
I can't find any of the code you mention in the rtr plugin

**Comment by msinn** [comment]
Btw. why are you commenting on an old issue without reopening it?

**Comment by ThomasCr** [comment]
I cant reopen, when some else has closed the issue (not me).

> `name, c = path.split('_')`

change on my commit, line 357 the filename back to path

> `self._createTrigger(filename, c, datetime.fromtimestamp(ts))`

change on my commit, line 360

**Comment by msinn** [comment]
Nachdem ich den Code

```
name, c = path.split('_')
```

zum test in einem Plugin in verschiedene Methoden (__init__, parse_item, ...) eingefügt hatte und brav Exceptions im log hatte, wollte ich das Thema schon zu den Akten legen.

Nun geht aus Deinem commit hervor, dass das eine in einer Methode auftritt, die Du aus der run Methode aufrufst. Da verlassen wir ein Stück weit den Bereich der Plugins, weil da das Python Thread Management ins Spiel kommt. Für die Run Methode muss ich vermutlich ganz wo anders suchen, um festzustellen wer die Exception schluckt.

Für Dich die schnellste Lösung für Methoden, die Du aus der run() Methode aufrufst, ist diese in ein try/except einzubetten, bevor die Exception die run() Methode "nach oben" verlässt.

z.B. so:

```
    def run(self):
        """
        Run method for the plugin
        """
        self.logger.debug("run method called")
        self.alive = True
        self.scheduler_add('cycle', self.update_items, prio=5, cycle=int(self._cycle_time))
        # if you want to create child threads, do not make them daemon = True!
        # They will not shutdown properly. (It's a python bug)
        try:
            self._restoreTrigger()
        except Exception as e:
            self.logger.error("Error in 'self._restoreTrigger()': {}".format(e))
```

**Comment by ThomasCr** [comment]
ok, werde versuchen in Zukunft daran zu denken. Konntest du es denn über die run Methode nachvollziehen?

**Comment by msinn** [comment]
Ja, nur ich habe keine Idee wo in der Hierarchie die Exception verschwindet, so dass sie nicht an die Oberfläche kommt. Ich muss sehen ob ich für run() und stop() (das sind die einzigen betroffenen Methoden. Die anderen Methoden werfen brav Exceptions) in der Hierarchie oberhalb der eigentlichen Methoden eine Stelle finde wo ich generalistisch ein solches try/except einbauen kann, damit man das nicht in den Methoden der Plugins selber machen muss.

**Comment by ThomasCr** [comment]
ok, verstehe

**Comment by msinn** [comment]
Was meinst Du mit "Scheduler code"?

**Comment by ThomasCr** [comment]
ja, das meinte ich. Danke nochmal für die Ausführung.

**Comment by msinn** [comment]
@ThomasCr Ich habe die Suche aufgegeben, wo die Exception verschluckt wurde. 
Ich habe in der Zwischenzeit eine Stelle gefunden, wo ich auch für die run() und die stop() Methode die Exception fangen und Loggen kann.
Im develop sollten nun auch ohne Maßnahmen von Dir Fehler im Log auftauchen.

**Comment by msinn** [comment]
Kommt da noch was oder können wir das Issue schließen?

**Comment by msinn** [comment]
Das kein Feedback mehr kommt: Geschlossen
