### ISSUE TITLE
Connection polling failed: [Errno 9] Ungültiger Dateideskriptor 

### ISSUE THREAD

**Issue by wil76** [smarthomeNG/smarthome#227]
any idea where this is coming from ?

```
2017-08-20  23:27:51 ERROR    Main         Connection polling failed: [Errno 9] Ungültiger Dateideskriptor
Traceback (most recent call last):
  File "smarthome.py", line 416, in start
    self.connections.poll()
  File "/usr/local/smarthome/lib/connection.py", line 100, in poll
    self._epoll.modify(fileno, self._ro)
OSError: [Errno 9] Ungültiger Dateideskriptor
2017-08-20  23:27:51 ERROR    Main         Connection polling failed: [Errno 9] Ungültiger Dateideskriptor
Traceback (most recent call last):
  File "smarthome.py", line 416, in start
    self.connections.poll()
  File "/usr/local/smarthome/lib/connection.py", line 100, in poll
    self._epoll.modify(fileno, self._ro)
OSError: [Errno 9] Ungültiger Dateideskriptor
2017-08-20  23:27:51 ERROR    Main         Connection polling failed: [Errno 9] Ungültiger Dateideskriptor
Traceback (most recent call last):
  File "smarthome.py", line 416, in start
    self.connections.poll()
  File "/usr/local/smarthome/lib/connection.py", line 100, in poll
    self._epoll.modify(fileno, self._ro)
OSError: [Errno 9] Ungültiger Dateideskriptor
```
obviously this has been looping for a longer time, but disappeared after some time with tons of log entries.
-----   Init SmartHomeNG 1.3x.ee85750.dev   -----

**Comment by ohinckel** [comment]
This is the one and only error message? I guess there is some more error in front of these errors indicating what's wrong with the file descriptor (maybe a connection was closed but not noticed and is still polled).

Could also be interesting which part is using connections. Which plugins are you using? Are you using other code using the connection management from `connection.py`?

**Comment by wil76** [comment]
there is no more in front of these messages.
and I do not use connection.py.
I found it already in 2 installations after migration to smarthomeNG

**Comment by msinn** [comment]
You are using the non stable branch (develop). If you have multiple installations (I guess production installations), you should use the stable master branch.

I can't realy tell where it is comming from. In the actual commit in the develop branche, the line 416 which is listed in your traceback contains other code, not the command `self.connections.poll()`.

**Comment by psilo909** [comment]
I removed some code lines after another issue was reported. did that in agreement with @cstrassburg - i cannot say if that is related to this observation.. commit was this one: https://github.com/smarthomeNG/smarthome/commit/965c45d72cb25f8edbb04184e0d25696f9ed0d46 and it is pretty long ago

**Comment by ohinckel** [comment]
He's using an old version of develop branch.

> he actual commit in the develop branche, the line 416 which is listed in your traceback
> contains other code, not the command self.connections.poll().

You can find this when looking into the [old version](https://github.com/smarthomeNG/smarthome/blob/ee857505c077fde1c37dbe72b691abd84ec5fb6c/bin/smarthome.py) of this file.

@wil76 can you tell us which plugins you're using? Could be that some plugin has a bug with the connection handling.

@psilo909 seems it is not related since it was just a removal of duplicate code. But the code looks compliated and could have still some bugs. Tests would help here to verify the correct behaviour ;-)

**Comment by wil76** [comment]
it's no more happening sine several days in both environments.
I close the issue, update the code, monitor further and come back when it happens again.

thanks Wil
