### ISSUE TITLE
Database plugin: SUM und COUNT Funktionen in den 'series' erlauben

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#235]
Diskussion im Forum: https://knx-user-forum.de/forum/supportforen/smarthome-py/1021844-neues-database-plugin auf Seiten 4 und 5

Es wäre IMHO sinnvoll eine COUNT und / oder eine SUM Funktion im Database Plugin zu haben.

Praktischer Usecase:

Ich habe ein Boolean in der Database der die Flamme des Brenners der Therme widerspiegelt. Das heisst ein True wenn der Brenner startet, und ein False wenn der Brenner wieder ausgeht.

Nützlich wäre ein Plot in der SmartVISU indem ich z.B. auf 24 Stunden die Brennerstarts pro Stunde sehe. Oder auf einer Woche die Brennerstarts pro Tag. Zum optimieren der Heizanlage wäre das sehr hilfreich. Das heisst es müsste eine "COUNT" Funktion geben die alle 'True' oder '1' in der DB in einer bestimmten Periode zählt.

Ich könnte mir da noch andere Usecases vorstellen, z.B. irgend eine Messung ergibt 0, -1 oder sonst was bei Fehlern. Dann könnte man mit COUNT von -1 die Anzahl der Fehler pro Periode anzeigen lassen... Bestimmt gibt's noch andere Ideen.

Eine 'SUM' Funktion wäre IMHO auch nützlich. Beispiel wenn ein Gerät einen Verbrauch pro Stunde als Zahl liefert könnte man mit einer 'SUM' Funktion den Verbrauch pro Tag in der Woch zusammenrechnen lassen.

# Implementierung
Zusammengefasst aus der Diskussion wird folgendes zur Implementierung vorgeschlagen.
## Funktion `sum`
Die Aggregatsfunktion `sum` kann ohne groesser Anpassungen einfach integriert werden und wird zusaetzlich zu `max/min/avg/on` zur Verfuegung gestellt.

Der Aufruf wuerde so aussehen:
`sh.item.db('sum', '2h', 'now')`

## Funktion `count`
Das zaehlen von Werten wird ueber eine neue Funktion implementiert: `count`. Per Default werden alle Werte `!= 0` gezaehlt. Zusaetzlich kann dieses Kriterium ueberschrieben werden in dem folgendes Format verwendet wird `"count"<op><value>`. Als Operatoren werden `!=` bzw. `<>`, `>`, `<` und `=` unterstuetzt.

Aufrufe wuerden so aussehen: 
`sh.item.db('count!=0', '2h', 'now')  # zaehlt Werte != 0 (default)`
`sh.item.db('count>0', '2h', 'now')  # zaehlt Werte groesser 0`
`sh.item.db('count<0', '2h', 'now')  # zaehlt Werte kleiner 0`
`sh.item.db('count=0', '2h', 'now')  # zaehlt Werte gleich 0`

## Funktion `diff`
Diese Funktion liefert die jeweilge Veraenderung zum Vorwert indem statt dem eigentlichen Wert die Differenz zum Vorwert zurueck geliefert wird. Die Werte werden durch die zusaetzlich angegebene Aggregatsfunktion - wie bisher - ermittelt.

Der Aufruf wuerde so aussehen:
`sh.item.db('diff:avg', '2h', 'now')`

## Funktion `raw` / `val`
Liefert die Einzelwerte ohne Aggregation zurueck mit der Einschraenkung, dass dadurch entweder
* die Menge der Eintraege nicht dem `count`-Parameter entspricht (weniger Werte als `count` und somit die Einschraenkung durch Abfragezeitraum greift) oder
* die Eintraege nicht bis zum Startzeitpunkt der Abfrage zurueck geliefert werden (mehr Werte als `count` und somit Einschraenkung durch `count`-Parameter)

## Sonstiges
* [x] andere Plugins werden nicht angepasst (wie z.B. `sqlite` oder `rrd`)
* [x] die `growth` Funktion muesste noch wissen, auf welche Aggregation die Abfrage basiert (avg, max, ...) -> wird dann so angegeben `growth:avg` oder `growth:val`
* [x] ist 'growth' der richtige Name -> nein, daher wird es nun `diff` sein

**Comment by ohinckel** [comment]
> We wäre IMHO sinnvoll eine COUNT und / oder eine SUM Funktion im Database Plugin zu haben.

SUM ist einfach einzubauen, da man die Aggregatsfunktion nur ersetzten muss.

Bei COUNT ist die Frage was man zaehlen moechte: nur Werte != 0, Werte innerhalb eines Bereiches, True / False, ... Vielleicht ist fuer die genannten Faelle auch das `ON` schon ausreichend?

**Comment by Foxi352** [comment]
Meiner Meinung wäre COUNT am flexibelsten wenn man das was gezählt werden soll als Parameter angeben könnte ?

**Comment by ohinckel** [comment]
Ja, wuerde aber bedeuten, dass man diesen Parameter auch z.B. von der Visualisierung uebergeben muesste und man dort ebenfalls Anpassungen vornehmen muesste.

Das koennte man aber evtl. durch unterschiedliche Funktionsparameter umgehen: aktuell min, max, avg, on,neu dann z.B. count-high und count-low (oder aehliches).

Welche Werte, ausser true/false bzw. high/low oder on/off, muesste man sonst noch zahelen koennen?

**Comment by smaiLee** [comment]
Wenn ich mich nicht irre, könnte man in der smartVISU auch sowas wie count=1 oder sogar count>0 setzen (der Ausdruck darf nur keine Punkte `.` enthalten).
Dies müsste dann in SHNG zerlegt werden.
Und als Standard, also wenn kein Parameter angegeben ist, sollte >0 verwendet werden.

**Comment by Foxi352** [comment]
Das wäre eventuell die optimale Lösung für count. Nehmen wir an ein Temperatursensor z.B. schickt bei Fehler 999 als Wert zurück (gibt ja anscheinend komische Sachen :-) ), dann kann man mit count=999 die Anzahl der Fehler pro Stunde / Tag / wie_auch_immer anzeigen lassen.

**Comment by ohinckel** [comment]
Hoert sich nach einen guten Vorschlag fuer `count` an.

Was machen wir mit den anderen Plugins, die als Datenquellen eingesetzt werden koennen (`sqlite`, `rrd`)? Anfangs der Database-Plugin-Entwicklung hatte ich mir schon ueberlegt ein einheitliches Interface fuer diese Plugins zu schaffen. Bisher sind die Plugins zueinander kompatibel und koennen ausgetauscht werden ohne dass man Anpassungen vornehmen muss. Solche Spezialloesungen machen das ganze dann inkompatibel.

Oder verzichten wir zukuenftig auf andere Plugins?

**Comment by Foxi352** [comment]
Also zumindest für sqlite bin ich persönlich der Meinung, dass es eigentlich obsolete ist sobald das database Plugin als stable und als default in shng eingebettet ist. Mit rrd habe ich noch nichts gemacht, ich nutze allerdings das influxdb plugin. Doch damit mache ich keine Plots in SV sondern in Grafana. Kann man denn mit dem rrd Plugin Plots in der SV anzeigen lassen ?

**Comment by smaiLee** [comment]
rrd steht ja anscheinend bereits auf der Abschussliste: https://knx-user-forum.de/forum/supportforen/smarthome-py/1115103-rrd-plugin-wird-es-noch-genutzt
Und sqlite brauchts IMHO nicht mehr, man kann ja auch im database Plugin sqlite als DB nutzen.

Und das bisherige würde ja weiter funktionieren, solange man die neuen Funktionen nicht verwendet.

**Comment by bmxp** [comment]
Ich denke solange sich count nur auf einen Binären Wert bezieht, wäre es relativ einfach. Im Zusammenhang mit count denke ich aber auch an die Anzahl von unterschiedlichen Werten von Ganzzahlen die prinzipiell verschieden Stati representieren (z.B. Statusmaschine)

**Comment by msinn** [comment]
@bmxp schrieb am 30. Juli in Issue https://github.com/smarthomeNG/smarthome/issues/218:

> I wished that visu_websocket plugin could provide also real values for a series (instead of only sum, avg, min or max).
>
> Just val to provide a real measurement. Together with the new database plugin we could then e.g. display correct measurements.

Auf Vorschlag von @ohinckel übernehme ich das mal in dieses Issue.

**Comment by smaiLee** [comment]
Obwohl ich den Vorschlag den diskreten Werten per val unterstütze, wirft das eine Fragen auf:
Wie soll mit Widersprüchen zwischen Anzahl vorhandener Datenpunkte in der gewählten Zeitspanne und dem Parameter count umgegangen werden?
Wird count einfach ignoriert oder wird es als maximale Anzahl verstanden?

Konkretes Beispiel:
Ich rufe die letzten 24h ab und habe darin pro Stunde 10 geloggte Werte, also Total 240. Count liegt bei 100.
Werden nun nur die letzten 100 Werte geliefert, also nur Daten der letzten 10 Stunden? Oder alle 240.

**Comment by bmxp** [comment]
Ist ein wenig auch eine Frage, ob in der Visu z.B. der User parametriert hat 1.000 Werte oder ob es sich dabei um einen defaultwert handelt. Wenn der User mitgibt, **maximal 1.000 Werte** dann darf SHNG eben nur 1.000 Werte liefern. Ist nur die Frage ob zeitlich die ersten 1.000 Werte (älteste Werte) oder die neuesten Werte.

**Comment by ohinckel** [comment]
Ich wuerde $count Eintraege von $end aus gesehen zurueckliefern. Bedeutet dann, dass man nicht unbedingt Daten bis zu $start zurueck bekommt, weil z.B. bis zu $start mehr Daten vorhanden sind als in $count angegeben.

Alternativ kann man in diesem Fall $count auch komplett ignorieren und alle Daten zurueck liefern, die in den Zeitraum fallen (vielleicht waere dann der Name `raw` statt `val` besser?).

**Comment by ohinckel** [comment]
Weil die Abfrage von Veraenderungen der Werte schon im Forum ein Thema waren, habe ich das noch mit aufgenommen. Man muss sich noch ueberlegen
* ob man die Funktion `raise` oder `growth` nennen moechte
* wie man die zugrundeliegende Aggregatsfunktion angibt (z.B. `avg.growth`, `growth:avg`, ...)

**Comment by ohinckel** [comment]
Ich habe nun folgendes implementiert:
* es gibt eine `sum` Funktion
* es gibt eine `val` Funktion
* es gibt eine `count` Funktion

Zusaetzlich zu diesen neuen Funktionen kann man noch eine "finalizer" Funktion angeben, die das eigentliche Ergebnis nochmal ueberarbeitet bzw. finalisiert. Damit wir z.B. das `diff` abgebildet. Bisher gibt es auch nur diese Finalisierungsfunktion die man als Prefix vor die andere Funktion davorschreiben kann, z.B:
* `diff:avg` - liefert die Differenzwerte fuer die `avg` Werte
* `diff:val` - liefert die Differenzwerte fuer die `val` Werte
* usw.

Ich habe es jetzt `diff` statt `growth` genannt, weil sich letzteres mehr nach einen Prozentwert anhoert als nach einer Differenz.

Bitte mal ausprobieren und testen.

**Comment by psilo909** [comment]
@Foxi352 ich fände die bezeichnung RAW statt VAL auch besser.. was denkst du?

**Comment by Foxi352** [comment]
> @Foxi352 ich fände die bezeichnung RAW statt VAL auch besser.. was denkst du?

Ehrlich gesagt hab ich da keine Präferenz solange die Funktion das richtige macht. Hab gerade auf den branch geswitched und werd mal testen. Beide Bezeichnungen sind für mich klar zu verstehen, von mir aus ist ein Wechsel also ok.

**Comment by psilo909** [comment]
@ohinckel magst du das dann noch umbenennen? :>

**Comment by ohinckel** [comment]
Habe es soeben umbenannt. Heisst jetzt `raw` statt `val`.

**Comment by ohinckel** [comment]
PR https://github.com/smarthomeNG/plugins/pull/93 wurde gemerged, damit schliesse ich das Issue.
