### ISSUE TITLE
Backend / Logics editor

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#236]
Im Backend auf der Codemirror Seite ist ein Knopf "Speichern und neu laden".

Leider macht der Code dahinter nicht nur das was der Knopf suggeriert sondern er triggert die Logik auch noch. Das ist sehr oft unerwünscht.

Ich würde entweder das triggern entfernen, oder einen weiteren Knopf "Speichern, neu laden und triggern" hinzufügen.

**Comment by Foxi352** [comment]
Ist durch commit c493fda gelöst worden

**Comment by psilo909** [comment]
should be implemented now. @msinn should please x-check my push.
