### ISSUE TITLE
after update device.rtr plugin doesn't work anymore

### ISSUE THREAD

**Issue by geertge** [smarthomeNG/smarthome#238]
After update I can't change the mode anymore and change the set temperature. What do I need to change to let it work again?

On the webpage the device.rtr config is the follow:

 {{ device.rtr('AP0705RTR', 'Heating', 'AP0705.Living.temp', 'AP0705.Living.set', 'AP0705.Living.mode', 'AP0705.Living.mode', 'AP0705.Living.mode', 'AP0705.Living.state') }}

The items are configured as follow

[AP0705]
    [[Living]]
        [[[temp]]]
                type = num
                visu = yes
                visu_acl = r
                history = true
                knx_dpt = 9
                knx_listen = 2/0/0
                knx_init = 2/0/0
	        sqlite = yes
	[[[set]]]
                type = num
                visu = yes
                 visu_acl = rw
                 history = true
                 knx_dpt = 9
                 knx_send = 2/1/1
                 knx_listen = 2/1/1
                 knx_init = 2/1/1
		sqlite = yes
        [[[mode]]]
               	type = num
               	visu = yes
               	visu_acl = rw
               	knx_dpt = 5
               	knx_listen = 2/1/2
               	knx_send = 2/1/2
               	knx_init = 2/1/2
		sqlite = yes
          [[[state]]]
              	type = num
               	visu = yes
               	visu_acl = r
               	history = true
               	knx_dpt = 5
               	knx_listen = 2/1/6
               	knx_init = 2/1/6
		sqlite = yes

**Comment by ohinckel** [comment]
Please check the log first for errors or warnings and report back. There should at least something about reserved keywords (e.g. you can not use keywords in item structure - details see #132 and #180).

Check if it works when renaming the items and not using keywords in the names.

**Comment by geertge** [comment]
OK, problem solved. The words set, state and mode changed.

Thanks

Van: ohinckel [mailto:notifications@github.com]
Verzonden: vrijdag 6 oktober 2017 16:47
Aan: smarthomeNG/smarthome <smarthome@noreply.github.com>
CC: geertge <hans_geert@msn.com>; Author <author@noreply.github.com>
Onderwerp: Re: [smarthomeNG/smarthome] after update device.rtr plugin doesn't work anymore (#238)


Please check the log first for errors or warnings and report back. There should at least something about reserved keywords (e.g. you can not use keywords in item structure - details see #132<https://github.com/smarthomeNG/smarthome/pull/132> and #180<https://github.com/smarthomeNG/smarthome/issues/180>).

Check if it works when renaming the items and not using keywords in the names.
