### ISSUE TITLE
Redesign of Travis test runs

### ISSUE THREAD

**Issue by msinn** [smarthomeNG/smarthome#240]
At the moment, when you make a commit to a plugin no test is run at all. But if you make a commit to the core, the plugin tests are run.

If someone commits a faulty plugin an you make a commit to the core afterwards, the core build is flaged as faulty.

@ohinckel wrote in a commit comment:

> If we want to have the tests running for both (core and plugins) let me know. I will try to set this up. IMHO I would configure the following in Travis:
>
> - each commit to master of core will just run the tests in master branch with plugin version of this master branch
> - each commit to develop core will run the tests in develop branch with plugin version head of develop of plugins
> - each commit to develop of plugin will run the tests like the one above (both with head of develop branches)
> 
> With this we do not need to bump the plugin repo version in core to the latest to usethe develop version. But we could also add a commit hook which updates the plugin version in core to the latest version each time one commits to the plugin repo. Will also result in executing tests with the latest versions.

I don't konow if we need Tests on the master branch, since it is derived from a testet development commit.

What I like to see is:

- a commit to the plugins repo starts a test run that:
  - checks out the core
  - checks out the plugins
  - runs the plugins tests
  - records the result in the plugins repo
- a commit to the core repo  starts a test run that:
  - checks out the core
  - checks out the plugins
  - runs the core tests
  - records the result in the core repo

I am not sure, if it is helpful to run the plugin tests on a core commit. At least the results of the plugin tests shouldn't break the core test.

**Comment by ohinckel** [comment]
The plugin tests should be executed on a core commit too. The core is used by plugins and if the API changes the plugins should still be able to use that API. When not running tests we will not know if we introduce a breaking change in the core and plugin will start to break.

**Comment by msinn** [comment]
Ok understood, but then every plugin with an error breaks the core (as it is now).

A way could be, to run the tests on the core and then start a test run on the plugins repo, that reports the errors to the plugins repo not the core's repo.

**Comment by ohinckel** [comment]
> and then start a test run on the plugins repo

This requires a more complex setup in GitHub and Travis-CI. I think it is not a problem when broken plugins will break the core test run too. They should always be working for at least the same branch.

So I suggest to run the suites for both repositories in the nearly the same way by always checking out both repositories and running the suite. The origin branch defines which branch will be used for the checkouts:
* commits to `develop` with checkout both in `develop` branch
* commits to 'master' will checkout both in `master` branch
* commits to other branch will checkout both in `develop` branch

In this setup the submodule of the core repo is not used anymore when running tests (even in the master branch). But we still need to update the link manually to keep our versions up to date. But I think this is something we always need to do manually (in `develop` branch when developing and in `master` branch when releasing). Just for the test suite this is not required anymore.

I tried to setup this in Travis-CI by modifying the `.travis.yml` configuration a little bit in [core](https://github.com/ohinckel/smarthomeNG-core/blob/issue-240/.travis.yml) and [plugins](https://github.com/ohinckel/smarthomeNG-plugins/blob/issue-240/.travis.yml) and creating a `.travis.sh` script in [core](https://github.com/ohinckel/smarthomeNG-core/blob/issue-240/.travis.sh) and [plugins](https://github.com/ohinckel/smarthomeNG-plugins/blob/issue-240/.travis.sh) which is doing the main parts to running the tests now (also checks which repos should be checked out in which branches).

This script could also be extended to run the documentation build and put then online somewhere (but currently I don't know how to run this build and how to upload the data then).

Currently the output can be viewed here:
* for the [core](https://travis-ci.org/ohinckel/smarthomeNG-core/builds/297334013) repository
* for the [plugins](https://travis-ci.org/ohinckel/smarthomeNG-plugins/builds/297333783) repository

**Comment by msinn** [comment]
As an ideas for the future: Would it be possible to run the plugin tests against different versions of the master branch to see if a plugin ist supporting those different core versions?

I know, it is a bit far fetched since only few plugins have tests right now.

**Comment by msinn** [comment]
For automatic documentation builds, it is a bit too early, since the structure of the documentation is changing right now by introducing a user documentation separate from the developer documentation.

For info how you can build the documentation yourself, just take a look at [/doc/how-to-build-docs.rst](https://github.com/smarthomeNG/smarthome/blob/develop/doc/how-to-build-docs.rst)

**Comment by ohinckel** [comment]
Sure running tests against differen versions should be possible (by adding env vars containing tags and let Travis CI build up a execution matrix with the values). But do we release newer versions of plugins for older SHNG version?

For the doc thing, I think it is usedful to build this and upload this somewhere. At least for us as developers. This way we can easily check if the doc build is still working when a PR is opened. I would also just upload this somewhere (hidden, like a subpath of smarthomeng.de as an inofficial documentation for developers) representing the current develop state. Of course the docs are changing always - but this should not be a problem. We could just remove the complete docs from the server and just upload the new version. It doesn't mater if it is well structured or not, it is just the current state. I really like to have this build and uploaded somewhere, but when others don't see a benefit we could skip this.

**Comment by msinn** [comment]
> But do we release newer versions of plugins for older SHNG version?

Some plugin authors to offer backward compatibility for one or two versions. Not all users update their installation when a new release comes out, but thy might want a plugin from the actual master.

>  (hidden, like a subpath of smarthomeng.de as an inofficial documentation for developers) 

I do this regularly. The actual (hidden) published version of the docu for the developer banch is dated:

_This documentation reflects the current Release 1.3c develop (as of 31. October 2017, commit 34c17bf)._

**Comment by ohinckel** [comment]
> I do this regularly.

Yes you can do it. But I don't like manual steps for what can be automated. And other developers can also see their updated documentation without knowing how to build it. Maybe they would also be able to fix some documetation bugs when reviewing the auto-generated documentation while working on a PR.

**Comment by msinn** [comment]
At the moment automation of the build process wouldn't do any good, since the massive changes to the way the documentation is structured could from time result in a non functional documentation or simply show wrong info. 

I start getting tired of this discussion. I see two way out:

1. You stop falling onto my nerves with this issue
2. I stop creating the documentation and you can create and automate all the way you want.

**Comment by ohinckel** [comment]
OK, maybe the current state is not useful for an automated build, agreed. I just want to reduce manual work for all of us and help avoiding [problems](https://github.com/smarthomeNG/plugins/pull/83#issuecomment-340532850) when building the documentation after a merge.

Maybe we can just integrated it in the Travis CI build and try to build the documentation (using the script you provide) without publishing it somewhere? Just to know that it is broken or still OK after a commit/merge. Could this be helpful? Or is it also useless since it could also break due to other changes/refactoring of the docs?

**Comment by msinn** [comment]
The final stage should be an automatic build. That's why I wrote a tool fetching the metadata from the plugins to automatically build documentation pages. But for a complete automatic build the user documentation should be somewhat complete and multi language support for the user documentation should be implemented. (User documentation should be German and be able to be translated into English). 

But for that I have to fiddle with Sphinx and with gettext for internationalization (i18n) and localization (L10n).

**Comment by msinn** [comment]
I ran into some trouble with the travis setup and I don't know what the trouble is detail.

I started to rework the core. Moving things out of bin.smarthome to the libs/classes thy belong to.

- I created a branch **reworked_core**
- I did the modifications to the core and the tests for the core (locally all tests succeed)
- I committed the changes and the travis tests failed.

In Detail: All core tests succeeded, only plugin tests failed. To be more precise: Only tests of the database plugin failed (48 of 55 tests failed, 1 was skipped) and I have no Idea why they fail on travis but not locally.


When I commit to branch **reworked_core**, from where are the plugins fetched for testing? From develop?

**Comment by msinn** [comment]
I hat some success. I found another part in the mockup that had to be changed for the reworked core. 

And I found out, why the tests succeed locally: I looks like the plugin tests for the database plugin are not running, when running the tests locally. 

@ohinckel Have you an idea why the tests behave different when run locally?

**Comment by ohinckel** [comment]
My local setup having core and plugins in `develop` executes the tests from `test_basic.py` of database plugin (and all passes).

According to the Travis logs of faild run the error is the missing `id()` method which is provided by the `database` plugin for all items confgiured for database access. But it seems the test items (from `plugins/database/tests/test_items.conf`) are not configured properly (maybe a path issue?). But looking at your [fix commit](https://github.com/smarthomeNG/smarthome/compare/13f1471987bb...bad5379d5aca), I don't understand why this is fixing the problem. It is just using `lib.item.Items()` instead of the internal items dict (which should get filled up by `with_items_from()` call in tests). Where is the place which updates the `lib.item.Items()` object there?

**Comment by msinn** [comment]
The place is im lib.items itself. I moved the item handling from bin.smarthome to lib.item. I just forgot to change the mockup routine. In bin.smarthome the old methods are changed to call the new methods in lib.item (to ensure nomfunctionallity is broken) until no plugin or logic calls the old methods any more.

**Comment by ohinckel** [comment]
OK, thanks for clarification.

I want to close this issue in the next days and keep the Travis build as described [previously](https://github.com/smarthomeNG/smarthome/issues/240#issuecomment-341929570). This will take care to run tests with the recent versions of the branches (both modules, core and plugins, will always be checkout in the same branch, but the newest version).

It could also be extended to run tests against different branches, but I would suggest to do this later.

@msinn, what do you think? Had time to check the Travis build logs mentioned above?

**Comment by msinn** [comment]
I know about the travis logs. I check them whenever the tests fail.

Could you write a wiki article about usage of the test environment? I think that would be helpful to plugin developers. At the moment they have (more or less) to reengineer how it works on another plugin to be able to write tests.

**Comment by ohinckel** [comment]
I have started to write [documentation](https://github.com/smarthomeNG/smarthome/wiki/Tests) about tests. Please review, extend, etc.

When we merge this PR I will update the PR, especially the Travis-CI section.

**Comment by ohinckel** [comment]
The documentation was update a little bit to describe the Travis-CI execution process.

**Comment by ohinckel** [comment]
Update the documentation further. So check if there's something missing. From my point of view we can close this now.
