### ISSUE TITLE
Http Modul opens port 8080 on localhost

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#242]
Dummy modul disabled. Http modul enabled on port 8383

```
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      16902/python3       
tcp        0      0 192.168.1.5:8383        0.0.0.0:*               LISTEN      16902/python3       
tcp        0      0 192.168.1.5:8384        0.0.0.0:*               LISTEN      16902/python3       

```

CherryPy always opens port 8080 on localhost for no apparent reason.
SHNG does error out on startup if anything already bound on localhost:8080

**Comment by bmxp** [comment]
Could you please give us the cherrypy version you are running on? Mine is 10.0 but I don't have that issue here...

**Comment by Foxi352** [comment]
11.1.0, but can confirm i have the same when downgrading to 10.0.0.

**Comment by bmxp** [comment]
Ok, it's buried in the nature of cherrypy:

Have a look at cherrypy/__init__.py around line 175:
```
engine.signals = _HandleSignalsPlugin(engine)

server = _cpserver.Server()
server.subscribe()
```

You see there is already a server defined ex works. You can check that if you start an interactive pythone console:

```
>>> import cherrypy
>>> cherrypy.server.socket_port
8080
>>> cherrypy.server.socket_host
'127.0.0.1'
```

This is what you have. If you examine the code for the http module, then IMHO this server object is not changed anywhere and as soon as the bus starts, then this server starts to listen at its default port and ip.

Having a look at the http module reveils:
```
        # Update the global CherryPy configuration
        cherrypy.config.update(global_conf)

        self._server1 = cherrypy._cpserver.Server()
        self._server1.socket_port=int(self._port)
        self._server1.socket_host=self._ip
        self._server1.thread_pool=self.threads
        self._server1.subscribe()

        if self._port != self._servicesport:
            self._server2 = cherrypy._cpserver.Server()
            self._server2.socket_port=int(self._servicesport)
            self._server2.socket_host=self._ip
            self._server2.thread_pool=self.threads
            self._server2.subscribe()

```

We might assign self._Server1 = cherrypy.server but I would ask @msinn if there are other reasons why he chose the current implementation.

**Comment by msinn** [comment]
Module has been changed and @Foxi352 confirmed, that the problem is fixed.
