### ISSUE TITLE
Useless code in KNX plugin

### ISSUE THREAD

**Issue by smaiLee** [smarthomeNG/smarthome#246]
I think I've found some useless or even wrong code in KNX plugin:

1. `self._lock = threading.Lock()` on [line 105](https://github.com/smarthomeNG/plugins/blob/00f151b23aea74ea299134c5e19b7a074cc54a58/knx/__init__.py#L105)  
If I didn't miss something, this property is never used.
Afterwards the `import threading` on [line 37](https://github.com/smarthomeNG/plugins/blob/00f151b23aea74ea299134c5e19b7a074cc54a58/knx/__init__.py#L37) can be removed also.

1. `self.handle_close()` on [line 388](https://github.com/smarthomeNG/plugins/blob/00f151b23aea74ea299134c5e19b7a074cc54a58/knx/__init__.py#L388)
I think this should be `self.close()` as `self.handle_close()` does nothing.  
`handle_close` is a method which can be implemented in objects which inherit from lib.connections.Stream. This is called in `Stream.close()` before the socket gets closed.
But in the KNX plugin `self.handle_close` is not implemented.

1. `if self.connected:` on lines [234](https://github.com/smarthomeNG/plugins/blob/00f151b23aea74ea299134c5e19b7a074cc54a58/knx/__init__.py#L234) and [250](https://github.com/smarthomeNG/plugins/blob/00f151b23aea74ea299134c5e19b7a074cc54a58/knx/__init__.py#L250)
The surrounding method `handle_connect` is called in lib.connection.Stream right one line below setting self.connected to true, so at the beginning of the method self.connected is always true.
If an exception happens in between we have a bigger problem and should not just ignore a closed connection but leave the method immediately.

**Comment by Foxi352** [comment]
Should be fixed by https://github.com/smarthomeNG/plugins/commit/303030feeeec73c4d814cde4e4d71e7c460579f2
