### ISSUE TITLE
UZSU: sunset/sunrise w/o RRULE

### ISSUE THREAD

**Issue by smaiLee** [smarthomeNG/smarthome#247]
There seems to miss an _ on [line 210](https://github.com/smarthomeNG/plugins/blob/00f151b23aea74ea299134c5e19b7a074cc54a58/uzsu/__init__.py#L210) of UZSU plugin. `next = self.sun(` should be `next = self._sun(`. Otherwise the using of sunset and sunrise without defining an RRULE will not work.

**Comment by bmxp** [comment]
Yes. Unfortunately no one ever seems to use sun* without rrule as the SmartVISU will always provide such an entry. And as long as there is an rrule entry this code will never be reached ...
So confirmed for develop. My local changes in uzsu plugin already included this fix but as I am still testing on the other problem of missed actions I did not push so far...

**Comment by smaiLee** [comment]
The always provided entry is not OK, because an empty string leads to an error. So I have to change this.

Regarding the other problem:
Actually I have problems to comprehend the RRULE part of the code. Is it really necessary to first try parsing and if this fails because of the sun-part parse the sun-string with yesterday's date? And then, some lines later,  the sun-string is parsed again with today's date.
I cant follow this.

**Comment by bmxp** [comment]
You would need to ask @mworion about this approach. But I might refactor it in future and thus change it. But there should be tests set up and I will have to read more about it before I change an implementation.

**Comment by smaiLee** [comment]
@mworion is the creator of the smartVISU widget, the plugin is made by @2ndsky.

**Comment by bmxp** [comment]
Yes, you are right sorry for mixing it up! Not sure if Nico is still involved ...

**Comment by bmxp** [comment]
The missing _ as described in the opening post was fixed. As @2ndsky is not active any more and currently no one works on the uzsu as the sun/moon this are about to be refactored for version 1.6 (?) i close this issue.
Please open a new issue when problems still arise after refactoring of sun/moon stuff.
