### ISSUE TITLE
BackendServer gives error on startup. 

### ISSUE THREAD

**Issue by realhik** [smarthomeNG/smarthome#250]
When using the BackendServer as
```
BackendServer:
    class_name: BackendServer
    class_path: plugins.backend
    # ip = xxx.xxx.xxx.xxx
    port: 8383
    updates_allowed: 'True'
    threads: 8
    user: admin
    password: xxxx
    language: de
```

the following error occurs in the log file:
```
2017-12-18  22:39:57 ERROR    Main         Plugin 'backend' from section 'BackendServer' exception: 'Http' object has no attribute 'shortname'
Traceback (most recent call last):
  File "/usr/local/smarthome-v1.4/lib/plugin.py", line 111, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance, self.meta)
  File "/usr/local/smarthome-v1.4/lib/plugin.py", line 413, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthome-v1.4/plugins/backend/__init__.py", line 146, in __init__
    self.logger.warning('{}: Using module {}'.format(self.classname, str( self.mod_http.shortname ), str( self.mod_http.version ), str( self.mod_http.longname ) ) )
AttributeError: 'Http' object has no attribute 'shortname'
```

When I comment the specific line I get 
```
2017-12-18  22:46:59 ERROR    Main         Plugin 'backend' from section 'BackendServer' exception: 'Http' object has no attribute 'register_app'
Traceback (most recent call last):
  File "/usr/local/smarthome-v1.4/lib/plugin.py", line 111, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance, self.meta)
  File "/usr/local/smarthome-v1.4/lib/plugin.py", line 413, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
  File "/usr/local/smarthome-v1.4/plugins/backend/__init__.py", line 163, in __init__
    self.mod_http.register_app(Backend(self, self.updates_allowed, language, self.developer_mode, self.pypi_timeout),
AttributeError: 'Http' object has no attribute 'register_app'
```

**Comment by psilo909** [comment]
looks like you did not update to SmartHomeNG 1.4. the backend in the master plugin branch now requires the new release to be used.

**Comment by msinn** [comment]
You are using an old version of the backend Plugin. That is incompatible with SmartHomeNG v1.4. Install the actual plugins.

**Comment by realhik** [comment]
My initial recursive checkout of v1.4-rc1 and switch to branch 1.4 did not affect the submodules. This is related to @msinn's comment in [issue 249](https://github.com/smarthomeNG/smarthome/issues/249) "The v1.4-rc1 branch was never intended to be used as an installation source, so it didn't reference the actual commit in the plugin repository. So, you are using a lot of old plugin versions." 

It would be nice if the main/standard/important plugins would belong to the base repository, e.g. `plugins-base`. Other maintained plugins could be placed in `plugins-extra`. Other plugins could just be referenced as long as they are not up to date in `plugins-experimental`.

**Comment by msinn** [comment]
How did you install SmartHomeNG v1.4?

I guess you installed over an existing installation. If so, you have to execute the script **bin/fetch_plugins.sh** to get the actual version of the plugins.

If you are doing a fresh install, the actual versions of the plugins. are checked out automatically.

This stands true regardless of the branch you are installing from (master or develop). 

Only for the rc1 branch (which was only a working branch for preparing the release) that was not true.  A run of **bin/fetch_plugins.sh** wouldn't have helped on that branch.

**Comment by realhik** [comment]
I installed it by checking out branch v1.4-rc1. (As I remember) I then did a `git submodule update --recursive --remote` or similar. The latter didn't obviously reference the actual commit in the plugin repository. Anyway, the problem is solved.
