### ISSUE TITLE
SQLITE for smartvisu 2.8 function problem

### ISSUE THREAD

**Issue by zobi** [smarthomeNG/smarthome#255]
Hi, i upgrade my install from RRD to SQLITE_VISU2.8

In documentation i've read that some function exist like avg, min max
But it doesn't work.

For exemple : 
`>>> sh.ext.temp()
3.9
` works fine

But : 
```
`>>> sh.ext.temp.db('min','1h')
2018-02-19 15:53:07 ERROR    smarthome    Main         Unhandled exception: 'SQL' object has no attribute '_frames'
<class 'AttributeError'>
  File "/usr/local/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/KNX/smarthomeNG/plugins/sqlite_visu2_8/__init__.py", line 373, in _single
    start = self._get_timestamp(start)
  File "/KNX/smarthomeNG/plugins/sqlite_visu2_8/__init__.py", line 242, in _get_timestamp
    elif frame[-1] in self._frames:
 -- smarthome.py:_excepthook:911
>>>` 
```
return error 

item is declare like this 
`
ext:

    temp:
        name: Température Extérieur
        type: num
        ow_addr: 28.5F1848050000
        ow_sensor: T
        eval: round(value, 1)
        knx_dpt: 9
        knx_reply: 1/0/100
        knx_send: 1/0/100
        sqlite: 'yes'
`

and plugins is call with this : 
`sql:
    class_name: SQL
    class_path: plugins.sqlite_visu2_8
`

I use python 3.6 thanks a lot for your help

**Comment by ohinckel** [comment]
Which version of SHNG are you using currently? Btw. you could also use the `database` [plugin](http://smarthomeng.de/user/plugins/database/README.html) instead of the `sqlite_visu2_8` plugin.

**Comment by zobi** [comment]
I use 1.4.2 master
Ok for database plugin i will make some test with it

**Comment by zobi** [comment]
Ok the database plugin is working with max min avg function, but smartvisu didn't work with this plugin ...

**Comment by ohinckel** [comment]
Do you get some error messages (in SHNG log or in browser console)?

**Comment by zobi** [comment]
No error in SHNG or browser console but graph didn't appear in SV with database plugin

**Comment by ohinckel** [comment]
Enabling the debug logging will tell us which queries are executed and what are the results of them.

**Comment by zobi** [comment]
i'm so sorry, 2 SHNG was launch at same time with 2 configurations ...
I try again with just one and database plugin, it work's fine

**Comment by ohinckel** [comment]
No problem. Glad to hear that all is working now.
