### ISSUE TITLE
smarthome.pid

### ISSUE THREAD

**Issue by paul768** [smarthomeNG/smarthome#257]
Hi.
I installed, configured the items, checked with the command -
cd / usr / local / smarthome / bin
python3 ./smarthome.py -d
everything worked perfectly, but then I decided to configure the startup service and there was a problem
- created the file service as in the example:
https://www.smarthomeng.de/user/installation/komplettanleitung_abschluss.html
 an startup error:

> pi@raspberrypi:~ $ sudo systemctl status smarthome.service
● smarthome.service - SmartHomeNG daemon
   Loaded: loaded (/lib/systemd/system/smarthome.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Tue 2018-03-06 13:12:14 UTC; 23min ago
  Process: 982 ExecStart=/usr/bin/python3 /usr/local/smarthome/bin/smarthome.py (code=exited, status=0/SUCCESS)

>Mar 06 13:10:30 raspberrypi systemd[1]: Starting SmartHomeNG daemon...
Mar 06 13:10:31 raspberrypi python3[982]: 2018-03-06 13:10:31 INFO     smarthome    Main         Using config dir: /usr/local/smarthome -- smarthome.py:__init__:196
Mar 06 13:10:31 raspberrypi python3[982]: fork #2 failed: 13 (Permission denied)
Mar 06 13:10:31 raspberrypi python3[982]: Daemon PID 988
Mar 06 13:10:31 raspberrypi systemd[1]: smarthome.service: PID file /usr/local/smarthome/var/run/smarthome.pid not readable (yet?) after start: No such file or directory
Mar 06 13:12:00 raspberrypi systemd[1]: smarthome.service: Start operation timed out. Terminating.
Mar 06 13:12:14 raspberrypi systemd[1]: Failed to start SmartHomeNG daemon.
Mar 06 13:12:14 raspberrypi systemd[1]: smarthome.service: Unit entered failed state.
Mar 06 13:12:14 raspberrypi systemd[1]: smarthome.service: Failed with result 'timeout'.

how to solve it?

**Comment by Foxi352** [comment]
This often happens when you first run it as user 'root', and then later use the service file to run it with a different user, probably use 'smarthome' if you followed the guide.

Try, as user root (or with sudo) to launch `chown -R smarthome:smarthome /usr/local/smarthome` and then try to restart the service.

**Comment by paul768** [comment]
thanks, now works
