### ISSUE TITLE
Entwicklungsguidelines für smarthomeNG

### ISSUE THREAD

**Issue by psilo909** [smarthomeNG/smarthome#26]
Hallo zusammen,

um etwas den Wildwuchs zu verhindern, habe ich angefangen, einen Bereich für Entwicklungs-Guidelines anzulegen:
https://github.com/smarthomeNG/smarthome/wiki/Entwicklungs-Richtlinien

Die Dinge sind nicht in Beton gemauert und ich würde bitten a) neue Vorschläge hier zu äußern b) wenn Probleme mit den bestehenden sind, diese ebenfalls hier zu diskutieren.

**Comment by bmxp** [comment]
Ja, Frage nach Best Practices:

Einige Plugins speichern beim Initialisieren die betroffenen Items in einer Item internen Liste um bei neuen Daten schnell drauf zuzugreifen zu können. Ein Beispiel ist IMHO das Roomba Plugin. Sollten wir mal dynamische Items realisieren wollen, so müßte das ggf. umgebaut werden, oder?

**Comment by psilo909** [comment]
meine haben gleich mehrere Listen und ich möchte betonen, dass mir das machen zu können auf welche Art auch immer wichtig ist ;)

**Comment by psilo909** [comment]
aber der post hat nichts mit dem issue zu tun, oder?

**Comment by bmxp** [comment]
Doch eigentlich schon. Eine Best Practice gehört für mich zu den Guidelines dazu, ebenso wie der Hinweis auf effizienten und lesbaren Code.

**Comment by psilo909** [comment]
ok jetzt verstehe ich, dachte du wolltest das mit den itemliste inhaltlich anbringen, abe das war nur ein beispiel für best practices..

**Comment by ohinckel** [comment]
Wie sieht es eigentlich mit der Stabilitaet von SmartHome.py aus, wenn unterschiedliche Entwickler daran arbeiten? Ich finde, dass die Chance gross ist, dass durch Anpassungen andere Funktionalitaet "kaputt" gehen koennte.

Koennten wir evtl. mal anfangen (vielleicht erstmal auf Core beschraenken) Funktionalitaet mit Tests zu verifizieren?

Sowas wollte ich damals schonmal anfangen - siehe [PR #89 bei mknx](https://github.com/mknx/smarthome/pull/89).

Waere vielleicht auch ein Punkt fuer die Guidelines?

**Comment by psilo909** [comment]
Für mich ok, es muss halt nur wer machen. Unittests möchte ich in Persona mir aktell nicht aufladen, ich poste halt alles was ich finde gleich als Issue... 

Wenns ich jemand bereiterklären würde wäre das aber super!

**Comment by sandman60** [comment]
Volle Zustimmung, das wird normalerweise gebraucht und es ist sinnvoll, m.E. allerdings nur beim Core, bei den Plugins hat m.E. der Entwickler ohnehin die Hand drauf und hat seine indiv. Tests und Tester... 
Beim Core allerdings sollte man doch m.E. vor der Einführung von Tests lieber mal das Freigabeverfahren, nebst Sinnhaftigkeitsprüfung, von Coreänderungen festlegen, sonst kommt da schnell Krüze in den Core die keiner braucht oder aber die Komplexität des ganzen Konstrukts wird massiv in die Höhe schnellen, was dann unweigerlich zu einer fehlenden Akzeptanz führen wird.

**Comment by psilo909** [comment]
Ich denke das Thema könnte sich gut jemand alleine als Aufgabe schnappen. Relativ wenig Konflikte und gut extern von den anderen Entwickler nachzuvollziehen. Plugins würde ich ausschliessen, so lange die Entwicklung so frei wie bisher bleibt. Generell sind Unittests gegen externe Schnittstellen aber sowieso ätzend..

**Comment by cstrassburg** [comment]
Hab die erstellung von Unittests im Rahmen des Issue #35 gesehen
Ich hab dazu jetzt die Tests erstmal in einem eigenen branch gestellt 
siehe https://github.com/smarthomeNG/smarthome/tree/testcases
und die commits aus https://github.com/mknx/smarthome/pull/89 hinzugefügt.
