### ISSUE TITLE
Database plugin: round to 3 decimal places instead of 2

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#261]
That would make calculations like "how many minutes did X run within the last 24 hours" make much more accurate and easier.

Thanks!

**Comment by onkelandy** [comment]
Good question. The config file might not be the "obvious" place to put such a thing. So actually specifying the "accuracy" in the query itself would be a good solution. "2" is standard if nothing is set, but you could set it higher.

**Comment by onkelandy** [comment]
I'm not enough into database to really comment on that.. What does v stand for?

A global precision definition wouldn't hurt in general to define the "standard" if no p=X is given in the query?

**Comment by ohinckel** [comment]
The `v=` defines the value to return (`avg`, `sum`, ...). The `v` should be the abbreviation for `value`.

And yes, we could add a global setting for the default precision. An maybe this is enough for now? You can then configure to return all values with 3 digits. Or do we really need to be able to specify this for each query?

**Comment by onkelandy** [comment]
Got it ;) I guess a global definition of precision might be fine to start with. In general I wonder what's the downside of having a higher precision. Will the calculation time really be worse? And if yes that might only happen with larger time frames, right? That of course would ask for a query-based precision again...

**Comment by ohinckel** [comment]
A global parameter `precision` was added. This can be used to:
* only return integer values (using `precision: 0`)
* use a specific precision (e.g. 3 digits after comma with `precision: 3`)
* do not round at all, just return values as raw floats (`precision: -1`)

@onkelandy, maybe you can try to use `precision: -1` and round the values by yourself. Or just set it to `precision: 3`.

**Comment by onkelandy** [comment]
Tested with precision 3, works fine. Thanks!
