### ISSUE TITLE
Catch exceptions in logics when reloading them. Currently errors make the logic "disappear"

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#263]
If you accidentally make a mistake in a logic an reload that logic it doesn't get found anymore and you have to restart smarthome after fixing the problem completely.

It would be great if the system would still recognize the logic so it can be reloaded again after fixing the error.

example:
```
2018-05-05  19:53:48 ERROR    Main         Exception: invalid syntax (test.py, line 3)
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/logic.py", line 998, in _generate_bytecode
    self.bytecode = compile(code, self.pathname, 'exec')
  File "/usr/local/smarthome/logics/test.py", line 3
    logger.info(sh.now()))
                         ^
SyntaxError: invalid syntax
```

```
CLI > rl test
Logic 'test' not found.
```

**Comment by msinn** [comment]
The logic doesn‘t disapear. If you go to the logics page in backend again and scroll to tge end, the logic should be listed under ‚not loaded logcis‘. Thhere you could klick on the filename to edit it again (and load it)

There has been an error when editing an unloaded logic. That has been fixed in the develop branch.

**Comment by onkelandy** [comment]
Okay, thanks for the info, works with newest develop. Any plans to add a logic in the CLI plugin?

**Comment by msinn** [comment]
I am not thinking about duplicating all features we add to the backend plugin to cli. 

I am only adding from time to time to cli. With new features coming to the backend with every release, I think cli is on a slow way out.

Do you have a special need to use the cli plugin?

**Comment by onkelandy** [comment]
Alright.. no special need. Just think it's somehow easier/faster to let's say list the values of all items containing a specific string for example.

But the issue with the "reload" is solved in the backend - that's fine enough. So I close this issue. Thanks.
