### ISSUE TITLE
Backend shows wrong python package versions ?

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#264]
I upgraded, for example, cherrypy multiple times. Latest was this morning from 14.x.x to 15.0.0.
```
root@srvsmarthome:~# pip show cherrypy
Name: CherryPy
Version: 15.0.0
Summary: Object-Oriented HTTP framework
Home-page: https://www.cherrypy.org
Author: CherryPy Team
Author-email: team@cherrypy.org
License: BSD
Location: /usr/local/lib/python3.5/dist-packages
Requires: cheroot, six, portend
```

But backend still shows a version from month ago. Of course i restarted SHNG, and now i even rebooted the VM completely just to be sure. But result is still the same:
![screen shot 2018-05-27 at 11 27 59](https://user-images.githubusercontent.com/5746932/40584449-0e6a7e3a-61a1-11e8-9cbd-e6a555e50444.png)

I have that same behaviour for some other packages but not for all of them ....

**Comment by psilo909** [comment]
develop version? there are several fixes for pypi and pip10 in develop

**Comment by Foxi352** [comment]
Sorry forgot to specify: Yes, latest devel pull.

**Comment by msinn** [comment]
Do you run shng from the same Python Installation into which you installed the new CherryPy version?

**Comment by bmxp** [comment]
It would be very interesting to know the version of setuptools you are using.

**Comment by Foxi352** [comment]
```
root@srvsmarthome:/usr/local/smarthome# python -V
Python 2.7.13

root@srvsmarthome:/usr/local/smarthome# python3 -V
Python 3.5.3
```

I installed all packages with 'pip3 install'

```
root@srvsmarthome:/usr/local/smarthome# pip3 show CherryPy
Name: CherryPy
Version: 15.0.0
Summary: Object-Oriented HTTP framework
Home-page: https://www.cherrypy.org
Author: CherryPy Team
Author-email: team@cherrypy.org
License: BSD
Location: /usr/local/lib/python3.5/dist-packages
Requires: six, cheroot, portend
```
Still backend shows 11.0 is installed:
![screen shot 2018-06-12 at 21 32 47](https://user-images.githubusercontent.com/5746932/41312745-3048e138-6e88-11e8-9fa2-fd6c354e05b4.png)

```
root@srvsmarthome:/usr/local/smarthome# pip3 show setuptools
Name: setuptools
Version: 39.0.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires:
```

**Comment by msinn** [comment]
Wie startest Du shng und welche Python Version zeigt Dir das Backend an?

**Comment by Foxi352** [comment]
![screen shot 2018-06-13 at 07 31 38](https://user-images.githubusercontent.com/5746932/41331989-1fefeddc-6edc-11e8-852e-a9c24b103b79.png)

```
serge@srvsmarthome:/etc$ cat /etc/systemd/system/default.target.wants/smarthome.service
[Unit]
Description=smarthomeNG daemon
After=network.target

[Service]
Type=forking
ExecStart=/usr/bin/python3 /usr/local/smarthome/bin/smarthome.py
User=smarthome
PIDFile=/usr/local/smarthome/var/run/smarthome.pid
Restart=on-abort

[Install]
WantedBy=default.target
```

**Comment by bmxp** [comment]
Was sagt ``ls -la /usr/local/lib/``?

Bist Du sicher, das Du SmartHomeNG neu gestartet hast, also den Dienst? Ich habe das mal nachgestellt und solange ich SmartHomeNG nicht neu starte, zeigt er mir im Backend was altes an.
Der relevante Code im Backend
```
import pkg_resources
ws = pkg_resources.working_set
for w in ws: print(w)
```
Bekommst Du da die richtige Version angezeigt?

**Comment by Foxi352** [comment]
```
serge@srvsmarthome:~$ ls -la /usr/local/lib/
total 24
drwxrwsr-x  6 smarthome smarthome 4096 Aug 29  2017 .
drwxrwsr-x 13 smarthome smarthome 4096 Apr  2 14:23 ..
drwxrwsr-x  4 smarthome smarthome 4096 Dec 10  2017 python2.7
drwxrwsr-x  3 smarthome smarthome 4096 Jun 21  2016 python3.4
drwxrwsr-x  3 root      staff     4096 Aug 29  2017 python3.5
drwxrwsr-x  3 smarthome smarthome 4096 Apr  9  2017 x86_64-linux-gnu
```

Das Problem habe ich schon sehr lange. Einige packages zeigen die neuste Version an, andere zeigen immer die gleiche alte Version an obwohl ich inzwischen mehrmals geupgraded habe. SHNG starte ich regelmässig neu, das ist sicher nicht das Problem.

Die Überreste von python3.4 sie ich hier sehe könnten eher das Problem sein ?

**Comment by bmxp** [comment]
Hast Du den Code von oben mal im python3 interaktiv ausprobiert? Bekommst Du da die richtige Version angezeigt?

**Comment by Foxi352** [comment]
```
serge@srvsmarthome:~$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> ws = pkg_resources.working_set
>>> for w in ws: print(w)
...
[ .... rausgeschnitten ... ]
CherryPy 15.0.0
[ .... rausgeschnitten ... ]

```

**Comment by bmxp** [comment]
Das würde bedeuten, das der gleiche Code im Backend was anderes ergibt, als das, was Du oben eben getestet hast.
Kannst Du den Service mal beenden und SmartHomeNG im debug-Modus laufen lassen und schauen, ob das dann nach wie vor die falschen Versionen liefert?

**Comment by Foxi352** [comment]
Scheint so. Im debug Modus habe ich immer noch die gleichen falschen Werte.

**Comment by Foxi352** [comment]
Hab's gefunden :-)
Es gab ein Verzeichnis `/home/smarthome/.local/lib/python3.5/site-packages/`. Hab's mit einem `locate CherryPy-11`gefunden. Wie es aussieht waren alte Versionen von den Packages die falsch angezeigt wurden in diesem Verzeichnis. Ein `rm -rf /home/smarthome/.local/lib/python3.5` hat das Problem gelöst.

Das erklärt warum der Code im Backend was anderes angezeigt hat als wenn ich es interaktiv selbst ausführe. Ich war `root`, und shng läuft als Benutzer `smarthome`.

Wo das `/home/smarthome/.local/lib/python3.5` herkommt ist mir allerdings ein Rätsel.

**Comment by msinn** [comment]
Hast Du evtl. Die Python 3.5 Version auf dem System gebaut? Das System ist nach Deinen Beschreibungen ja initial mit Python 3.4 installiert worden. (Sonst hättest Du kein Python 3.4) 

Wenn Du als User smarthome gebaut hast, könnte das das Verzeichnis erklären.

**Comment by Foxi352** [comment]
Kann mich nicht erinnern, will das aber auch nicht ausschliessen. Hab jedenfalls keine Source codes im /home/smarthome gefunden, und die aktuelle Python 3.5 kommt aus dem original repo. Könnte aber sein, dass es am Anfang noch nicht verfügbar war und ich manuell gebaut hatte, und später durch die offizielle Version ersetzt hatte.

Auf jeden fall ist es kein SHNG Problem, und sollte es nochmal bei jemandem auftauchen wissen wir wo man auch noch suchen kann :-)

Schliesse das Issue hiermit und Danke an alle für die Hilfe !
