### ISSUE TITLE
Issues with missing locale on system

### ISSUE THREAD

**Issue by sebastianfaulhaber** [smarthomeNG/smarthome#265]
I currently experiment with SmartHomeNG within Docker containers and realised that the system locale seems to be rather relevant. Without setting the locale the log showed

```
2018-07-14  15:44:06 WARNING  __main__          --------------------   Init SmartHomeNG 1.5.0594062.HEAD   --------------------
2018-07-14  15:44:06 ERROR    __main__          Locale for the enviroment is not set. Defaulting to en_US.UTF-8
2018-07-14  15:44:06 ERROR    lib.shyaml        YAML-file load error in /usr/local/smarthome/modules/http/module.yaml:  
'ascii' codec can't decode byte 0xc3 in position 308: ordinal not in range(128)
2018-07-14  15:44:06 ERROR    lib.module        Module http exception: invalid syntax (<string>, line 1)
```

The configuration files did not work with that locale.

The following workaround did the trick for me:
`export LANG=de_DE.UTF-8`

Regards,
Sebastian

**Comment by msinn** [comment]
Yes, you are right. But what is the issue?

**Comment by msinn** [comment]
Is the message

```
2018-07-14  15:44:06 ERROR    __main__          Locale for the enviroment is not set. Defaulting to en_US.UTF-8
```

not clear enough?

You are right about a corresponding note in the documentation. That has been forgotten at the end of the discussion in the forum. It has mainly been forgotten, because almost no one need to set it, if he follows the complete installation instruction. In that case the Linux environment is set.

I can't say anything about docker, since I don't use it. The description has been done by henfri.

**Comment by sebastianfaulhaber** [comment]
After thinking again about the expected behaviour, I'd rather prefer the application falling back to "de_DE.UTF-8" as the default (since the app won't work with the current default "en_US.UTF-8").

Happy to create a fix for that...what do you think?

Cheers,
Sebastian

**Comment by Foxi352** [comment]
Not every SHNG user lives in DE. What is wrong with the current default ?
For example on my Debian the LANG is set to en_IE.UTF-8, and SHNG works flawlessly and as expected. On my MAC the language is not set and it defaults to en_US.UTF-8. Still SHNG works as expected.

My guess is more that your .yaml file has not been correctly saved as UTF-8 file ?
Could that be possible ?

Test for example with `file -bi modules/http/module.yaml`

Output should be: `text/plain; charset=utf-8`

**Comment by sebastianfaulhaber** [comment]
So I've tried the following on my Mac, my CentOS Docker Host and from within my Debian based container:
```
git clone git://github.com/smarthomeNG/smarthome.git --single-branch --branch v1.5 .
file -bi modules/http/module.yaml
```
The output was `text/plain; charset=utf-8` in each case. So...this shouldn't be the problem. 

However, since I am the only one having this problem let's close this issue for now.

Thanks a lot for your help!
Sebastian
