### ISSUE TITLE
Language Server Protocol

### ISSUE THREAD

**Issue by henfri** [smarthomeNG/smarthome#266]
ich habe noch einen Wunsch.
Die Nachbarn von Openhab haben LSP integriert:
http://www.kaikreuzer.de/2017/12/18/openhab22/

Ich weiß nicht, wieviel Aufwand das für SH.py und die SmartVisu wäre. Aber ich denke, das würde die Arbeit an beiden sehr vereinfachen indem es Syntaxfehler verhindert.

Was meint ihr?

**Comment by psilo909** [comment]
Verstehe ich den Request so, dass Du gerne für einen Codeeditor einen Check hättest, der beim Erstellen der Yaml Dateien prüft, welche Attribute usw zulässig sind? Ist es dann nicht sinniger Items direkt via Backend hinzuzufügen?

Ich befürchte zudem dass der Wildwuchs bei den Plugins hier auch ein großer Blocker sein könnte. Leider ist die Schar der Plugin Maintainer recht überschaubar :-/ gleiches Thema wie bei dem "Lock" Item falls eine URL nicht erreichbar ist.

Vielleicht müssen wir mit 2.0 einen großen Cut ziehen, aber 50% der Plugins rauszukicken dürfte dem Ziel auch nicht so recht dienlich sein.

**Comment by henfri** [comment]
Hallo,

>Verstehe ich den Request so, dass Du gerne für einen Codeeditor einen Check hättest, der beim Erstellen der Yaml Dateien prüft, welche Attribute usw zulässig sind?

Nein. Es geht mir nicht nur um die Items.

>Ist es dann nicht sinniger Items direkt via Backend hinzuzufügen?

Das wäre sicherlich sehr komfortabel um einzelne Items hinzuzufügen. Für viele (ähnliche) Items ist ein Editor deutlich schneller. 

Ich habe mir das bei Edomi und Openhab mal angeschaut. Es ist für den Anfänger sicher toll, dass alles per GUI geht. Aber man braucht robuste Sehnenscheiden und viel Geduld. Aber gerade um den Einstieg zu schaffen wäre es super, wenn man alles, was nötig ist um ein Licht zu schalten per GUI machen kann.

Das ist aber nicht mein Anliegen hier.

90% meiner Fehler sind blöde Syntaxfehler. Und selbst ohne Fehler brauche ich viel Zeit um die richtigen Items rauszusuchen.
Vom LSP verspreche ich mir, dass ich beim schreiben einer Logik das Item aus dem Baum links wählen kann. Auch templates (in der von mir verlinkten Demo für die Visu; bei uns vielleicht z.B. ein RTR-Block für die Items) oder sogar, wenn die Smartvisu mitmacht Blöcke für die Visu wären möglich.

Gruß,
Hendrik

**Comment by henfri** [comment]
> Vielleicht müssen wir mit 2.0 einen großen Cut ziehen, aber 50% der Plugins rauszukicken dürfte dem Ziel auch nicht so recht dienlich sein.

Nee, das würde mir nicht gefallen ;-)
Aber ist es denn ein großes Problem, abwärtskompatibel zu bleiben?

Gruß,
Hendrik

**Comment by psilo909** [comment]
so ein syntaxchecker macht imho nur sinn, wenn er komplett checkt. ansonsten ists wieder nur ne halbgare lösung.. 

zudem wäre das zielbild ja sowieso, items via backend hinzuzufügen - und da kann man dann ja prüfen... die die es weiter mit codeeditor machen, sollten auch wissen was sie tun ohne einen syntaxchecker ;)

soweit ich das oben sehe, hängt sich openhab auch nur auf der visual studio editor ein, oder? wir bräuchten ja was vergleichbares in nem vernuenftigen python editor, bspw pycharm

**Comment by henfri** [comment]
Hallo,

sorry, aber in reiner Syntaxchecker ist etwas ganz anderes. Hast du dir das Video hinter meinem Link angesehen?
Man hat im Editor direkten Zugang zur den Objekten (Items, aber auch Funktionen).
Ein Syntaxchecker zeigt nur die Fehler. Mit LSP kann ich die Items aus der Liste wählen und habe eine Autovervollständigung.

> zudem wäre das zielbild ja sowieso, items via backend hinzuzufügen - und da kann man dann ja prüfen... die die es weiter mit codeeditor machen, sollten auch wissen was sie tun ohne einen syntaxchecker ;)

Das sehe ich anders. Die Möglichkeit über das Backend Items hinzuzufügen ist gut. Aber ich rede ja hier nicht nur über Items sondern v.a. über das Schreiben von Logiken.

> soweit ich das oben sehe, hängt sich openhab auch nur auf der visual studio editor ein, oder? wir bräuchten ja was vergleichbares in nem vernuenftigen python editor, bspw pycharm

der VSCode editor ist open-source und das ganze geht auch für Python.

Gruß,
Hendrik

**Comment by msinn** [comment]
Geht das jetzt um Python Syntax oder yaml Syntax (jeweils mit shNG Spezialitäten)?

**Comment by henfri** [comment]
Hallo,

um Beides.
Wenn ich ein eval in einem Item schreibe, wünsche ich mir Unterstützung
Wenn ich eine Logik schreibe, wünsche ich mir Unterstützung.

Ein Baum, aus dem ich Items wählen kann wäre da super.

Gruß,
Hendrik

**Comment by msinn** [comment]
> Ein Baum, aus dem ich Items wählen kann wäre da super.

Was fehlt Dir denn dabei im Logik Editor? Hast Du mal versucht ein Item einzutippen? Sobald Du sh. getippt hast, setzt die Autovervollständigung ein und liefert Dir die Liste aller Items.

**Comment by msinn** [comment]
Dis Anzahl Editoren die LSP unterstützen ist bisher ziemlich überschaubar (je nach Zählweise 11 bis 13 Editoren). Ich sehe im Moment nicht, dass der Aufwand der Implementierung von LSP in einem vernünftigen Verhältnis zum allgemeinen Nutzen steht.

**Comment by bmxp** [comment]
Also Hendrik ich freue mich, wenn Du das implementierst und bereitstellst aber ich sehe derzeit nicht die Manpower das zu machen. Da gibt es Wichtigeres. Insofern mache ich den Issue hier erstmal zu.
