### ISSUE TITLE
Parameter Überprüfung in Plugins vereinheitlichen 

### ISSUE THREAD

**Issue by cstrassburg** [smarthomeNG/smarthome#27]
Plugins werden in der Plugin-Konfiguration konfiguriert, die diverse Einstellungen fuer ein Plugin enthalten kann. Diese Einstellungen werden dem Konstruktor des Plugins uebergeben, werden wobei das Mapping zwischen der Einstellung und des Konstruktor-Parameters ueber den Namen gemacht wird: enthaelt die Konfiguration den Wert `host` so muss der Konstruktor auch einen Parameter `host` besitzen. D.h. alle moeglichen Parameter muessen als Konstruktor-Parameter angeben werden, damit sie verwendet werden koennen. Weiterhin muss das Plugin sich auch um die Typenbehandlung kuemmern (z.B. `int(param)` oder `bool(param)`).

Ziel soll es sein, ein einfaches generisches Interface fuer Plugin-Einstellungen zu schaffen, die verschiedene Arbeiten abnehmen kann.

Folgende Punkte koennten interessant sein:
- [x] fehlerhafte Parameter werden ignoriert und fuehren nicht direkt zu einem Fehler (siehe #55)
- [x] es soll eine Parameter-Konfiguration im Plugin hinterlegt werden koennen, die die moeglichen Parameter definiert
- [x] die Typenbehandlung (Umwandlungen von z.B. `str` in `int`) soll automatisch passieren
- [x] evtl. kann eine Parameter-Konfiguration auch dazu genutzt werden um diese in die Dokumentation (automatisch) einfliessen zu lassen
- [x] verschiedene Typen koennten direkt unterstuetzt werden (z. B. den Typ "password", welches sich auch um die Hashes kuemmern koennte - siehe dazu die Dikussion aus #101)
- [x] die Dokumentation der Plugin-Parameter in der Doku koennte standardisiert und automatisiert generiert werden
- [ ] ...

**Comment by msinn** [comment]
Ich habe eine generische Methode zur Überprüfung von Parametern der Modul-Parameter implementiert. Die konfigurierten Werte werden gegen Metadaten geprüft. Wenn die Art der Überprüfung für diejenigen, die auf dem Thema rumdenken in Ordnung ist, würde ich das auch auf die Plugin-Parameter übertragen.

Die im folgenden beschriebene Implementierung für die Module (am Beispiel des http-Moduls) kann man sich analog für die Plugins denken:

- Im Verzeichnis des Moduls (`/modules/http`) liegt eine Datei mit der Beschreibung der Metadaten für das Modul (`module.yaml`)
- In dieser Metadaten Datei gibt es einen Abschnitt `parameters:` in dem jeder Parameter definiert ist (mit Datentyp, Default Value, evtl. Werteliste)
- Folgende Datentypen werden für die Überprüfung unterstützt: 'bool', 'int', 'pint', 'float', 'pfloat', 'str', 'list', 'dict', 'ip', 'mac', 'foo', wobei `pint` eine positive Integer Zahl und `pfloat` eine positive Float interpretiert. `ip` und `mac`spezifizieren Strings, die die Formatforgabe '0.0.0.0' bzw. 'aa:bb:cc:dd:ee:ff' erfüllen.
- Die in /etc/module.yaml angegebenen Werte werden geprüft und in der geprüften (evtl. durch Default Value ersetzten) Version wie bisher als Strings an das Modul übergeben.
- Wenn ein ungültiger Wert angegeben wird und in den Metadaten kein Default Value spezifiziert wurde, wird der evault Value für den jeweiligen Datentyp verwendet.
- Zusätzlich wird in der Modul-Instanz ein Dict initialisiert, dass den Namen `_parameters` trägt. In diesem Dict werden die Parameter mit ihren konfigurierten Werten im jeweiligen Datentyp (also nicht alle als String) abgelegt. Module können also wählen, ob sie die alte Form der Parameterübergabe wählen (also in `def __init__( ... )` spezifiziert oder ob sie auf das Dict zugreifen, in dem die Werte bereits im richtigen Typ vorliegen.
- Falls keine Metadaten vorliegen (keine `module.yaml` oder in der Datei `module.yaml` kein Abschnitt `parameter:`, verhält sich der Loader wie in den älteren Versionen von SmartHomeNG.

Wenn man in der obigen Beschreibung `Modul` durch `Plugin` ersetzt, erhält man die Beschreibung, die ich für die Plugins implementieren möchte.

**Comment by ohinckel** [comment]
Hoert sich schinmal ziemlich danach an, sodass man das auch fuer Plugin-Parameter verwenden koennte.

Das mit den Typen koennte man evtl. auch in einer allgemeinen Konfiguration unterbringen. Dort ist dann z.B. der Name des Typs (int, str, float, mac,...) definiert mit den jeweiligen Defauls, Einschraenkungen, ... Damit koennte man in Zukunft auch weitere Typen unterstuetzen.

Das mit den `pint` koennte man dann in einer solchen Konfiguration aufnehmen und z.B. einen min/max-Constraint setzen (oder via regex-Cinstraint im Fall des Mac/IP-Parameters). Die hart implementierten Typen finde ich nicht so praktisch, da es auch unterschiedliche Implementierungen geben koennte was erlaubt ist und was nicht. Haette man fuer die Typen ein einheitliches Interface, koennte man aucn diese allgemeinen Typen in der Doku auffuehren und in den Plugins dann nur referenzieren, anstatt in jedem Plugin erklaeren zu muessen, wie ein IP-Parameter auszusehen hat.

Was mich aber noch am meisten stoert, waere die doppelte Implementierung. Module und Plugins scheinen ziemlich aehnlich konfiguriert zu werden. Das wuerde ich vereinheitlichen. Ich haette auch das eigentliche Laden/konfigurieren der Module/Plugins vom Starten getrennt - aber vieleicht ist das ja schon so. Dann koennte man alles erstmal laden/konfigurieren und anschliessend die Module und Plugins starten.

**Comment by msinn** [comment]
> Das mit den Typen koennte man evtl. auch in einer allgemeinen Konfiguration unterbringen. Dort ist dann z.B. der Name des Typs (int, str, float, mac,...) definiert mit den jeweiligen Defauls, Einschraenkungen, ... Damit koennte man in Zukunft auch weitere Typen unterstuetzen.

So hatte ich das gedacht.

> und z.B. einen min/max-Constraint setzen

Daran hatte ich auch schon gedacht. Ich hatte nur (weil schnell und einfach) erstmal pint, pfloat und value-lists implementiert.

> Was mich aber noch am meisten stoert, waere die doppelte Implementierung. Module und Plugins scheinen ziemlich aehnlich konfiguriert zu werden.

Das würde ich in ein eigenes lib-Modul rausziehen. Wenn das Module Interface reift, ergibt sich in der Zukunft vielleicht auch die Möglichkeit Module und Plugins zu vereinheitlichen. Ich wollte nur im entstehen des Modul Interfaces (mal Schauen, ob weitere Module vielleicht weitere Anforderungen haben) nicht gleich das große Rad drehen, das mit dem Plugin Interface zu verheiraten.

Das Laden der Module ist vom Starten getrennt. Erst werden alle Module geladen, dann gestartet. Sie werden aber gestartet bevor die Plugins geladen werden, damit die Plugins eine lauffähige Umgebung vorfinden.

**Comment by msinn** [comment]
Die Metadaten unterstützen für die Plugin Parameter jetzt auch typisierte Listen.

Bisher konnte man als Datentyp **list** angeben. Beim Einlesen der Parameter konnte die Gültigkeit der konfigurierten Werte in der Liste jedoch nicht geprüft werden.

Nun kann man ausser **list** als Typ auch **list(<datatype)** angeben, wenn alle Werte, die man in der Liste konfigurieren darf denselben Datentyp haben. Dann wird die Gültigkeit der konfigurierten Werte geprüft.

Beispiele:

- type: **list**    - Die Liste darf beliebige Werte enthalten
- type: **list(int)**    - Die Liste darf nur Integer Werte enthalten
- type: **list(ipv4)**    - Die Liste darf nur IP Adressen enthalten

**Comment by msinn** [comment]
Allmost all original ideas havebeen implemented for plugin parameters in v1.4
