### ISSUE TITLE
Cache doesn't get updated by plugin on DICT items

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#274]
This is easy to replicate. Just add a code like this at the beginning of a plugin, e.g. uzsu parse_item method:
self._items[item]['bla'] = True
item(self._items[item])

The value will get written in the item but it doesn't stay there. Means as soon as you remove the lines above and restart smarthome, the entry "bla" disappears. Backend also does not update the info about "last update" or "last change"

**Comment by msinn** [comment]
Does it work for lists?

Updating lists and dicts through the backend works ok (updating change time and changer). So maybe it has something to do with Python not copying complex data but working with a reference instead.

Could you do the test again and not assign the dict but make a copy of the dict and assign the copy?

**Comment by msinn** [comment]
Wie gesagt, die Cache Funktionalität an sich ist in Ordnung.

Wenn Du ein Item vom Typ dict (mit cache: True) anlegst, ins Backend geht (da ist der Wert natürlich leer) und dort z.B.  **{'k1': 'v1', 'k2': 'v3'}** eintippst und das Feld verlässt, änderst Du den Wert.

Wenn Du jetzt shNG neu startest und im Backend nachschaust, wirst Du sehen, dass der eingetippte Wert wiederhergestellt ist.

**Comment by onkelandy** [comment]
Ja, die ist in Ordnung. Aber sobald ich über ein Plugin rein schreib, ist es vorbei. Rechte scheinen prinzipiell zu passen. Cache-File hat RW für alle und auch unter root macht's die gleichen Probleme.

Szenario nochmals..:
- Start normal, manuelles Ändern in Backend -> wird eingetragen und gespeichert. 
Nach Neustart ist alles da und kann normal beschrieben werden.

- Start mit obigem Plugin-Code in der run Methode eines beliebigen Plugins: manuelles Ändern in Backend NICHT möglich. Nach Neustart auch nichts im Cache

**Comment by msinn** [comment]
Worauf ich hinaus will: Sowohl Dein Szenario als auch das Backend nutzen die Funktionalität **Item(neuer_wert** zum setzen des Wertes, nur mit unterschiedlichen Resultaten.

Da in Deinem Szenario update time, etc nicht gesetzt werden, vermute ich (wie schon weiter oben geschrieben) die Python interne Speicherverwaltung als Ursache:

Wenn ein Dict einem anderen zugewiesen wird, setzt Python nur einen Zeiger auf das ursprüngliche Dict. Wenn Du nun das Dict änderst, ändert sich der Zeiger nicht und deshalb werden die ganzen Update Aktionen nicht ausgeführt.

**Comment by onkelandy** [comment]
Perfetto. Die Lösung ist denkbar einfach. Im Plugin muss einfach zuerst ein leeres dict ins Item geschrieben werden und danach das, was vorher ausgelesen wurde und mit einem weiteren Key erweitert wurde. Yikes...

In dem Fall ist das kein Issue mehr.. aber vielleicht kann man das irgendwo im Entwicklerhandbuch für Pluginentwicklung als Hinweis festhalten?

dictionary=self._sh.test_dict()
dictionary.update({1:'test'})
self._sh.test_dict({})
self._sh.test_dict(dictionary)

**Comment by ohinckel** [comment]
> dictionary=self._sh.test_dict()

Vielleicht koennte das immer eine "deep copy" der Daten zurueck liefern? Geht etwas auf die Performance, macht es aber intuitiver. Ausserdem kann man so auch nicht mehr "interne Strukturen" des Items aendern in dem man in das dict schreibt ohne es wieder zu setzen.

**Comment by msinn** [comment]
@onkelandy Die von Dir geschilderte Lösung ist nicht wirklich schön. Sie würde auch 2 mal triggern, wenn andere Items oder Logiken von diesem Item abhängen. Der Vorschlag von @ohinckel liefert da ein deutlich besseres Ergebnis. Du kannst folgendes machen:

```
import copy

dictionary=copy.deepcopy(self._sh.test_dict())
dictionary.update({1:'test'})
self._sh.test_dict(dictionary)
```

Ich schaue mir die Tage mal an, wie ich das am besten für dicts und lists direkt in lib.item implementiere.

**Comment by msinn** [comment]
@ohinckel Die Methode, die Itemwerte in lib.item zurück liefert ist folgende:

```
    def __getitem__(self, item):
        return vars(self)[item]
```

Würdest Du für alle Werte ein deepcopy machen, also so:

```
    def __getitem__(self, item):
        return copy.deepcopy(vars(self)[item])
```

oder nur für dicts und listen?

**Comment by ohinckel** [comment]
Ich wuerde einfach immer ein `copy.deepcopy()` machen: es wird bereits geprueft ob es sich um primitive Typen handelt oder nicht. Dabei werden dann auch z.B. tuples beruecksichtigt (haben wir zwar nicht, aber warum spezielle Checks nochmal an in der `__getitem_()` Methode einbauen).

Die Aenderung koennte dann ggf. den Speicherbedarf erhoehen. Vielleicht sollte man daher mal einen Vergleich machen ob sich das zu stark negativ auswirkt.

**Comment by onkelandy** [comment]
Das deepcopy funktioniert wunderbar und ist sicher die beste Lösung, wenn sie direkt ins getitem rein kommt. Übers Backend kann man nämlich definitiv keine Änderungen an einem dict vornehmen, wenn schon was im cache angelegt ist.

**Comment by msinn** [comment]
@ohinckel 
> Die Aenderung koennte dann ggf. den Speicherbedarf erhoehen. Vielleicht sollte man daher mal einen Vergleich machen ob sich das zu stark negativ auswirkt.

Das sollte aber nur den Speicherbedarf erhöhen, wenn jemand Items vom Typ dict oder list hat. Damit sollte der Großteil der Anwender davon nichts merken.

**Comment by msinn** [comment]
@onkelandy 
> Übers Backend kann man nämlich definitiv keine Änderungen an einem dict vornehmen, wenn schon was im cache angelegt ist.

Das kann ich nicht nachvollziehen. Bei mir funktioniert folgendes problemfrei:

- Item mit ```type: dict```und ```cache: True``` definiert
- Über das Backend ein Wert eingegeben (```{'k1': 'v1', 'k2': 'v1'}```)
- shNG neu gestartet
- Im Backend das item aufgerufen. Der Wert  (```{'k1': 'v1', 'k2': 'v1'}```) ist da
- Im Backend das Item geändert (```{'k1': 'v1', 'k2': 'v2'}```)
- shNG neu gestartet
- Im Backend das item aufgerufen. Der Wert  (```{'k1': 'v1', 'k2': 'v2'}```) ist da

Was geht bei Dir denn nicht?

**Comment by onkelandy** [comment]
Hab nochmals ausführlich getestet. Das Problem im Backend besteht tatsächlich immer dann, wenn man als KEY vom dict eine Zahl eingibt oder im dict bereits eine Zahl als key definiert ist.

Wenn das dict also zu Beginn leer ist und ich gebe {1: 'bla'} ein, springt's zurück. Wenn ich das dict mittels Logik update, wird der Eintrag brav erstellt, aber man kann das dict im Backend nicht mehr aktualisieren. Und zwar ist es egal, was man versucht zu ändern, es springt immer auf den vorigen Zustand. Liegt wohl daran: https://stackoverflow.com/questions/32544835/python-create-dictionary-using-dict-with-integer-keys

Klar könnte man die Zahl als str definieren, aber Stolperfalle ist es schon.

**Comment by msinn** [comment]
Die Ändrung mit dem deepcopy füge ich sowieso im item ein. Es ging mir nur darum den Fehler den Du siehst zu verstehen.

Ich hatte Dich so verstanden, dass Du außerhalb vom Backend mit deepcopy das Problem. Icht hast, oder?

**Comment by onkelandy** [comment]
Deepcopy löst das Cache-Problem für dicts definitiv. 

Dicts mit Integer-Keys funktionieren generell, lassen sich aber nicht im Backend anpassen oder erstellen.

**Comment by msinn** [comment]
@onkelandy Ich habe im develop die Änderung in lib.item eingebaut. Schau mal ob jetzt für Dich alles ok ist.

**Comment by onkelandy** [comment]
Leider kein Erfolg. Hab's nochmals direkt in der Logik/im Plugin probiert:
copy.deepcopy(self._sh.test_dict())
funktioniert. Nur mit dem neuen item.py im lib aber funzt es nicht.

Dem Problem beim Update aus dem Backend bin ich inzwischen auf die Schliche gekommen: json.loads verträgt keine int als dict keys :( So richtig guten Workaround hab ich trotz längerer Suche leider nicht gefunden.. 
https://stackoverflow.com/questions/17099556/why-do-int-keys-of-a-python-dict-turn-into-strings-when-using-json-dumps

**Comment by msinn** [comment]
Ich hatte die falsche Stelle identifiziert um das deepcopy() einzubauen. Nun ist es dort, wo wirklich der Item Wert zurückgegeben wird.

Zu dien Dicts mit Integer-keys habe ich auch keine gute Idee, ausser sie zu vermeiden. Da das json Format das nicht unterstützt, werden wir in der Umwandlung in Richtung der Web Oberfläche (Javascript) dort immer einige Probleme haben.

**Comment by onkelandy** [comment]
Works! Prima.

Was die int keys anlangt... Ich weiß nicht, was json.loads noch so alles macht, aber womöglich wäre für dicts-Konvertierung yaml eine Alternative!?
Das hier würde funktionieren:
import ruamel.yaml as yaml
import re

value = yaml.load(re.sub(":\s*None", "", re.sub(":\s*", ": ", value), flags=re.I), Loader=yaml.Loader)

Hab mal dieses Dict übers Backend angelegt und keine Beschwerden erhalten. Anzahl Leerzeichen vor oder nach dem : wird über re.sub abgefangen. true/false funzt, none nur mit obigem re.sub.
{4   :    5, 44: 'rrr', '333': True, '4387': 'test', '222: true': 'None', '1132': 'test', '4954': 'test', 444: False, '%&_': 'ÜÖ', '9692': 'test', 'xyz':none, 'leer:}

Wenn das zu "unsicher/suspekt" ist, könnte man die Lösung vielleicht als weiteres try/except einbinden? Dann funzt alles wie gehabt, nur int dicts werden über yaml formatiert und haben zumindest eine Chance auf Überleben..?

**Comment by msinn** [comment]
YAML ist ein superset von json und beherrt dicts vollständig. Nur wenn solche Items in Frontends bearbeitet werden sollen die Javascript nutzen, ist json das Transportformat für die Daten.

**Comment by onkelandy** [comment]
Du meinst ein weiteres try/except beim Lesen aus'm Backend wär nix? Dann können wir den Issue hier schließen. Wäre super, wenn's bald einen 1.5.2 Release gäbe. Sind inzwischen doch einige essentielle Updates eingeflossen.

**Comment by msinn** [comment]
Ich noch verstehe nicht, was Du mit einem try/except "retten" willst.

- Wenn Du ein dict mit einem Integer Key anlegst, wird das im Backend (Browser) richtig angezeigt.
- Wenn Du dieses dict im Backend (Browser) bearbeiten willst, funktioniert das nicht, weil der Browser das dict, wenn es kein gültiges json ist beim zurücksenden, als String statt als dict interpretiert. Das führt zur Fehlermeldung im Log, die bei der versuchten Zuweisung eines falschen Typs aus lib.item kommt.

**Comment by onkelandy** [comment]
Und mit obiger Funktion würde das Ändern eines dict mit int keys im Backend funktionieren. Der String wird in ein dict umgewandelt, auch wenn es int keys gibt.

**Comment by msinn** [comment]
Das ist aber kein Problem des Backends, sondern kann überall auftreten wo json im Spiel is, z.B. auch in der Kommunikation zur smartVISU.

**Comment by msinn** [comment]
> Wäre super, wenn's bald einen 1.5.2 Release gäbe. Sind inzwischen doch einige essentielle Updates eingeflossen.

Das dict Verhalten ist die Veränderung/Verbesserung eines Verhaltens, das es bereits seit Anbeginn von smarthome.py gibt. Insofern sehe ich nicht, dafür ein Bugfix Release 1.5.2 zu machen. Die Änderung würde normal in die v1.6 einfließen.

**Comment by onkelandy** [comment]
scheduler_change und _trigger aus dem smartplugin funktioniert erst seit dem update: https://github.com/smarthomeNG/smarthome/commit/ad4696796b0366b32b8687e1a27026c6829ec0b6

Es geht mit sh.scheduler.change, aber nicht mit der im Beispielplugin angegebenen smartplugin Methode.

**Comment by msinn** [comment]
Das hat mit diesem Issue jetzt aber nichts zu tun, oder?

Wenn scheduler_change und _trigger aus dem smartplugin bisher nicht gingen, kann sie bisher auch keiner genutzt haben. Also hat das letzte Release keine bestehende Funktionalität gebrochen. Das brechen einer bestehenden Funktionalität ist bisher der Anhaltspunkt dafür gewesen ein Bugfix Release herauszugeben.

Wenn wir für jeden Bug den wir finden, ein Release machen würden, hätten wir bald daily Releases 😉 

Zurück zum dict Verhalten: Ich bin mal in die lib.item tief-getaucht und glaube eine Stelle gefunden zu haben, wo man das Verhalten ändern könnte (ohne Nutzung von YAML, sondern mit Hilfe von ```literal_eval```).

**Comment by onkelandy** [comment]
Fix Release: Ich denk halt nur, dass eine Funktion, die im Beispielplugin propagiert wird, auch funktionieren sollte. Dass sie bis dato niemand außer mir eingesetzt hat, ist ne andere Sache. Zeile 89 hier https://github.com/smarthomeNG/smarthome/blob/master/dev/sample_plugin_1_5/__init__.py funktioniert, aber das in logischer Konsequenz anzuwendende scheduler_change nicht. Aber das hat jetzt tatsächlich nix mit dem Issue hier zu tun und ist natürlich eure Entscheidung.

Zum dict Verhalten: Das ast.literal_eval hatte ich auch schon getestet. In irgendeinem Sonderfall gab es ein Problem, find's aber leider nicht mehr. Ist sicher einen Versuch wert! Und sollte es doch Sonderfall-Probleme geben, kann man's bestimmt abfangen. Evtl. klassische Fehler wie klein geschriebene false/none noch umwandeln..?

**Comment by msinn** [comment]
Aus dem Backend wird das dict als ein String übergeben. Die Umwandlung in ein dict findet erst in lib.item statt. Die eigentliche Ursache liegt hier:

```
def _cast_dict(value):
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except Exception as e:
            value = value.replace("'",'"')
            value = json.loads(value)
    if isinstance(value, dict):
        return value
    else:
        raise ValueError
```

Hierbei werden noch die einfachen Anführungszeichen ersetzt (die in json unzulässig sind) bevor der String in ein dict gewandelt wird. Für Keys die kein String sind, werde ich hier die Behandlung einbauen.

**Comment by msinn** [comment]
Just pushed a new version of lib.item

**Comment by onkelandy** [comment]
works. can be closed I guess
