### ISSUE TITLE
Database plugin does not properly start if http module isn't enabled

### ISSUE THREAD

**Issue by smaiLee** [smarthomeNG/smarthome#277]
IMHO the database plugin should work w/o http module as the webif is just an additional feature.
Likely cause seems to be this code at end of `__init__`:
```python
        if not self.init_webinterface():
            self._init_complete = False
```
https://github.com/smarthomeNG/plugins/blob/9d947548a5aabfa449d5ea12f955d6b7a8cfc4e6/database/__init__.py#L99-L100

Because of _init_complete the items do not get parsed.

Worst thing about this: The DB connection and the scheduler entry are added before, so they are already working despite the plugin is not usable.

**Comment by ohinckel** [comment]
I can't tell very much about the web-interface implementation, but I think the plugin should not depend on a working web-interface. Don't know if this is a general problem or only in the database plugin.

Maybe @psilo909 or @msinn can tell more about the implementation and how to deal with "broken" web-interfaces of plugins.

**Comment by msinn** [comment]
Plugins should work without http and webinterface. Tge if statement above makes only sense for plugins that won‘t do anything without web interface, like the backend plugin.

**Comment by msinn** [comment]
The sample interface should contain the right code to deal with this situation. I did not write the web interface for the database plugin but probably it can be fixed by calling **self.init_webinterface()** without the if ... then

**Comment by msinn** [comment]
@smaiLee I corrected the initialization of the database plugin. Should be ok now.

**Comment by smaiLee** [comment]
:+1: checked
