### ISSUE TITLE
"setValue" key in scenes/*.yaml

### ISSUE THREAD

**Issue by kr2** [smarthomeNG/smarthome#283]
my problem: i would like to fade to learned values on some items in a scene
maybe there is a simple solution i don't see?
my suggestion to solve that would be a "setValue" key something like that:
```yaml
[...]
- {item: ..., setValue:"lambda item, newVal: item(newVal)", value: 100, learn: true}  # default no fade
- {item: ..., setValue:"lambda item, newVal: item.fade(newVal, 5, 0.1)", value: 100, learn: true}  # fade
- {item: ..., setValue:"lambda item, newVal: item.timer(600, 0)", value: 100, learn: true}  # ...
[...]
```

**Comment by msinn** [comment]
At the moment you can use 'learn' **or** you can eval expressions but not both at the same time. 

At the moment there are no additions planned for the scene functionality.

**Comment by msinn** [comment]
For version 1.9 I will look into a fade function for scenes that can fade to a (learned) value and would have parameters to control the fading.

**Comment by msinn** [comment]
SmartHomeNG v1.9 implements userfunction, which can be used in eval expressions.
Instead of implementing something like **setValue**, scenes can use eval expressions with userfunctions instead of using lambda functions as in the example in the request.

**Comment by msinn** [comment]
Since there is no further feedback, I close the issue. 
If the suggested solution is insufficient, please reopen.
