### ISSUE TITLE
logging.yaml: change file names/suffix for TimedRotatingFileHandler

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#287]
Would be perfect to integrate an option for the log naming when rotating the log. Something like this:
https://stackoverflow.com/questions/338450/timedrotatingfilehandler-changing-file-name

In my opinion it makes more sense to include a ".log" as a suffix to easily open it with corresponding tools (when accessing from Windows/Mac). Right now the suffix is the date added after the .log instead of before.

The log rotation feature from the python logging accepts a "prefix" and "suffix" but I have no clue how to correctly send it from the logging.yaml...

**Comment by msinn** [comment]
I don't like it myself. This is Python standard behavior for rotating FileHandlers. I have to do a deep dive into the Python logging documentation to see if/how it can be fixed. 

Probably, a fix (when found) has to be implemented by each user in his own logging.yaml.

**Comment by onkelandy** [comment]
Something like putting handler.suffix = "%Y-%m-%d.log" in the logging.yaml would be fine enough ;)

**Comment by msinn** [comment]
@onkelandy 
> The log rotation feature from the python logging accepts a "prefix" and "suffix"

Where did you find the documentation?

In the Python 3.7 documentation under **TimedRotatingFileHandler** The only time I found suffix is:

```On rotating it also sets the filename suffix.```

And then the documentation explains how to set the rotation point in time.

**Comment by msinn** [comment]
As I see it, it could only work, if we write a class with a special  handler that allows the desired naming and specify that class in the handler's section instead of ```logging.handlers.TimedRotatingFileHandler```

**Comment by msinn** [comment]
Since no one seems to be eager to write a replacement class for ``logging.handlers.TimedRotatingFileHandler``, I am closing this issue.

**Comment by freetomik** [comment]
If you can access your logger outside the `logging.yaml` somewhere in your code, you can change namer of the logger handler:
[Add File Extension in TimedRotatingFileHandler (StackOverflow)](https://stackoverflow.com/questions/61948867/add-file-extension-in-timedrotatingfilehandler).

Code which works for me:
```python
    for handler in logging.getLogger().handlers:
        if isinstance(handler, logging.handlers.TimedRotatingFileHandler):
            handler.namer = lambda name: name.replace(".log", "") + ".log"
```

**Comment by onkelandy** [comment]
Thanks but this issue actually got fixed a long time ago.

**Comment by freetomik** [comment]
Ok, I thought that it wasn't fixed, but just closed. Maybe it will help somebody who finds it here though.
