### ISSUE TITLE
Feature request: documentation and blogentry links in backend plugin

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#288]
For more complex plugins it might be necessary to include a separate documentation besides the README. It's easy to do that with the web interface but it would be more conclusive to have an additional button in the plugins overview of the backend plugin.

Additionally it would be perfect to directly link from that site to a blog entry on the smarthome webpage. Either by URL (direct links to the blog don't seem to work by the way?) or by using a tag (e.g. the plugin name). 

Both could be configured in the plugin.yaml as blogentry_tag and documentation_page or whatever.

To go even further it might make sense to provide an easy way to read the README and/or plugin.yaml information all from one place. What do you think?

Find an example screen shot with dummy icons and mouseover tooltips attached:
<img width="1658" alt="pluginpage_example" src="https://user-images.githubusercontent.com/7084934/46571476-ed09d000-c975-11e8-87bf-0415017b2b7d.png">

**Comment by msinn** [comment]
As a Standard the documentation should be integrated in the user documentation (or the developer documentation if appropriate).

e.g.: https://www.smarthomeng.de/user/plugins/avm/user_doc.html

This documentation is easy to create. It is contained in a file in the plugin directory and named **user_doc.rst**. For a page to be included in the developer documentation the file has to be named **developer_doc.rst**.

Instead of using restructured Text (rST), it is possible to use markdown. In that case, the file has to have the extension **.md** instead of **.rst**.

In the plugin list, cound be an icon added, if the user_doc.rst exists for that plugin and could link to the documentation page.

**Comment by onkelandy** [comment]
Thanks for the info on the documentation. Is it possible to structure the documentation with multiple files like mentioned here: https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#include-other-rst-files-with-the-toctree-directive

Would that work with the shng site? I've seen in the develop docu of the websocket plugin that it's possible to integrate a submenu in the sidebar. That might be an option though for the stateengine plugin it might become overwhelming if everything is in one single page.. not sure about that.

Yes, an icon linking to the corresponding shng page would be great. Still, also linking to relevant blog entries might be helpful, too. And maybe the support thread? documentation and support are already in the plugin.yaml of the avm plugin I've seen. Just need to be made accessible more easily ;)

**Comment by msinn** [comment]
I don't see any reason for it not to work. The documentation is built with sphinx.

If the subpages are only visible by clicking a link from the page above or are available in the toc depends on a setting for toctree which defines the maximum sublevel to be included in the toctree on the left side of the documentation.

A Link to the support thread is already in the backend plugin. Just click a row with a plugin and you see details for the plugin. There is a link to the support thread and (if it exists) a link to further documentation.

Links to Blog entries are a bit difficult. How many links to different blog articles do you want? You can use the documentation link to point to a blog post. Just enter it in the metadata (plugin.yaml in the plugin directory).

**Comment by onkelandy** [comment]
OIC.. That's nice though not very obvious to be honest with the click on the line (esp. when there is a lot of info like for the knx plugin). Anyhow, an icon showing there is more docu and/or support might make things easier. Like your suggestion above "In the plugin list, cound be an icon added, if the user_doc.rst exists for that plugin and could link to the documentation page."

As far as the blog is concerned, providing a tag could work as long as every plugin related blog entry  has a tag with the plugin name. Actually it wouldn't even be necessary to put the tag in the plugin.yaml, it could be done automatically based on the plugin name? The webservices plugin could then have an icon/entry in the backend linking to https://www.smarthomeng.de/tag/webservices as long as there is no 404 error?

**Comment by msinn** [comment]
Linking to /tag/... is a good idea, but it will never return an 404. If no blog exists, Wordpress will show a page (which just doesn‘t have info about that tag).

**Comment by onkelandy** [comment]
Too bad :( Maybe extracting the title of the site could work as at least that is "site not found"..?

**Comment by msinn** [comment]
Linking to the documentation is implemented in the admin interface. 

Linking to the Blog Tags: As it can't be determined if there are matching articles, the Link can not be en-/disabled accordingly. So we have to skip this feature for the moment.

**Comment by onkelandy** [comment]
Maybe manually provide the blog tags in the plugin.yaml like the link to the support thread?

**Comment by msinn** [comment]
Linking to blog articles from the admin interface is implemented in SmartHomeNG v1.7.

@onkelandy Can this issue be closed?

**Comment by onkelandy** [comment]
yes it can.
