### ISSUE TITLE
Change naming convention of log files

### ISSUE THREAD

**Issue by Tom-Bom-badil** [smarthomeNG/smarthome#289]
For the time being, log files are created as follows (list of my log dir as of 2018-10-07):

- smarthome.log                       # Today's log
- smarthome.log.2018-09-29
- smarthome.log.2018-09-30
- smarthome.log.2018-10-01
- ...
- smarthome.log.2018-10-06

As you can see, the daily logs are renamed to _'smarthome.log.yyyy-mm-dd'_. This is a bit inconvenient, as the file extension is different for each file, and double-clicking a file e.g. in Windows Explorer (I am accessing the logs through Samba) will bring up a 'File open' dialogue each and every single time - due to the unknown extension '.yyyy-mm-dd'.

A minor change would fix this: Instead of _'smarthome.log.yyyy-mm-dd'_ I would recommend to use _'smarthome.yyyy-mm-dd.log'_, so all log files have the same extension '.log'.

Thanks for considering, and thumbs up once more for all your work and efforts,
/tom

**Comment by onkelandy** [comment]
dude.. you are MUCH too late ;)
https://github.com/smarthomeNG/smarthome/issues/287

**Comment by Tom-Bom-badil** [comment]
Oops, my bad - closing this one, thanks! :)

**Comment by ohinckel** [comment]
That explains my "déjà vu" feeling.
