### ISSUE TITLE
Items are triggered ("eval") on Restart of sh.py

### ISSUE THREAD

**Issue by henfri** [smarthomeNG/smarthome#290]
Hello,

an eval of an item is triggered when restarting smarthome-ng.
See:
https://knx-user-forum.de/forum/supportforen/smarthome-py/1274096-item-wert%C3%A4nderungen-z%C3%A4hlen
and:
https://knx-user-forum.de/forum/supportforen/smarthome-py/1273010-verbrauch-gas-etc-ungewolltes-item-trigger-bei-neustart

Greetings,
Hendrik

**Comment by msinn** [comment]
@henfri It has been a *feature* since the beginning of smarthome.py. There is extra code to do it:
```
    def _init_run(self):
        """
        Run initial eval to set an initial value for the item

        Called from Items.load_itemdefinitions
        """
        if self._trigger:
            # Only if item has an eval_trigger
            if self._eval:
                # Only if item has an eval expression
                self._sh.trigger(name=self._path, obj=self.__run_eval, by='Init', value={'value': self._value, 'caller': 'Init'})

```

**Comment by msinn** [comment]
Das Verhalten, das es seit den initialen Versionen von smarthome.py gubt, ist in einigen Situationen zwar umschön, ohne ein grundlegendes Redesign eher nicht zu fixen.

Die beiden Threads auf die oben verwiesen wurde, beschreiben übrigens unterschiedliche Situationen. Das zweite Thema ist eher ein database/sqlite Theme und durch database: init statt database: True zu lösen.
