### ISSUE TITLE
Travis-CI failing at update_config_section only using python3.7

### ISSUE THREAD

**Issue by maddinador** [smarthomeNG/smarthome#294]
Every recent travis-ci job fails due to the test `test_06_update_and_read_section` in `tests/test_logics.py` **only using python3.7**.
The test tries to update a logics section.
The test object wants to do that by deleting the old values first, which (from my point of view _might_) not exist.
More in detail: `update_config_section()` in `lib/logic.py` tries to `del conf[section]['filename']`.
I've unsuccessfully tried to find the difference of the `del `statement between py3.6 and py3.7.
It seems like older python versions are more relaxed when a to-be-deleted key does not exist.

Anybody working on that already or having any hints about that?

Link to a failing job: [https://travis-ci.org/smarthomeNG/plugins/jobs/438825440](https://travis-ci.org/smarthomeNG/plugins/jobs/438825440)

**Comment by maddinador** [comment]
Well, a little update:
I've compared docs:
[https://docs.python.org/3.6/library/stdtypes.html#dict](https://docs.python.org/3.6/library/stdtypes.html#dict)
[https://docs.python.org/3.7/library/stdtypes.html#dict](https://docs.python.org/3.7/library/stdtypes.html#dict)
In both cases the doc says about `del d[key]:` "Raises a KeyError if key is not in the map."
And that's the exception we got.

Thus the cause must be somewhere else. Having a look at `update_config_section()` in `lib/logic.py`:
The lines before the `del` statement create an empty `conf` (if non-existent) and the to-be-deleted `section` (if non-existent) using `shyaml.get_emptynode()`.
If the to-be-updated `section` does not exist before, we are trying to delete non existing, are we?

**Comment by ohinckel** [comment]
The `ruamel.yaml` is different:
```
ruamel.yaml>=0.13.7,<=0.15;python_version<'3.7'
ruamel.yaml>0.15.0,<0.16.0;python_version>='3.7'
```

According to the logs in Python 3.7 version `0.15.72-cp37` is installed (see [logs](https://travis-ci.org/smarthomeNG/plugins/jobs/440051272)), in older Python versions version `r0.15.0-cp36` is installed (see [logs](https://travis-ci.org/smarthomeNG/plugins/jobs/440051271)).

Looking at the `ruamel.yaml` source this [commit](https://bitbucket.org/ruamel/yaml/commits/435feb498b1fb017aa0b5407c1ee35451d54c3dc) could be responsible for breaking the test (the `__delitem__()` method): removing a non-exsitent key will now result in a `KeyError` while previously it was ignored.

The `logic.py` is [removing "internal" keys](https://github.com/smarthomeNG/smarthome/blob/develop/lib/logic.py#L772) from the `dict` read from a logic YAML file (filename, cycle, crontab, watch_item). In some cases the `dict` is created by `shyaml.get_emptynode()` which [returns](https://github.com/smarthomeNG/smarthome/blob/develop/lib/shyaml.py#L329) a `yaml.comments.CommentedMap` object. This object does not have all these keys and will result in an exception.

@msinn, @bmxp do we need to check if key exists before we remove it? Are there other objects/settings which can be used which automatically ignores non-existent keys in ruamel?

**Comment by msinn** [comment]
I will have to look into it. The chance of breaking changes in ruamel.yaml was the reason to define a max. version in requirements,txt. But: With Python 3.7 the defined max. version did not work any more.

I started to use a newer version of ruamel.yaml (0.15.64) in my develop environment (without problems), but I am not using Python 3.7 yet.

**Comment by msinn** [comment]
I have modified lib.logic to avoid the breaking change in ruamel.yaml v0.15.70.

Travis is now again running successful for Python 3.7.

I modified the requirements for ruamel.yaml and set the max version to 0.15.74 to avoid potentially running into other breaking changes.
