### ISSUE TITLE
Make additional properties of item publicly accessible for stateengine plugin

### ISSUE THREAD

**Issue by i-am-offline** [smarthomeNG/smarthome#296]
The stateengine plugin needs to change some settings of stateengine-items. This is currently being done by changing private variables of the items.
In order to have a stable interface, this feature request asks for the implementation of publicly accessible methods to access these settings. The following variables need to be accessed by the stateengine plugin:

- _eval
- _trigger
- _enforce_updates

For these, both getters and setters would be needed.

If it helps, I can add the required coding and provide a PR

**Comment by msinn** [comment]
I have implemented the three properties.

They are documented in the developer documentation. An actual version of the developer develop documentation (for the develop branch) can be found under https://www.smarthomeng.de/dev/developer/ (mind the **dev** in the url) in the Items-API (https://www.smarthomeng.de/dev/developer/lib/item.html).

In contrast to the internal data, the properties have only one datatype. Instead of False the trigger property returns an empty string and vice versa.

Please give it a try and give feedback.

**Comment by i-am-offline** [comment]
Thank your for this.

How about using methods instead of properties to access the variables? So in your example it would be

- property name --> child item "name"
- method name() --> attribute "attribute"

Other item attributes already have getter methods (e.g. name, type)
Getter and setter could be included in one method (similar to `__call__`)

b.t.w: I actually have child items called "trigger" ...

**Comment by smaiLee** [comment]
I like the solution with methods, but I'm afraid this wont work.
AFAIK an object can't have a property and a method with same name.

**Comment by smaiLee** [comment]
I just realized that the problem is not dedicated to the new feature or python but to yaml - even in older versions of SHNG.
You can't have two attributes with same name - and in item.yaml sub-items are just attributes of type associative array.

**Comment by ohinckel** [comment]
Another idea how to separate properties from child items is:
```yaml
item:
  properties:
    type: str
    ...
  child1:
    properties:
      ...
  child1:
    properties:
      ...
```
So properties are explicitly listed in a `properties` section, children can just be added as direct-child element. But this would make it impossible to declare a child item with name `properties`.

Maybe the other way around would be better:
```yaml
item:
  type: str
  ...
  children:
    child1:
      ...
    child2:
      ...
```

This way you need to declare what is a children by putting them into an own section named `children`. Could also be easier to migrate existing configurations and you do not have to prefix all the properties with `i_..` as [suggested above](https://github.com/smarthomeNG/smarthome/issues/296#issuecomment-435231574).

**Comment by smaiLee** [comment]
Actually I don't see why the attributes of items have to be Python properties.
Why not just implement `Item.get_iattr_value(self, attribute)` and `Item.set_iattr_value(self, attribute, value)`?

This wont solve the existing problem in YAML but at least prevents new problems in Python.

**Comment by msinn** [comment]
I think this is quite complicated in usage. I would prefer to follow the idea of @i-am-offline and make methods out of the properties. That should avoid conflicts with items and we don't need to put all those 'properties' to the reserved word list.

I have to test that...

**Comment by smaiLee** [comment]
As mentioned in https://github.com/smarthomeNG/smarthome/issues/296#issuecomment-435298270 this wont work - obviously an object can't have a property and a method with same name.
Or did I misunderstand the proposal?

**Comment by msinn** [comment]
Thats why I think about converting the properties to methods: Instead of having an item property **name** have a method **name()** to set/get the value of that internal property **_name**.

**Comment by smaiLee** [comment]
Yes, I understood this.
But taking your example from https://github.com/smarthomeNG/smarthome/issues/296#issuecomment-435231574 (ignoring that this wouldn't work in YAML either):
```yaml
itemtree:
    gas_station:
        name: 'cheapest station'
        ...

        street:
            type: str
            ...
        name:
            type: str
            ...
```

itemtree.gas_station would then have a property `name` (the sub-item) and a method `name()` - and that's the thing which does not work.

**Comment by psilo909** [comment]
@msinn but changing this will now introduce a breaking change for all plugins and logics which currently use a "name()" function.. and i am no fan of just naming new methods with the prefix

**Comment by msinn** [comment]
Have you read my last post?

**Comment by psilo909** [comment]
@msinn yes? thats why i mention that introducing an "i" prefix to even existing functions is a breaking change?

or do i not get the point?!?

**Comment by msinn** [comment]
Why is it a breaking change if I introduce a new additional feature using en i_<property> naming?

**Comment by msinn** [comment]
Remenber: Up to now there is no function name() (at least in the released version)

**Comment by psilo909** [comment]
@msinn as written in gitter: as long as it is only for new functions it is ok.. but naming only new functions this way makes no sense?

**Comment by msinn** [comment]
What name should they have then?

**Comment by smaiLee** [comment]
> Maybe something like i (for item property) or p (to signal it is a property). To avoid most conflicts it could be i_?

Just my 2 cents:
I would prefer `a_` or even better `attr_`
`i_` could be misunderstood as "item" instead fo "item property"
And in SmartPlugin they are called attr (like get_iattr_value) not property.

The longer prefix "attr" is more clear than just "a" or "i" and the risk of overlapping a sub-itemis reduced (sub-items called "i_trigger" or "a_trigger" seems more likely than "attr_trigger").

**Comment by psilo909** [comment]
perhaps we should just keep functions in master for compatibility for 1 release or sth.. and redirect from the old function to the new one and log a deprecated warning?

**Comment by msinn** [comment]
@psilo909 I was thinking about that for the methods we already have: type(), last_change(), age(), ...

**Comment by psilo909** [comment]
@msinn perhaps we can also do that for methods that exist in the dev currently before the release.. i think i adapted many plugins to the new path() function for example. currently i dont know all places where this was done..

**Comment by msinn** [comment]
@smaiLee we are talking about two things: 

1. plugin-specific attributes (stored in conf-dict) 
and 
2. properties, which might have other values then the configured attribute values in item.yaml

**Comment by msinn** [comment]
@psilo909 as long as we don't expect conflicts with item naming that's ok for me.

**Comment by msinn** [comment]
Another question (or decision to be made): Besides naming convention, implement it as properties or as methods. Each has it's advantages and disadvantages:

Properties can be used on the receiving end of assignments:
```
sh.test.name.xx_name = 'New name'
```
and would be questioned this way:
```
myvar = sh.test.name.xx_name
```

Methods on the other hand:
```
sh.test.name.xx_name('New name')

myvar = sh.test.name.xx_name()
```

**Comment by smaiLee** [comment]
According to https://stackoverflow.com/a/36943813 I would avoid methods
> The "Pythonic" way is not to use "getters" and "setters", but to use plain attributes, like the question demonstrates
[...]
If later, you want to modify the setting and getting, you can do so without having to alter user code, by using the property decorator

**Comment by smaiLee** [comment]
An alternative to prefixing would be what @ohinckel supposed for YAML in https://github.com/smarthomeNG/smarthome/issues/296#issuecomment-435311098
So instead of `sh.test.name.xx_name` it would be `sh.test.name.xx.name` (where xx e.g. could be "props" or "properties").

Personally I would prefer this because prefixing seems somehow uncommon for me.
The impact for compatibility is similar or even smaller:
There would be one new keyword (this "props" or "properties"). By using prefixes there are several new keywords (all the property names with prefix).
On the other hand this prefixed names are less likely used as item name already.

**Comment by msinn** [comment]
@smaiLee That's why I implemented it as properties. But someone was against using the property = assignment, so I decided to ask. I like the property way.

But the method way has the advantage, that you can use multiple parameters in the assigenment. For example:

```
sh.test.name.property.value('New value', 'logic abc')
```
To signal that a value was set by logic abc, like it is now for
```
sh.test.name('New value', 'logic abc')
```

I could live with the extra .property.

**Comment by msinn** [comment]
I have implemented the public properties of the item class thru an inner class. They are now available thru ```sh.<item-path>.property.<property>```

Now the only new *forbidden word* in item naming is **property**.

The properties are really implemented as properties (not as methods). The access works like shown in this example:
```
eu = sh.test.name.property.enforce_updates
sh.test.name.property.enforce_updates = True
```

At the moment the following public properties exist:
- enforce_updates (bool, r/w)
- eval (str, r/w)
- name (str, r/w)
- path (str, r/o)
- trigger (list of str, r/w)
- type (str, r/o)

If access to other internals of the item class is needed, I'll add it per request.

**Comment by msinn** [comment]
I have implemented the properties in the form of ```<item>.property.<propertyname>```. Doucmentation:
https://www.smarthomeng.de/dev/user/konfiguration/items.html or https://www.smarthomeng.de/dev/developer/items.html.

@i-am-offline Have a look if it works for you.

**Comment by i-am-offline** [comment]
@msinn thank you, it seems to work great.

However, i found one small bug in your implementation. In lib/item.py, line 891 there is an `._item` to much.
The line reads

                self._item._item._enforce_updates = value

which caused an error when setting the enforce_updates property.
After changing it to

                self._item._enforce_updates = value

the error was fixed.

**Comment by msinn** [comment]
@i-am-offline The bug is fixed. Can we close this feature request?

**Comment by i-am-offline** [comment]
Thank you.
