### ISSUE TITLE
avm plugin: Exception bei outgoing.last_call_date

### ISSUE THREAD

**Issue by msinn** [smarthomeNG/smarthome#30]
Um den last outgoing caller richtig zu bekomme, habe ich bei **last_caller** und **last_call_date** das cache = yes auskommentiert. Dann liefert das plugin den richtigen Namen für den last caller outgoing.

Wenn ich danach den cache wieder einschalte, bekomme ich wieder den falschen Namen. 
Wenn ich den cache wieder ausschalte, bekomme ich wieder den richtigen Namen. 

Ich hatte beim ersten mal als ich die cache Zeilen auskommentiert hatte folgende Exception (reproduzierbar). Nach dem wieder einschalten und nochmaligem ausschalten des Caches konnte ich die Exception nicht mehr produzieren.

```
2016-04-24 17:01:51 ERROR    Main         Item wohnung.fritzbox.monitor_wt.outgoing.last_call_date: problem creating: 'avm_data_type'

Traceback (most recent call last):
  File "/usr/local/smarthomeNG/lib/item.py", line 219, in __init__
    child = Item(smarthome, self, child_path, value)
  File "/usr/local/smarthomeNG/lib/item.py", line 275, in __init__
    update = plugin.parse_item(self)
  File "/usr/local/smarthomeNG/plugins/avm/__init__.py", line 572, in parse_item
    if item.conf['avm_data_type'] in ['is_call_incoming','is_call_outgoing',
KeyError: 'avm_data_type'
```

**Comment by psilo909** [comment]
kann es sein, dass das alte item jetzt nich im file cache liegt? keine ahnung wie man den cleared aber ich tippe aktuell eher darauf, dass jetzt durch das testen im cache was corrupt ist. das cachen der calllist im plugin hat damit nichts zu tun. bitte mal selber noch weiter nachgehen

**Comment by msinn** [comment]
Ja,
nachdem ich die entsprechenden Dateien in var/cache gelöscht habe ist das Problem weg.

**Comment by psilo909** [comment]
Issue damit erstmal geschlossen!
