### ISSUE TITLE
behavior of .age() and  .prev_age()

### ISSUE THREAD

**Issue by sisamiwe** [smarthomeNG/smarthome#308]
Hi,
I'm testing the development branch and doing this I've noticed, that the behavior of the item function  .prev_age() has changed.
It seems that the function .prev_age() is resulting in a value that should be the result of the function .age().
The function .prev_age() provides a non-static value.

Is this intended?

**Comment by msinn** [comment]
No this was not intended. Internally a wrong function was called.

Fixed.
