### ISSUE TITLE
Attribut **threshold** needs an overhault in documentation, tests and maybe bugfixes

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#309]
It is unclear, how **threshold** attrib is realy working and how to configure it.

- An update to [documentation](https://www.smarthomeng.de/user/konfiguration/items_standard_attribute.html?highlight=threshold) is needed including a real world sample how to use it.
- clearification of separator | or : for the values
- maybe bugfixing if it does not work at all

**Comment by smaiLee** [comment]
Code is in https://github.com/smarthomeNG/smarthome/blob/f0a8cce0e169897e56e21d5fb5b1629e5e25bc2b/lib/item.py#L558-L566 and https://github.com/smarthomeNG/smarthome/blob/f0a8cce0e169897e56e21d5fb5b1629e5e25bc2b/lib/item.py#L2106-L2112

**Comment by msinn** [comment]
Should be fixed by Commit https://github.com/smarthomeNG/smarthome/commit/2c596dc8c64e96233d3e3472412cd2078803f1b4

**Comment by bmxp** [comment]
Should be working as documented. If any errors may arise or a deep test suite shows anything else, feel free to reopen.
