### ISSUE TITLE
multiple GAs for knx_cache lead to error

### ISSUE THREAD

**Issue by henfri** [smarthomeNG/smarthome#316]
Hello,

user error, but should lead to a proper error message:
If knx_cache gets more than one GA, this error appears in the full log:

```
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/item.py", line 662, in __init__
    child = Item(smarthome, self, child_path, value)
  File "/usr/local/smarthome/lib/item.py", line 727, in __init__
    update = plugin.parse_item(self)
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 462, in parse_item
    if not ga in self.gal:
TypeError: unhashable type: 'list'
```

Proposal:
a) handle the exception and give a logger.error("knx_listen can only take one GA")
-possibly in combination with
b) use the first GA provided only

**Comment by msinn** [comment]
Could you add the following lines to the knx plugin as a test and give feedback isf it fixes your problem:

add at line 33 (just were the other import statements are)
```
from lib.utils import Utils
```

and add directly **before** line 462: ``if not ga in self.gal:``:
```
            if Utils.get_type(ga) == 'list':
                self.logger.warning("{} Problem while reading KNX cache: Multiple GA specified in item definition, using first GA".format(item, ga))
                ga = ga[0]
```

**Comment by henfri** [comment]
No... type object 'Utils' has no attribute 'get_type'
I will check.

**Comment by msinn** [comment]
You are right. The get_type function has been added after v1.5.1 (it is only in develop)

**Comment by msinn** [comment]
You can use the lib/utils.py from the develop branch with your installation from master.

**Comment by henfri** [comment]
That seems to work. Thanks!
It may be needed at other knx_* as well, of course.

**Comment by msinn** [comment]
It is needed on knx_init (were I already have implemented it) it is **not** needed on knx_listen, where it is valid to have multiple GAs. That‘s why I put out a WARNING, not an ERROR. It is only the initialization that has to decide which GA to use.

**Comment by msinn** [comment]
Fix/Enhancement rolled out with v1.6

**Comment by henfri** [comment]
Thanks!

**Comment by henfri** [comment]
Hello,

I do not remember/understand, why it is not needed on 
knx_init
knx_cache

but not on
knx_listen

...

Can you remind/explain?


Regards,
Hendrik
