### ISSUE TITLE
[CORE] logger.info in stat.py for EPHEM version is spamming the logfile

### ISSUE THREAD

**Issue by sandman60** [smarthomeNG/smarthome#32]
Hi,

it seems that due to this line the logfile is logging every 5 mins. the EPHEM-version.

Suggest to change from " logger.info('Ephem Version: {0}'.format(ephem.__version__)) " to " logger.debug('Ephem Version: {0}'.format(ephem.__version__)) ". In general the logging of the EPHEM version to an env.-item is brilliant and should be kept.

Cheers,
Oliver

**Comment by cstrassburg** [comment]
Erledigt
