### ISSUE TITLE
FreeBSD compatibility: logics/watchdog.py

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#328]
logics/watchdog.py:

`call("/bin/touch /usr/local/smarthome/var/run/smarthome.watchdog", shell=True)`

In FreeBSD ist touch in /usr/bin/touch. Deshalb gibts es Fehlermeldungen.
Dieses Kommando sollte doch eigentlich bei jedem System im Path sein ?

Vorschlag zur Anpassung zwecks Kompatibilität:

`call("touch /usr/local/smarthome/var/run/smarthome.watchdog", shell=True)`

**Comment by ohinckel** [comment]
Sollte man das nicht besser gleich durch Python-Code (z.B. [pathlib.Path.touch()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.touch)) ersetzen anstatt Shell-Code fuer diesen trivialen Task zu verwenden?

**Comment by Foxi352** [comment]
Selbstverständlich wäre das besser. 

Da meine Linux VM sich permanent aufhängt, spricht einfach freezed ohne kernel panic oder sonst ersichtlichen Grund, bin ich dabei definitiv mein SHNG und SV auf FreeBSD zu migrieren. Ich werde für alles was mir auffällt Issues öffnen und Kommentare wie dieser sind herzlich willkommen. Das trägt dann auch gleich zur MacOS Kompatibilität bei ...

Sobald ich dann Zeit habe will ich alles was mit FreeBSD Kompatibilität zu tun hat in einem Push zusammen updaten. (Ausser die Issues die eventuell schon geschlossen wurden).

**Comment by ohinckel** [comment]
> Sobald ich dann Zeit habe will ich alles [...] in einem Push zusammen updaten.

Hoert sich gut an! Danke fuer die Info und die Muehe!

**Comment by msinn** [comment]
@Foxi352 Ich verstehe das Issue irgendwie nicht. Du schreibst
```
logics/watchdog.py:

...
```
Eine Datei watchdog.py im logics Verzeichnis ist kein Bestandteil von SmartHomeNG.

Was meinst Du mit dem Issue?

**Comment by Foxi352** [comment]
Uh, das ist schon lange her :-) Muss ich nachschauen.

**Comment by Foxi352** [comment]
Also ich hab in meinen logics seit jeher ein  watchdog.py mit folgendem Inhalt:
```
#!/usr/bin/env python
from subprocess import call
call("touch /usr/local/smarthome/var/run/smarthome.watchdog", shell=True)
```

Keine Ahnung wo das herkommt. Mir irgendetwas uraltes sein. Ich kann mich aber nicht erinnern, dass ich das erstellt haben sollte. Falls das nicht irgendwie bestandteil von SH ist dann bitte Issue schliessen und ich werd die Datei dann mal verschieben :-)

**Comment by msinn** [comment]
Im master und im develop gibt es im logics Verzeichnis nur diese Dateien:

- .gitignore
- blockly_logics.py
- blockly_logics.xml
- example_logging.py
- example_persistance.py

und im alten smarthojme.py von mknx gab es nur .gitignore. Die Datei musst Du vermutlich woanders her haben.

Ich mach dann hier mal zu.
