### ISSUE TITLE
[avm plugin] Feature Request: Callmonitor Item(s) für eigene Telefonnummer

### ISSUE THREAD

**Issue by msinn** [smarthomeNG/smarthome#33]
Hi René,

ich habe 7 Telefonnummern auf der Fritz!Box. Da wäre es wichtig, wenn ich bei eingehenden Anrufen ermitteln könnte, für welche meiner Nummern der Anruf ist.

Analog (aber nicht ganz so wichtig) für ausgehende Anrufe: Hier wäre es schön, wenn ich ermitteln könnte, unter welcher eigenen Nummer der ausgehende Anruf geführt wird.

Viele Grüße
Martin

**Comment by psilo909** [comment]
Du möchstes auf Basis der aktuellen Implementierung neben dem Namen noch die Nummer ODER möchtest Du für jede Nummer einen eigenen CallMonitor? 

Letzeres ist erstmal aus Zeitgründen nicht umsetzbar, weil so gut wie unmöglich vernünftig zu testen (paralleles Rufhandling etc).
Zweiteres lässt sich die Woche mal abends bauen.

Allgemein kannst Du jetzt schon optional den Callmonitor für eine (1) Zielrufnummer bei Dir filtern. Das reicht aber nicht wie ich das verstehe.

**Comment by msinn** [comment]
Ich möchte auf Basis der aktuellen Implementierung zusätzlich meine eigene Nummer (die angerufen wurde bzw. die den ausgehenden Anruf führt).

Für jede Nummer ein Callmonitor wäre definitiv Overdone. Für die Zukunft könnte man höchsten darüber nachdenken zwei Callmonitore zu haben. Mehr Gespräche lassen sich über den Anschluß parallel nicht führen, auch wenn man mehr Telefonnummern haben kann.

**Comment by psilo909** [comment]
@msinn gehen hypothetisch nicht doch mehr als 2? ansich wäre der beste ansatz beliebig viele callmonitore unter angabe der internen rufnummer auf die er hoeren soll zu instantiieren. ich glaube aber ich habe jetzt schon nen bug mit dem killen von threads und das wird dann iregdnwie noch krasser.

ich baue dir jetzt erstmal das mit der nummer noch und suche dann lieber die nächsten wochen weitere bugs.. heute um 16:20 war meine box wohl auch überlastet von der gesamt-request-menge. alle items sind schon ein ganz schönes bombardment für das device.. die cycle time sollte imho evtl sogar raufgesetzt werden.

**Comment by psilo909** [comment]
Also für Incoming Calls ist alles gut, für Outgoing kriege ich mind als der get_calllist nur ein "SIP: xxxxxxx" anstatt der reinen Nummer. Aus dem "echten" Callmonitor könnte aber die "pure Nummer" gehen...

**Comment by msinn** [comment]
Hypothetisch gehen auch mehr als 2 Gespräche. Nur nicht mit den Standard Telefonie-Providern. ISDN kann nur 2 Gespräche zur Zeit und die "Ablösungsangebote" über VOIP sind auch auf 2 parallele Gespräche beschränkt. 

Wenn jemand auf andere SIP Provider zurückgreift, gehen auch mehr als zwei Gespräche (je nach Box).

**Comment by psilo909** [comment]
Das SIP haue ich jetzt im Regex aus dem Feld raus.. Initialisierung geht schon, jetzt halt noch "live" Update via CallMonitor.

Bitte beobachte bei Deinen Tests mal, ob die FB irgendwann nichtmehr annimmt. Hatte heute Nachmittag paar Errors wegen Timeout..

Zudem mal die Threadanzahl bitte beobachten. Bin nicht sicher ob ich überall sauber beende.

**Comment by msinn** [comment]
Für die Anzeige der eigenen Nummern ist Incoming auch wichtiger als Outgoing. Damit kann man entscheiden, wer eigentlich angerufen wurde. 

Outgoing das "SIP: xxxxxx" finde ich auch nicht so schlimm. Es geht nur um die Unterscheidbarkeit der Nummern, nicht um die Nummern an sich.

Bei mit steht bei einem ausgehenden Anruf in der csv Liste z.B.:

```
4;24.04.16 22:32;Martin;0172400xxxx;IP-Telefon 607xxxxx;Internet: 40607xxxxx;0:01
```
wobei **Internet: 40607xxxxx** für die VOIP Konfiguration zum Provider steht und **IP-Telefon 607xxxxx** für das per SIP an der Fritz!Box angeschlossene VOIP Telefon.

**Comment by psilo909** [comment]
Kannst Du mir mal Deine Header dazu sagen?

**Comment by msinn** [comment]
```
sep=;
Typ;Datum;Name;Rufnummer;Nebenstelle;Eigene Rufnummer;Dauer
4;24.04.16 22:32;Martin;0172400xxxx;IP-Telefon 607xxxxx;Internet: 40607xxxxx;0:01
```

**Comment by psilo909** [comment]
ich meinte eher die header wie sie aus der fritzbox zu den feldern zugeordnet "rauspurzeln" ;) Da müssten sie englisch sein.

**Comment by msinn** [comment]
Wo meinst Du denn "rauspurzeln"? 

Ich hatte oben den Header, so wie er in der csv Datei steht gepostet.

**Comment by psilo909** [comment]
du exportierst über die gui der fritzbox nehme ich an? meinte den technischen header wie ich ihn in der get_calllist auslese: attributes = ['Id', 'Type', 'Caller', 'Called', 'CalledNumber', 'Name', 'Numbertype', 'Device',  'Port', 'Date', 'Duration']
aber auch egal: probier bitte einfach mal ob die neuen items bei dir jetzt das gewünschte anzeigen.

**Comment by psilo909** [comment]
noch ein Hinweis: das Feature bei Anruf von einer Quellenummer auf eine Zielnummer Items zu triggern ist wohl nicht so ohne.. Offenbar kann man mit CLIP no screening die Quellrufnummer faken. Auf jdn Fall hat mir gerade ein Bekannter dempnstriert, wie er in Kenntnis der Nummern mein Tor öffnen kann :> daher mit Vorsicht verwenden!!

**Comment by psilo909** [comment]
die neuen Items sind jetzt ja da, reicht das für die Schließung des Issues?

**Comment by msinn** [comment]
Die neuen Items funktionieren! Auf Seiten das AVM Plugins ist soweit alles ok.
Das Widget für den Callmonitor könnte noch um die eigene Nummer erweitert werden.
Alternativ könntest Du ein weiteres Widget erzeugen, weil nicht jeder Nutzer mehrere Nummern nutzt und die Zusatzinfo vielleicht überflüssig findet. 

Ich habe mich nur beim testen schwergetan. Ich bin anscheinend über einen Bug in der Autogeneration von Visu Pages gestolpert. Das untersuche ich im Nachgang.

**Comment by psilo909** [comment]
Naja die Widgets sind aus meiner Sicht schöner Wohnen. Wer mehr will sollte fähig sein, die auf seinen Bedarf anzupassen. Aber mal schauen...

**Comment by msinn** [comment]
Ich mach dann gleich mal "Schöner Wohnen" 😄  und schick Dir die überarbeiteten Widgets zu. (Dem Systeminfo fehlt auch noch ein 'br').

Das "Schöner Wohnen", also möglichst vollständige und möglichst auch optisch ansprechende Widgets finde ich gerade für Einsteiger eine gute Hilfestellung. Das ist auch ein Grund warum ich das Ausliefern von Widgets mit den Plugins angegangen bin.

**Comment by psilo909** [comment]
Gerne :) ich hab auch keinen Kummer, wenn Du die im Plugin-Folder direkt updatest ;) So lange sie getestet sind.
