### ISSUE TITLE
Feature Request: threshold for database plugin

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#339]
I have some float items that constantly change their value (based on a sensor) very marginally, eg. 20.34, 20.38, 20.12, 19.99 etc.

It is not very useful to write every small change into the database. So I propose an additional database_threshold keyword that specifies the necessary minimum change of an item to write it in the database. Example:
Last entry in database for specific item is 20.00 (maybe on init it should always write the current value, not regarding the threshold)

Item has database_threshold of 1.50
Item changes to 20.50, 21.20, 19.00, 21.25 and does not get written to the database as the value change in comparison to the last database entry (not the last item value!) is less than 1.50

After the last change to 21.25 the item value changes to 21.50 and now gets written to the database.

I'm aware that the problem could be solved by using extra items and/or logics but it might be a nice feature for the plugin itself.

**Comment by smaiLee** [comment]
I implemented exactly this behaviour for another plugin. I will check if the code could be easely adapted for database plugin.

**Comment by ohinckel** [comment]
I think is was already requested in #285 and we should track this in the old issue instead of creating a new one.

**Comment by onkelandy** [comment]
Yep its the same. Too old I could remember/find it ;)
