### ISSUE TITLE
Support für Python 3.2 und Python 3.4

### ISSUE THREAD

**Issue by cstrassburg** [smarthomeNG/smarthome#34]
#31

Vorgehen überlegen für die Sicherstellung der Kompatibilität zu Python 3.2 und 3.4 
- Zeitraum für unterstützte Python Versionen definieren. 
- automatisierte Tests

**Comment by encbladexp** [comment]
Ansatz: Support der letzten 2 Python 3 Versionen welche in Ubuntu LTS drin sind. Das wäre aktuelle Python 3.4 und 3.5.

**Comment by bmxp** [comment]
Hm. Ich würde es ein wenig davon abhängig machen, welche Python Version es maximal auf einem Raspi gibt. Es gibt sehr viele Leute, die über den Raspi zum SmarthomeNG.py kommen. Die steigen vielleicht mal später auf Jessie und NUC um aber um die Anfänge gut zu meistern liegt die Einstiegshürde beim Raspi sehr niedrig. Aktuelles Image bei Raspbian basiert auf Debian Jessie und nicht mehr auf Wheezy. Lt. [Debian.org](https://packages.debian.org/de/jessie/python/) sollte das ein 3.4.2 sein. Daher würde ich ab der nächsten Release ein 3.4 voraussetzen wollen.

**Comment by msinn** [comment]
Ich hole das Thema nochmal hoch. Sollen wir für die Version 1.3 wirklich noch Python 3.2 unterstützen? Inzwischen ist Python 3.6 released. Rückwärts-Kompatibilität bis zu Python 3.4 sollte inzwischen eigentlich hinreichend sein.

Anderenfalls sollten die Travis Checks für Python 3.2 lauffähig gemacht werden. Die schlagen bei Pull-Requests im Moment standardmäßig fehl.

**Comment by ohinckel** [comment]
Die Tests schlagen deswegen fehl, weil man mit den Abhaengigkeiten vorsichtig umgehen muss (unicode vs. non-unicode Module). Laesst sich bisher eigentlich einfach loesen weil man die Abhaengigkeiten mitPython Version hinterlegen kann. Macht man dass oder geht entsprechend mit der Version der Abhaengigkeit runter loesen sich auch die Probleme.

Das erstman allgemein in den Griff zu bekomen war etwas aufawendiger. Aber aktuell koennte man einfach die requests Abhaengigkeit fuer das tankerkoenig Plugin entsprechend runterdrehen oder mit Python-Version hinterlegen (wer sich auch immer dazu berufen fuehlt - notfalls hinterlege ich das man). Damit waeren die Tests wieder gruen.

Das klaert aber die die eigentliche Frage. Von meiner Seite aus weiss ich nicht ob es wirklich noch andere Probleme mit 3.2 gibt und ob sich das lohnt den Support dafuer einzustellen. Wenn es wenig Probleme gibt sollten wir es vielleicht einfach weiter unterstuetzen. Wie die Nutzung der 3.2er aussieht weiss ich aber auch nicht. Kann man eine Umfrage starten? Vielleicht mal im knx-uf?

**Comment by sandman60** [comment]
Habe noch ein Prod-System auf 3.2 (altes PI-Image) und das läuft bislang bis auf das Backend stabil unter 3.2. Umgekehrt gibt es ja inzwischen eine saubere Installdoku sowie ein PI-Image von Onkelandy, daher würde ich nun auch klar dazu tendieren 3.2 über die Klinge springen zu lassen.

**Comment by msinn** [comment]
@sandman60 Das Backend hatte ich damals auch noch unter 3.2 zum laufen gebracht. Welche Versionen man braucht hatte ich in ie README geschrieben. Ob das für den aktuellen Entwicklungsstand noch gilt, kann ich aber nicht sagen.

Ich würde auch für eine Einstellung der Unterstützung von 3.2 plädieren.

Ich bin allerdings nur drüber gestolpert, weil travis Tests für 3.2 für den Core fehlschlagen (für 3.3, 3.4 und 3.5 laufen sie). Das mag an einer fehlerhaften Config von travis liegen. Genau sagen kann ich das nicht. Ich habe mich in travis noch nicht eingearbeitet.

**Comment by ohinckel** [comment]
Mich wuerde vor allem interessieren wie die Benutzer das sehen. Koennte man mit einer Umfrage in Erfahrung bringen. Aber klar, wenn wir sagen wir wollen das nicht mehr, dann ist das eben so. Und nicht falsch verstehen, ich finde es auch gut alte Versionen loszuwerden, aber der Umstieg sollte auch ohne Probleme fuer die Benutzer moeglich sein (bspw. durch ein aktualisiertes RPi Image).

Aber anscheinend gab es ja mal den Bedarf 3.2 zu unterstuetzen (daher auch dieses Issue; vielleicht aber auch um anzukuendigen wie lange wir das noch unterstuetzen wollen). Und wenn sich der Aufwand gering haelt, warum nicht. Wenn es aber devinitiv keinen sinnvollen Grund mehr gibt, sollten wir lieber weg von dieser Version.

Warum die Tests fuer 3.2 nicht laufen ist klar und kann aktuell auch einfach gefixt werden (siehe Kommentar von oben). Das sollte nicht das Problem sein.

Die Tests fuer 3.5 sehen zwar gruen aus, laufen aber nicht da 3.5 bei travis-ci aktuell nicht verfuegbar/installiert ist und tox so eingestellt ist, das in diesem Fall kein Fehler gemeldet wird, sondern das ignoriert wird und der Testkauf gruen wird.

**Comment by cstrassburg** [comment]
Von mir aus kann die 3.2 Version weg. Man sollte eh immer zusehen das sein System auf einem aktuellen Stand ist, sonst hat man Probleme mit der Sicherheit. René war einer der die 3.2 weiterhin haben wollten, da es letztes Jahr für sein NAS keine neuere gab.
Mittlerweile wurde auch Python 3.6 released. 
Die Fehler bei Travis habe ich mir auch schon mal angeschaut, was etwas traurig ist, ist die mangelnde Unterstützung für Python >3.4 . Damit ist das Tool nur bedingt nutzbar.

Zurück zu den Versionen. In der Regel  setzt man für Produkte eine Strategie fest: z.B " unterstützt werden die aktuellste Version und zwei Vorgänger"

**Comment by msinn** [comment]
@psilo909 Brauchen denn 

- avm
- enigma2
- odlinfo
- pushbullet
- tankerkoenig

requests in der Version 2.9.1 oder größer?

Wenn die Requirements für diese Plugins nicht runter gedreht werden können, sollten wir dringend kurzfristig eine Entscheidung zum 'Droppen' des Python 3.2 Supports in shNG v1.3 treffen.

Falls wir auf eine requests Version runterkommen, die noch unter Python 3.2 läuft, können wir das 'Droppen' auch gerne noch ein Release verschieben. 

In der Doku zu requests steht 'Unterstützung für Python 3.1 und 3.2 kann zu jeder Zeit wegfallen.' und die letzte Version, die in den Change-Notes eine Python 3.2 Kompatibilität ausweist ist requests 1.2.1.

**Comment by sandman60** [comment]
Alle Plugins laufen bei mir mit Requests 2.5.1 und PY 3.2.

**Comment by msinn** [comment]
Ich habe zum Test ```requests==2.5.1```eingetragen. Das bringt die Tests ein ganzes Stück weiter.

Nun stolpert der Test für Python 3.2 in test_smarthome.py am ```import bin.smarthome```
mit der Meldung *ImportError: No module named bin.smarthome*
In den höheren Versionen von Python ist das kein Problem.

Ich habe travis-ci und tox übrigens do umkonfiguriert, dass jetzt die Versionen von 3.2 bis 3.6 auch wirklich getestet werden (können). Den Test für Python 3.2 kommentiere ich in der ```.travis.yml``` erstmal aus, damit die Tests sonst durchlaufen.

**Comment by ohinckel** [comment]
@msinn schoen dass das jetzt funktioniert. Danke!

Kannst du das auskommentierte Zeug aus den Konfigurationsdateien noch entfernen? Wird ja nicht mehr gebraucht und sieht sauberer aus.

Wenn die Plugins auf die andere Version von requests umgestellt wurden sollten die Tests fuer  3.2 doch auch durchlaufen, oder? Koennen wir daher die 3.2 wieder aufnehmen oder haben wir uns jetzt davon verabschiedet? Wenn ja, sollten wir das aber noch irgendwo verkuenden wenn wir das nicht mehr unterstuetzen.

**Comment by bmxp** [comment]
Naja, derzeit ist ja noch alles develop insofern braucht man noch nichts zu verkünden. Ich persönlich habe keinen Bedarf an der 3.2 Unterstützung aber auf etwas älteren NAS braucht man das schon. @psilo kommt da sicher drumherum bei Bedarf, ein unbedarfter Nutzer etvl. nicht.
Vielleicht sollten wir das nächste Release bei Gelegenheit mal festklopfen und dann damit auch 3.2 Support fallenlassen?

**Comment by psilo909** [comment]
@bmxp auf Synology ist mitlerweile Python 3.5 Standard

**Comment by msinn** [comment]
@ohinckel Die Tests für 3.2 laufen noch nicht durch. Angemeckert wird, wie ich oben schrieb,
```import bin.smarthome``` in test_smarthome.py
mit der Meldung *ImportError: No module named bin.smarthome*

**Comment by msinn** [comment]
@psilo909 Hattest Du das Requirement requests>=2.9.1 in den 4 Plugins gesetzt? Hattest Du einen Grund für die 2.9.1?

**Comment by psilo909** [comment]
@msinn das habe ich doch schon mal kommentiert: mein Grund ist, dass ich auf dieser Version meine Sachen entwickle und teste und nicht auf niedrigeren kann. nachdem @sandman60 die Funktion auf niedrigerer nun bestätigt hat, habe ich umgesetzt. aber ohne garantie

**Comment by msinn** [comment]
Ich habe das in den Requirements der 4 Plugins mal versionsabhängig eingetragen:
```
requests>=2.9.1;python_version>'3.2'
requests==2.5.1;python_version=='3.2'
```

**Comment by psilo909** [comment]
funktioniert das? muss mal testen wie sich das backend hier jetzt verhaelt

**Comment by msinn** [comment]
Das hatte cstrassburg an anderer Stelle bereits so verwendet.

**Comment by cstrassburg** [comment]
Das funktioniert so ganz gut, damit lassen sich die Requirements abhängig von der Umgebung steuern

**Comment by cstrassburg** [comment]
Ehrlich gesagt habe ich keine Lust mehr auf die unterstützung von Python <3.4 
```
Python 3.3 was released on September 29, 2012
Python 3.4.0 was released on March 16th, 2014
Python 3.5 was released on September 13, 2015 
```
Ich würde vorschlagen 3.6 und  3.5. 
Die 3.4 ziehen wir noch bis zum übernächsten Release durch und lassen dann den Support und Tests entfallen.

**Comment by msinn** [comment]
Mein Vorschlag wäre ähnlich: Wir sollten außer dem aktuellen Release zwei Vorgänger Versionen unterstützen. 

Das würde bedeuten, den Support für 3.2 und 3.3 zu droppen und 3.4 zu unterstützen, bis eine Version 3.7 erscheint.

**Comment by msinn** [comment]
Eine etwas realistischere Betrachtung der Releases ist es, nicht nach dem 0er Release sondern nach dem letzten Release zu sehen:

```
Python 3.3.6 was released on 2014-10-12
Python 3.4.5 was released on 2016-06-27
Python 3.5.2 was released on 2016-06-27

Python 3.6.0 was released on 2016-12-23
 ```

**Comment by encbladexp** [comment]
Ich wäre dafür das wir nur die jeweils aktuelle Version, und die aus Debian stable (dem aktuellem!) supporten.

**Comment by msinn** [comment]
Das finde ich als Besxhrwibung zu umständlich. Ich habe zum Beispiel keine Ahnung welches die aktuelle Stable Version von Debian ist und welche Python Version(en) darin enthalten ist/sind.

Wir sollten uns auf die Pyrhon Versionsnummern konzentrieren. Nur zwei Versionen finde ich knapp. Das wären dann 3.6 (3.6.0 ist erst im Dezember 2016 erschienen) umd 3.5 (3.5.0 ist im September 2015 erschienen).

Zumal 3.4 noch Fixes eralten hat, zu dem Zeitpunkt als auch die letzen Fixes für 3.5 erschienen.

Ich sehe im Moment realistisch nur Probleme die 3.2 zu unterstützen. Die 3.3 ist abwr genauso veraltet. Beide sind zwitgleich das letze mal gefixt worden.

Wie oben geschrieben bin ich für Support der aktuellen Version + 2 Versionen rückwärts.

**Comment by bmxp** [comment]
Ich würde vorsichtig mit den neuesten Versionen sein wie z.B. 3.6. Jetzt gerade ist aktuell zum Beispiel auf Windows - für uns nicht relevant aber als Beispiel passend - eine Unverträglichkeit von cherrypy aufgetaucht. Das zeigt das nicht immer das neueste auch stabil sein muß. Das erste "Service Pack" ist IMHO immer ein guter Zeitpunkt drauf einzusteigen. Ich würde demzufolge 3.4 und 3.5 favorisieren. 3.2 oder 3.3 würde ich nicht mehr berücksichtigen wollen und mit 3.6 vorsichtig sein und 3.6 einfach in die Tests mit einbinden.
Vielleicht sollten wir auch einen Blick Richtung Raspberry riskieren und versuchen die dort aktuell mit Raspbian verfügbaren Versionen berücksichtigen da dies ein häufig genutztes Einsteigermodel für SHNG darstellt.

**Comment by psilo909** [comment]
3.6 würde mich aktuell auch außen vor lassen. synology hat aktuell 3.5 als aktuellste on board :)

**Comment by ohinckel** [comment]
So lange es fuer eine Version noch security patches gibt koennten man die Version beruecksichtigen - waere dann sowas wie @msinn vorgeschlagen hatte (nicht das Release-Datum, sonder das Updated-Datum beruecksichtigen). Sofern es auch keinen grossen Aufwand darstellt diese Versionen zu unterstuetzen, sollten wir das auch versuchen.

Neue Versionen koennten wir nach Verfuegbarkeit in die Tests einbinden um zu sehen ob die ohne Fehler verwendbar ist (weitere Tests vorausgesetzt). Wenn stabil, dann aucn offiziell unterstuetzen.

**Comment by bmxp** [comment]
Noch einmal eine überarbeitete Übersicht:

| Version | released | letztes Servicerelease | released | Lebenszeit
| --- | --- | --- | --- | --- |
| 3.2 | 2011-02-20 | 3.2.6 | 2014-10-12 | ca. 3,5 Jahre
| 3.3 | 2012-09-29 | 3.3.6 | 2014-10-12 | ca. 2 Jahre
| 3.4 | 2014-03-16 | 3.4.5 | 2016-06-27 | ca 2 Jahre
| 3.5 | 2015-09-13 | 3.5.2 | 2016-06-27 | knapp 1 Jahr
| 3.6.0 | 2016-12-23 | - | - | vermutlich 2 Jahre ?

Raspbian Jessie vom März 2016 bietet bereits Python 3.4

**Comment by cstrassburg** [comment]
Es geht nicht nur um Sicherheitsupdates sondern auch um Features/Libs die man verwenden kann. Oft werden die Sachen nicht auf ältere Versionen portiert was zu Folge hat, dass man manche Libs garnicht verwenden kann. In so fern spielt die Version schon ne Rolle, denn selbst wenn z.B. 3.2 mit Sicherheitspatches versorgt werden sollte, bindet man sich sprachlich an die Einschränkungen dieser Version. Irgendwann wäre es schön die alten Zöpfe abschneiden zu können.

Ich denke mit der aktuellen Version und zwei Vorgängern würden wir ganz gut fahren.

**Comment by msinn** [comment]
Um dis Diskussion mal zu Ende zu bringen, wäre mein Vorschlag (als Konkretisierung von @cstrassburg 's Beitrag) der folgende:

Als aktuelle Python Version wird die Version festgelegt, die zum Beginn der Entwicklung einer Version die aktuelle Version ist/war. 'Beginn der Entwicklung' meint den Zeitpunkt, zu dem die Vorgängerversion released wurde.

Beispiel:
Zum Zeitpunkt des Release 1.2 von shng war Python 3.5 aktuell, also sollte dann SmartHomeNG 1.3 die Python Version 3.5 unterstützen (und zwei Vorgängerversionen: 3.4 und 3.3)

| SmartHomeNG | akt. Python zu Entwicklungsstart | unterstützte Python Versionen |
| --------------- | --------------------------------- | ------------------------------ |
| v1.2 und davor |  diverse                                            | Python 3.2, 3.3, 3.4                  |
| v1.3                   | Python 3.5                                       | Python 3.3, 3.4, 3.5                   |
| v1.4                   | Python 3.6                                       | Python 3.4, 3.5, 3.6                   |

Dies bedeutet nicht, dass SmartHomeNG unter älteren Python Versionen nicht mehr funktioniert. Es bedeutet nur, dass es unter älteren Versionen nicht mehr durchgängig getestet wird und und das (auch in Plugins) Funktionalitäten von Python genutzt werden können, die in den älteren Versionen nicht unterstützt werden.

Ich bitte um Rückmeldungen. Wenn die Präzisierung so ok ist, würde ich sie ins Wiki als verbindlich übernehmen.

**Comment by ohinckel** [comment]
Passt fuer mich. Wir haben 3.2 im develop bereits auch schon verbannt (zumindest was die Tests angeht) und verwenden nur noch 3.3-3.6.

**Comment by msinn** [comment]
Hat außer ohinkel niemand eine Meinung?

**Comment by bmxp** [comment]
Wenn wir mal zu einem 1.3 Release kommen ...? Debian Jessie bringt Python 3.4 mit. Da Debian immer sehr konservativ ist mit neuen Versionen und Wert auf Stabilität legt, wäre derzeit IMHO die älteste unterstützte Python Version die 3.4. Sobald Debian Stretch erscheint (Juni 2017), wird es Python 3.5 sein.
Daher würde ich als Minimum derzeit immer die im letzten stabilen Debian gelieferte Python Version setzen wollen. Da das mit Deinem Vorschlag oben harmoniert, passt das von mir aus.

**Comment by msinn** [comment]
Die Regel für die durch SmartHomeNG unterstützten Python Versionen wurde ins Wiki aufgenommen.
