### ISSUE TITLE
env.system.start is printed as NaN in Safari

### ISSUE THREAD

**Issue by chester4444** [smarthomeNG/smarthome#340]
printing env.system,start in _Safari_ (apple browser) with
`{{ basic.print('', 'env.system.start', 'short') }}`
results in **_NaN_**.

Initializing env.system.start in [lib/env/init.py](https://github.com/smarthomeNG/smarthome/blob/master/lib/env/init.py#L20) should be like this:

`start =datetime.datetime.fromtimestamp(psutil.boot_time()).strftime("%Y-%m-%dT%H:%M:%S")`

Please note the 'T' between date and time, as it should be according to ISO 8601.

**Comment by psilo909** [comment]
isnt this more of an issue for SmartVISU?

**Comment by chester4444** [comment]
env.system.start is initialized in smarthomeNG, lets say in slightly sloppy way.

smartVISU just handle it over to a browser. Safari refuses to print it, since it is out of standard.

**Comment by bmxp** [comment]
According to ISO that is correct but  I would suggest to just remove the strftime and keep it as datetime just like ``sh.env.core.start``

**Comment by chester4444** [comment]
Ok, now I'm using
`sh.env.system.start(datetime.datetime.fromtimestamp(psutil.boot_time()), logic.lname)`
and it works too - thanks

BTW: good job on the whole smarthomeNG project!

**Comment by bmxp** [comment]
@msinn , @psilo909 anything what would vote against a change?

**Comment by psilo909** [comment]
try it and i will test it ;) its dev branch anyway.

**Comment by bmxp** [comment]
Ok. I've pushed this to dbd77b81
