### ISSUE TITLE
Connection polling failed Error on Mac OS X

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#350]
Sometimes I get this error on startup, most likely after some timeout with the ical plugin or general network stuf..?
Happens on Mac OS X
```
2020-04-13  21:22:21 ERROR    __main__          Connection polling failed: name 'KQ_EV_ONESHOT' is not defined
Traceback (most recent call last):
  File "bin/smarthome.py", line 640, in start
    self.connections.poll()
  File "/Users/ank/smarthome/lib/connection.py", line 214, in poll
    flags=select.KQ_EV_ADD | KQ_EV_ONESHOT))
NameError: name 'KQ_EV_ONESHOT' is not defined
```

**Comment by msinn** [comment]
@Foxi352 is using SmartHomeNG on Mac OS and had started moving the functionality from lib.connection to lib.network. Maybe he has an idea.

**Comment by msinn** [comment]
According to the Python documentation 3.0 (and back to 3.5) KQ_EV_ONESHOT is valid on all operating systems. Pycharm shows it as undefined in the source (I am developing on Mac OS). 

So, I have no idea what is going on.

**Comment by bmxp** [comment]
Thos is very old. Does the problem still exist?

**Comment by onkelandy** [comment]
Haven't tested this anymore but I guess the problem is gone. At least I didn't see the error anymore.
