### ISSUE TITLE
mqtt subscription not working when smarthomeNG installed in different directory

### ISSUE THREAD

**Issue by i-am-offline** [smarthomeNG/smarthome#355]
I have an item with an mqtt subscription. The mqtt message received from the broker was not processed correctly. The log showed:

    2020-05-03  10:37:08 ERROR    modules.mqtt        _on_mqtt_message: received topic for unknown subscriber_type 'unknown'
    2020-05-03  10:37:08 ERROR    modules.mqtt        _on_mqtt_message: Received topic 'diele/geraete/pir', payload 'b'True'', QoS '0', retain '0' WITHOUT matching item/logic

It took me quite a while to track this issue down, but then I realized that the reason is the installation directory. I did not install smarthomeNG in `/usr/local/smarthome` as shown in the manual, I installed in `/srv/smarthome`. 

The coding which causes the issue is in method `_get_caller_type` in class `Mqtt` (modules/mqtt/__init__.py). In this method, hardcoded directory levels are used. In my installation the method returned "Unknown" due to the different directory levels. Therefore incoming messages could not be correctly assigned. Changing the hardcoded directory levels according to my installation fixed the issue for me, but is not a general solution.

As a general solution I have changed the method, so that the filename parts are accessed "from the top". Different directory levels for the installation should not matter this was. Pull request will follow soon.

**Comment by msinn** [comment]
The PR #[356](https://github.com/smarthomeNG/smarthome/pull/356) has been merged into develop and has been included in the release v1.7.2 of SmartHomeNG.
