### ISSUE TITLE
Mehrere DeprecationWarning, durch Python 3.8 ?

### ISSUE THREAD

**Issue by Foxi352** [smarthomeNG/smarthome#358]
```
bin/smarthome.py:842: DeprecationWarning: CRLType has been deprecated, use CRL instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: NetscapeSPKIType has been deprecated, use NetscapeSPKI instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: PKCS12Type has been deprecated, use PKCS12 instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: PKCS7Type has been deprecated, use PKCS7 instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: PKeyType has been deprecated, use PKey instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: X509ExtensionType has been deprecated, use X509Extension instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: X509NameType has been deprecated, use X509Name instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: X509ReqType has been deprecated, use X509Req instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: X509StoreType has been deprecated, use X509Store instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: X509Type has been deprecated, use X509 instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: ConnectionType has been deprecated, use Connection instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: ContextType has been deprecated, use Context instead
  obj = getattr(module, sym)

```

**Comment by msinn** [comment]
Bitte eine ältere Python Version benutzen. SmartHomeNG 1.7x ist nicht für Python 3.8 freigegeben (siehe Doku)

**Comment by msinn** [comment]
Nachtrag: Die als deprecated gemeldeten Strings kommen in der SmartHomeNG Installation nicht vor. Beziehen die sich vielleicht auf ein privates Plugin?

**Comment by ohinckel** [comment]
Laut Stacktrace koennte es sich hierbei um ein Modul handeln. Wenn ich mir die Typen anschauen koennte ich mir vorstellen dass es etwas mit dem `http` Modul zu tun haben koennte (CRL, X509, PKCS - hat alles mit Zertifikaten zu tun und daher evtl. relevant fuer HTTP/TLS).

Koennte daher von der openssl Bibliothek kommen:
  https://github.com/pyca/pyopenssl/pull/814
... die evtl. von anderen Bibliotheken verwendet wird (z.B. cherrypy).

**Comment by Foxi352** [comment]
Ich antworte dann hier mal auf alle Kommentare in einem Post und in Kurzform :-)
* Ich bin mir bewusst dass 1.7 bis Python 3.7 supported wird. Deshalb habe ich das Issue auch mit Milestone 1.8 getagged !
* Es war als Info / Reminder gedacht. Ich wollte es melden damit es bei Gelegenheit gecheckt wird. Ich bin ja auf 'develop' und nicht auf 1.7 branch. Und 'develop' ist in meinen Augen defacto die Vorbereitung dür das nächste Release, also 1.8. Oder liege ich da falsch ?
* Ich habe nur das websocket Plugin aktiv und das http Modul.

Hier dann mal mit ein paar Zeilen vorher damit man den ungefähren Zeitpunkt sieht:
```
2020-05-23  14:41:57 WARNING  lib.shtime          Using holidays for country 'LU', province '', state '', 1 custom holiday definitions(s) defined
2020-05-23  14:41:57 INFO     cherrypy.error      [23/May/2020:14:41:57] ENGINE Bus STARTING
2020-05-23  14:41:57 INFO     cherrypy.error      [23/May/2020:14:41:57] ENGINE Serving on http://192.168.1.149:8383
2020-05-23  14:41:57 INFO     cherrypy.error      [23/May/2020:14:41:57] ENGINE Serving on http://192.168.1.149:8384
2020-05-23  14:41:57 INFO     cherrypy.error      [23/May/2020:14:41:57] ENGINE Bus STARTED
2020-05-23  14:41:58 WARNING  lib.module          Not loading module Mqtt from section 'mqtt': Module is disabled
2020-05-23  14:41:58 WARNING  lib.item            load_itemdefinitions(): For testing the joined item structs are saved to /home/swagener/git/smarthome/etc/structs_joined.yaml
2020-05-23  14:41:59 INFO     cherrypy.access.140236092329168 192.168.1.149 - - [23/May/2020:14:41:59] "GET /api/server/status/ HTTP/1.1" 200 31 "http://192.168.1.149:8383/admin/system/config" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
2020-05-23  14:41:59 INFO     cherrypy.access.140236092329168 192.168.1.149 - - [23/May/2020:14:41:59] "GET /api/server/status/ HTTP/1.1" 200 31 "http://192.168.1.149:8383/admin/system/config" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
bin/smarthome.py:842: DeprecationWarning: CRLType has been deprecated, use CRL instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: NetscapeSPKIType has been deprecated, use NetscapeSPKI instead
  obj = getattr(module, sym)
bin/smarthome.py:842: DeprecationWarning: PKCS12Type has been deprecated, use PKCS12 instead
  obj = getattr(module, sym)
[...]
```

**Comment by msinn** [comment]
Hallo Serge,

um das Ganz in einen Kontext zu setzen:

- Python3.8 liefert Deprecated Warnungen aus, die von Vorgänger Versionen nicht angezeigt wurden.
- Die Deprecated Warnungen werden aus der Garbage Collection ausgegeben. Das bedeutet, dass die Garbage Collection auf dentsprechende Objekte, Typen, ... getroffen ist, die diese Warnung auslösen. Die Garbage Collection ist aber nur der Überbringer der schlechten Nachricht.
- In diesem Fall werden die beanstandeten Typen weder im Core noch in Plugins dirket verwendet.
- Um sich dem Thema zu nähern, muss man (wie Du es getan hast) die Auslösung eingrenzen. Der eigentliche Auslöser ist mit hoher Wahrscheinlichkeit ein Python Package welches von einem Plugin oder auch einem Modul genutzt wird.
- Wenn das Package isoliert ist, wäre zu prüfen, ob die aktuellste Version des Packages installiert ist.
- Es wäre dann evtl. sinnvoll ein Issue im plugins Repo (oder im shng Repo, falls es durch ein Modul induziert ist) ein Issue im smarthome Repo aufzumachen und Dabei das Plugin bzw. das Modul anzugeben. (In der allgemeinen Form wie Du das Issue eröffnet hast, hilft das leider nicht weiter)

Zu den obigen Meldungen: Ich kann sie in meiner Installation (Python 3.8.3 und aktueller develop Branch) nicht nachvollziehen. Ich erhalte keine Warnungen. Es muss also etwas sein, was Du installiert hast, was auf meinem System nicht vorhanden ist.

Zu ohinckels Idee: Welche Version pyopenssl hast Du denn installiert? Ich habe z.B. kein pyopenssl installiert, was erklären könnte wieso ich keine Warnungen erhalte.
