### ISSUE TITLE
Planung Releasezeitraum und Releasemanagement 

### ISSUE THREAD

**Issue by cstrassburg** [smarthomeNG/smarthome#36]
#31

[Release Management im Wiki](https://github.com/smarthomeNG/smarthome/wiki/ReleaseManagement)

**Comment by psilo909** [comment]
Major 2-3 mal im Jahr (beinhalten KERN Umbauten)
Minor: zwischendrin, max 1 zwischen Releases, beinhaltet größere Bugfixes und neue Plugins / Pluginverbesserungen 

?

**Comment by SgtSeppel** [comment]
Vorschlag klingt gut. Zu oft sollten die Releases nicht kommen, sonst wird es auf Nutzerseite schnell unübersichtlich.
Zwischen den Releases sollte genug Zeit liegen, dass die meisten Nutzer auf das neue Release migrieren.
