### ISSUE TITLE
list in backend/items.html empty after update

### ISSUE THREAD

**Issue by SimeonEhrig** [smarthomeNG/smarthome#364]
I have upgraded smarthomeNG from version `1.5.1` to `1.7.2`. In general the update worked really well and the control of the smart devices works like before. So, items and logics still work. But If I want to watch the items in the web browser via backend, I get a empty list 

![image](https://user-images.githubusercontent.com/10682583/97708274-ccf75d00-1ab8-11eb-8585-cc1f94c4e9ed.png)

The header indicates that the items were found and they still work, but the list is empty. Using the search bar as a workaround does not work either.

**Comment by msinn** [comment]
The backend plugin is deprecated. You should configure and use the admin Module of the core instead.

**Comment by SimeonEhrig** [comment]
> The backend plugin is deprecated. You should configure and use the admin Module of the core instead.

Okay, I will try it.

**Comment by SimeonEhrig** [comment]
I could fix it. I forgot to check out the new version of the `plugin` repository (it's some time ago, since I set up the system). This fixed the backend bug. I have now also switched to the admin page. Thanks for the help.
