### ISSUE TITLE
Usage statistics

### ISSUE THREAD

**Issue by SgtSeppel** [smarthomeNG/smarthome#37]
Due to the discussion about the release planning (#36) I was wondering wheter it might be a good idea to deliver a usage statistics script with shNG.

Something like
- Create a random "ID" and store it to a file
- Poll a script (on GH maybe?) and pass along shNG's version number
- Run the script on each startup

Implementation could be a plugin which gets defaultet to ON at new installations, with a comment in the plugin.conf for the user to deactivate/opt out.

That way decisions may be easier to make, like in the python version discussion.

Opinions?

**Comment by psilo909** [comment]
Für uns zwar cool aber als User möchte ich nicht, dass SH.py "nach Hause" funkt.

**Comment by bmxp** [comment]
Nee, aus Datenschutzgründen geht das gar nicht. Höchstens als neues Plugin was man als Opt-In installieren muß. Aber das wird sicher wieder keiner machen ...

**Comment by Bonze255** [comment]
Oder als opt im control center? Auf die man klicken muss ?

**Comment by psilo909** [comment]
Was ist denn der control center? Vermutlich irgendwas, was ich ohne Image nicht kenne, oder?

**Comment by Bonze255** [comment]
Jepp, eig ne schoene sache, da kann man backups/ restore der items vornehmen und als zip runter/ hochladen, und die einzelnen plugins ueber den browser neu starten ...

**Comment by cstrassburg** [comment]
Ich habe mir das mal auf dem Image angeschaut, in dem control center ist nicht viel drin. Eine Seite von Martin und ein paar Scripte (config backup/restore, restart von Diensten, git pull, reboot, upgrade, systeminfo... )

**Comment by Bonze255** [comment]
Du hast recht, war wohl schon länger  nicht mehr drin, Dienste konnte man beenden und starten.
 Auf jedenfall für den Durchschnittlichen User recht komfortabel ;)

**Comment by ohinckel** [comment]
bq. Zu Plugins habe ich da aber nichts gefunden

Kann mir vorstellen, dass Plugins garnicht neustartbar sind: die Implementierung von Plugins ist nicht standardisiert und ziemlich "flexibel". D.h. Plugin-Entwickler koennen tun, was sie wollen und SmartHome hat das nicht unter der Kontrollen um sicher sagen zu koennen, wie ein Plugin gestoppt oder gestartet wird.

Ich hatte schon mit dem Gedanken gespielt, ein Interface fuer Plugins anzubieten, in dem alle Funktionen bereitgestellt werden, die ein Plugin braucht (z.B. Scheduler-Tasks erstellen - ist etwas, was SmartHome vermutlich keinem Pugin ohne weiteres zuordnen kann um diesen Task zu entfernen, damit das Plugin von SmartHome neu gestartet werden kann).

Aber das ist ein anderes Thema und hat mit diesem eigentlich nicht viel zu tun. Trotzdem faende ich es besser, wenn Plugins ein Interface implementieren muessen (z.B. fehlt definitiv ein stop-Methode, mit der das Plugin sich stoppen kann und alles dafuer notwendige macht - ist evlt. ein erster Schrit in die Richtung, wenn man aktuell nicht so viel umbauen moechte).

**Comment by cstrassburg** [comment]
> (z.B. fehlt definitiv ein stop-Methode, mit der das Plugin sich stoppen kann und alles dafuer notwendige macht

Die ist eigentlich drin, was fehlt ist der Zwang diese zu implementieren 
`def stop(self):`

> Ich hatte schon mit dem Gedanken gespielt, ein Interface fuer Plugins anzubieten, in dem alle Funktionen bereitgestellt werden, die ein Plugin braucht
Sh.py hat schon ein paar Schwächen die wir mit der Zeit ausbügeln werden.

Ich werde ein paar Oberklassen entwerfen und mal mit einem Plugin anfangen. Aber das ist hier schon ein anderes Thema. ;-)
