### ISSUE TITLE
Introduce further Levels for debugging

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#384]
There is a need for further log levels in SmartHomeNG:

Right now the standard python log levels are defined:

* 0 - NotSet
* 10 - DEBUG
* 20 - INFO
* 30 - WARNING
* 40 - ERROR
* 50 - CRITICAL

Logging from Core e.g. should use something more important that INFO but less than WARNING. See [this Thread in KNXUF](https://knx-user-forum.de/forum/supportforen/smarthome-py/1598122-shng-1-7-2-info-statt-warnung-möglich-im-logfile)

Adding a new loglevel could be achieved with Code like this:
```
import logging

def addLoggingLevel(description, value):
    """
    Adds a new Logging level to the standard python logging

    :param description: appearance within logs SYSINFO
    :type description: string
    :param value: numeric value for the logging level
    :type value: int
    :param tocall: function name to call for a log with the given level
    :type tocall: String, optional, if not given  description will be used with lower case 

    no error checking is performed here for typos, already existing levels or functions
    """

    def logForLevel(self, message, *args, **kwargs):
        if self.isEnabledFor(value):
            self._log(value, message, args, **kwargs)
    def logToRoot(message, *args, **kwargs):
        logging.log(value, message, *args, **kwargs)

    logging.addLevelName(value, description)
    setattr(logging, description, value)
    setattr(logging.getLoggerClass(), description.lower(), logForLevel)
    setattr(logging, description.lower(), logToRoot)

addLoggingLevel('SHNGINFO', 25)
```
The start could then look like
```
2021-01-13  19:55:00 CET SHNGINFO lib.smarthome.main   --------------------   Init SmartHomeNG 1.7.2c.44ace818.develop   -------------------- -- smarthome.py:__init__:371
2021-01-13  19:55:00 CET SHNGINFO lib.smarthome.main   Running in Python interpreter 'v3.7.3 final', from directory /usr/local/smarthome -- smarthome.py:__init__:372
2021-01-13  19:55:00 CET SHNGINFO lib.smarthome.main    - on Linux-4.19.0-13-amd64-x86_64-with-debian-10.7 (pid=24438) -- smarthome.py:__init__:373
2021-01-13  19:55:00 CET WARNING  lib.smarthome.main    - Nutze Feiertage für Land 'DE', Provinz 'NI', 5 benutzerdefinierte(r) Feiertag(e) definiert -- smarthome.py:__init__:432
2021-01-13  19:55:01 CET WARNING  lib.module           Not loading module Mqtt from section 'mqtt': Module is disabled -- module.py:_load_module:230
2021-01-13  19:55:04 CET WARNING  plugins.knx          Benutze Busmonitor (L) = 'logger' -- __init__.py:__init__:140
2021-01-13  19:55:04 CET WARNING  lib.plugin           Plugin 'visu_websocket' (section 'websocket') is deprecated. Consider to use a replacement instead -- plugin.py:__init__:568
2021-01-13  19:55:10 CET WARNING  lib.plugin           Plugin section 'mylogname2' uses same class 'OperationLog' and instance 'default' as plugin section 'mylogname1' -- plugin.py:_test_duplicate_pluginconfiguration:329
2021-01-13  19:55:22 CET SHNGINFO lib.smarthome.main   --------------------   SmartHomeNG initialization finished   -------------------- -- smarthome.py:start:720

```

This way a WARNING could be preserved for something that really warns a user.

The default logging should then be configured to use new levels and upgrading a version of SHNG should then probably warn *old users* of new log levels.

**Comment by onkelandy** [comment]
Also voting vor a level DEVELOP (9) to have temporary extra verbose feedback when needed

**Comment by onkelandy** [comment]
Im Prinzip ist es nur ne Benennungsfrage. Die Abstufung des DEBUG in L1-L3 schlägt in die gleiche Kerbe.

So ein developmode könnte zB Inhalte von Variablen listen, kurzzeitig für ganz spezielle Features Details liefern, etc. Konkret denke ich an das Stateengine plugin, das per Attribut die Loglevel "aus", "Info" oder "Debug" kennt. Das Debug Log ist auch für Anwender sehr sinnvoll, weil sie dann mitbekommen, warum ein Zustand genau eingenommen und was wann berechnet wurde. Hingegen beim Testen von Features, etc. wären dann phasenweise noch mehr Logeinträge nötig, die aber den Endanwender 0 interessieren.

Ob jetzt dann der Endanwender zukünftig DEBUG_L2 sieht und man zum Entwickeln auf DEBUG stellt oder der Anwender wie gehabt DEBUG sieht und beim Entwickeln mittels DEVELOP mehr gezeigt wird, ist mehr oder weniger egal.

**Comment by msinn** [comment]
So wie ich das verstehe, suchst Du also (für das stateengine Plugin) so was wie USER_DEBUG und DEVELOPER_DEBUG

**Comment by Morg42** [comment]
Um mal noch was beizutragen:

für mich ist DEBUG ausreichend. Ich habe keinen Bedarf, bei DEBUG nochmal zu unterscheiden. Wenn der User DEBUG will, dann bekommt er das - vorgesehen ist das (aus meiner Sicht) nicht; also, DEBUG ist nicht für den Endanwender vorgesehen. INFO kann da schon reichlich sein.

Für die Start- und Stop-Meldungen könnte man noch NOTICE (z.B. als 25) definieren, wobei ich mit der WARNING kein Problem habe. Da stört mich schon eher das ERROR von cherrypy...

**Comment by onkelandy** [comment]
Ich denke, es gibt schon immer wieder Situationen, in denen Normaluser DEBUG einschalten (müssen). Gerade, wenn es um Fehlersuche geht. 
Beim Sateengine plugin ist es halt nochmals was anderes. Aber wie gesagt, wie man die Level nennt, ist ja wurscht. Drei verschiedene Debuglevel passt auch.

**Comment by msinn** [comment]
Im develop ist de level NOTICE implementiert. Der numerische Wert dazu ist entweder 29 oder 31. 

31 wird gewählt, wenn die logging.yaml nicht angepasst wird, um keine Meldungen zu unterschlagen.

**Comment by onkelandy** [comment]
Gibt es nun auch die Debug_l2 und Debug_l3? Das wäre super!
@msinn es sieht so aus als würden die aktuellen Änderungen dazu führen, dass die Logger im Admin IF nicht mehr gelistet werden können.

**Comment by msinn** [comment]
Fix ist im develop

> Gibt es nun auch die Debug_l2 und Debug_l3? Das wäre super!

Nein, im Core ist kein Bedarf und die Erweiterung um weitere Level (aktuell den Level NOTICE) wirkt auch nur im Core.

**Comment by msinn** [comment]
v1.9 is released
