### ISSUE TITLE
Add "enforce_change" to item view at backend

### ISSUE THREAD

**Issue by sisamiwe** [smarthomeNG/smarthome#389]
Hi, 

the new attribute "enforce_change" is not yet part of the attribute listing in item view of backend.
Maybe this can be added.

THX

**Comment by psilo909** [comment]
Backend Plugin or Admin Interface? Backend Plugin is deprecated

**Comment by sisamiwe** [comment]
Sorry: Admin Interface.

**Comment by msinn** [comment]
Resolution went into master with release v1.8.2
