### ISSUE TITLE
[avm plugin] Exception nach Firmware Update einer Fritz!Box

### ISSUE THREAD

**Issue by msinn** [smarthomeNG/smarthome#39]
Hi René,

ich habe eine meiner 7390 upgedated (die ohne Telefonie Nutzung). Diese Box hat jetzt die Firmware v6.51.

Seitdem habe ich im 5 Minuten Takt folgende Exception im smarthome.log:

```
2016-05-01 11:49:16 ERROR    plugins.avm_fritz_wz Method plugins.avm_fritz_wz exception: 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "/usr/local/smarthomeNG/lib/scheduler.py", line 358, in _task
    obj()
  File "/usr/local/smarthomeNG/plugins/avm/__init__.py", line 540, in _update_loop
    self._update_wan_ip_connection(item)
  File "/usr/local/smarthomeNG/plugins/avm/__init__.py", line 1556, in _update_wan_ip_connection
    item(element_xml[0].firstChild.data)
AttributeError: 'NoneType' object has no attribute 'data'
```

Diese Fritz!Box hat keine eigene WAN Verbindung. Der WAN Traffic wird über die andere Box geführt.

Das AVM Plugin ist das Aktuelle (Version 0.961)

**Comment by psilo909** [comment]
SH mal neu gestartet? ;) Ob ich im laufenden Betrieb eim FW Update mit einem Reconnect abfangen kann, wage ich zu bezweifeln.

**Comment by psilo909** [comment]
Nachtrag: "WAN Verbindung. Der WAN Traffic wird über die andere Box geführt." -> Jagst Du trotzdem WAN spezifische Items gegen die Box?

**Comment by psilo909** [comment]
Ich commite später nen Fix gegen Fehlkonfiguration ;)

"if not element_xml[0].firstChild is None:" in 4 oder 5 methoden

**Comment by msinn** [comment]
Ja, ich habe smarthome neu gestartet.

```
-> Jagst Du trotzdem WAN spezifische Items gegen die Box?
```
Du kennst mich doch. Ich mache gerne Crash-Tests 😃

**Comment by psilo909** [comment]
ok ich gehe an meinen desktop und schiebe es schnell rauf ;)

**Comment by psilo909** [comment]
https://github.com/smarthomeNG/smarthome/commit/3d0e38c4f572f02f2042d4e8070c2f333aa70528
