### ISSUE TITLE
System configuration via web interface breaks holidays.yaml

### ISSUE THREAD

**Issue by peteruhrig** [smarthomeNG/smarthome#390]
Dear all,

when I run the system configuration and remove the line about special holidays, a broken `holidays.yaml` is written.

To reproduce:
- Remove the highlighted part in the following screenshot and save:
![image](https://user-images.githubusercontent.com/19432934/106530093-f8d91300-64eb-11eb-8d9e-e356d79e1b9d.png)
- Restart smarthomeNG
--> Restart fails because the last two lines of `holidays.yaml` look like this:

```
custom:
[]
```

Best wishes,
Peter

**Comment by msinn** [comment]
custom has to be a list of stings, but you entered a dict in custom1

**Comment by peteruhrig** [comment]
I did not put anything in custom1. The highlighted dict was there from the beginning, directly after setup. When I leave it in, at least nothing breaks. When I remove it so that I have an empty field (just like for custom2 and the others), the broken holidays.yaml gets written.

**Comment by msinn** [comment]
As of today: Can't reproduce. The last line of holiday.yaml looks like this:

```
custom: []
```

which is perfectly fine and SmartHomeNG restarts as it should.

**Comment by onkelandy** [comment]
I can actually confirm Peter's problem. My holiday.yaml also has the [] in the next line and not next to "custom:"
Could it depend on some python package @msinn ? I'm using 0.16.7 ruamel

**Comment by msinn** [comment]
I am using ruaml.yaml 0.16.7 too. Which Python version are you using? I am running Python 3.8.3

**Comment by onkelandy** [comment]
Tried it on two system and had the problem on both..
System 1:
1.8.2c.119f1e0c.develop
Python: 3.8.6 final
ruamel: 0.16.7

System 2:
1.8.2d.b712cb46.develop
Python: 3.9.2 final
ruamel: 0.16.7

Also got this error after saving the changes:
```
2021-12-01  11:34:20 ERROR    lib.shyaml        YAML-file load error in /usr/local/smarthome/etc/holidays.yaml:  
while scanning a simple key
  in "<unicode string>", line 40, column 1:
    []
    ^ (line: 40)
could not find expected ':'
  in "<unicode string>", line 41, column 1:
    
    ^ (line: 41)
NOTE: Look for the error at the expected <block end>, near the second specified line number
```

**Comment by msinn** [comment]
I changed the handling the following way: 
- if the list of custom holidays is empty, the **custom** key is removed from holiday.yaml (instead of writing an empty list)
- when reading the holiday.yaml file, it is checked if the key **custom** exists. If not, the list is initialized empty

**Comment by onkelandy** [comment]
works as described on my system - maybe @peteruhrig can also test?

**Comment by msinn** [comment]
v1.9 is released
