### ISSUE TITLE
Restarting via commandline arg -r or webif breaks foreground modes (-f, -i, -d)

### ISSUE THREAD

**Issue by Morg42** [smarthomeNG/smarthome#392]
shng has a proper mechanism to work in a daemonized setup. The command line options -f and -i (and deprecated -d) all start shng not daemonizing, but staying in foreground.

The restart mechanism kills the original process from a fork, which breaks foreground modes, mainly because the original mode is not transported.

Before I start work on this, I'd like to get input if this issue is worth addressing (it is for me...).

My outline of a plan is to

1. modify the restart code in bin/smarthome.py for restarting after dependency install,
2. modify the sh.restart() code to issue an additional argument (e.g. --restart-mode=f/i/d) to transport the original mode,
3. modify the startup code to parse this argument and behave accordingly.

The first item is already done, the second and third might prove a bit more work to not break anything else.

Will this be something to be considered implementing?

**Comment by msinn** [comment]
Should be fixed by the PR of Morg42

**Comment by msinn** [comment]
Fixed with the release 1.9.1
