### ISSUE TITLE
Allow other Backup stem names

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#393]
Currently backups made via admin interface will be named ``shng_config_backup_<year>-<month>-<day>-<hour>-<minutes>.zip``

Since I have three independent installations which I support remotely from home it would be great to distinguish the backups by name. So I would suggest to add a key ``backup_stem`` to ``etc\smarthome.yaml`` that will have the default of ``shng_config_backup_`` but which could be changed to something else like ``Waldstrasse_shng_config_backup_``

**Comment by msinn** [comment]
Resolution went into master with release v1.8.2
