### ISSUE TITLE
[avm plugin] Callmonitor

### ISSUE THREAD

**Issue by msinn** [smarthomeNG/smarthome#40]
Hi René,

beim Callmonitor (Incoming) ist mir ein Verhalten aufgefallen, das das Plugin von dem Einbau der eigenen Telefonnummer nicht hatte.

Im Widget geht das Icon auf "Gespräch" (oranger abgenommener Hörer), aber die Angaben zu Namen, Zeit und Nummer bleiben unverändert auf dem alten Anruf. Das ändert sich auch nach Beendigung des Telefonats nicht. Es werden weiterhin die Daten des nun vorletzten Anrufs angezeigt.

Nach einem Neustart von smarthome.py werden die korrekten Daten über den letzen Anruf angezeigt.

**Comment by psilo909** [comment]
Was heißt "vor dem Einbau der eigenen Tel.Nr"? Hast Du nen Filter gesetzt? Passt der 100% auf das was via Telnet im Callmonitor kommt?

Nach dem Neustart initialisiert wer - wenn dus nicht cachest -  via get_calllist.

**Comment by msinn** [comment]
Ich meine bevor Du eingebaut hast, dass die eigene Telefonnummer (die angerufen wurde) als Item zur Verfügung steht. 

Die ganzen Zeilen cache = yes habe ich rausgenommen, damit das smarthome.py caching mir beim testen nicht wieder in die Suppe spuckt.

**Comment by msinn** [comment]
Ich kann das Verhalten leider nicht sicher reproduzieren. Ich melde mich, wenn ich ein reproduzierbares Verhalten habe.

**Comment by psilo909** [comment]
Ich beobachte es auch mal.. ggf acht geben wenn Du sh.py in laufenden Telefonaten beendest.. dann ergeben sich manchmal komische Konstellationen.

**Comment by msinn** [comment]
Problem ist nicht wieder aufgetreten. Deshalb mach ich mal zu.
