### ISSUE TITLE
[avm plugin] Probleme mit dem Erkennen von Devices

### ISSUE THREAD

**Issue by msinn** [smarthomeNG/smarthome#41]
Hi René,

ich hatte die schon geschrieben, dass ich mit dem Erkennen von Devices anhand der Mac Adresse Probleme hatte. Ich habe das Thema auf die Firmware Version der Box eingegrenzt.

Das Problem besteht weiterhin auf der 7390 v6.30, während die Erkennung auf der 7390 v6.51 funktioniert.

Kann ich für Dich noch irgendwas nachschauen, damit Du das besser eingrenzen kannst?

Viele Grüße
Martin

**Comment by msinn** [comment]
Hallo René,

ich habe gerade von Sandmann60 die Info bekommen, dass das ein Bug in der v6.30 Firmware ist. (bei mehr als 16 Devices)

Das ist für mich sehr ärgerlich, da die 7390 deutlich mehr als 16 Devices kennt. Das ist mein Internet Router und ich kann kein FW Update machen, da die Box vom Provider stammt.

Ich hatte bisher nur Devices probiert, die in der Heimnetz/Netzwerk Übersicht weiter hinten standen. Ich habe jetzt eines der ersten 16 Geräte genommen und damit geht es.

Damit ist das kein Issue in Deinem Plugin.

**Comment by psilo909** [comment]
Hi,

naja das würde aber mit jedem Plugin passieren.. Hoffe mal Dein Provider gibt bald die neue frei. Haben die Dir verboten die FW zu updaten? Grundlegend dachte ich, Routerzwang sei aufgehoben? Bzw. Du müsstest Dir doch ne eigene hinstellen können? Ich habe bspw. auch nicht den doofen Speedport von der TKOM gemietet sondern gleich ne FB gekauft.

VG,

René

**Comment by msinn** [comment]
In der gebrandeten Box (wilhelm.tel) ist der ganze Menüpunkt "Update" nicht vorhanden. Das letzte mal (Update auf v6.30) hat das nach der Freigabe durch AVM rund ein halbes Jahr gedauert bis der Provider das Update eingespielt hat...

**Comment by psilo909** [comment]
hmm wenn Du Zugangsdaten hast würde ich dann echt überlegen ne eigene FB zu kaufen. Zahlst Du "Leihgebühr" wie bei der TKom?
