### ISSUE TITLE
Remove lib.connection

### ISSUE THREAD

**Issue by Morg42** [smarthomeNG/smarthome#410]
After transitioning active code in core and plugins to lib.network, the lib.connection ist obsolete (concerning code checked in on GitHub / smarthomeNG) following [issue 399 @plugins](https://github.com/smarthomeNG/plugins/issues/399)

One consideration before finally removing lib.connection should be a way to warn users incorporation lib.connection in private plugins.

Options might be
- displaying a warning in AdminUI
- writing a warning to the log
- writing a warning to the console
- ...?

Removal should be planned earliest for 1.10, latest for 2.0, IMHO.

**Comment by Morg42** [comment]
Todo: check plugins before next release

**Comment by Morg42** [comment]
currently using lib.connections:

- [ ] LOGO @bmxp 
- [ ] comfoair (inactive?)

**Comment by bmxp** [comment]
LOGO might be still in use by @ivande, I have no idea about comfoair

**Comment by msinn** [comment]
Maybe you should ask in the forum and on gitter, if the two plugins are still in use (and if someone is maintaining them).

**Comment by Morg42** [comment]
Checking again, I already migrated the `monitor` functionality to lib.network, so only plugins explicitly importing lib.connection might need to be adjusted.

sv_websocket is one building its own network server from lib.connections, but as far as I recall this is deprecated...

So lib.connection could be removed at one of the next releases. The deprecation warning is already implemented for those using lib.connection in private plugins.

**Comment by msinn** [comment]
Sc_websocket ist deprecated and will be retired in v1.10. There is no need to update it. It has been replaced by the websocket module.

**Comment by msinn** [comment]
SmartHomeNG v1.9.4 has been released
