### ISSUE TITLE
Error when listing loggers in admin interface

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#411]
```
Apr 05 07:57:12 ERROR    modules.admin.api_loggers Logger Exception: dictionary changed size during iteration
Traceback (most recent call last):
  File "/usr/local/smarthome/modules/admin/api_loggers.py", line 103, in get_active_loggers
    for l in logging.Logger.manager.loggerDict:
RuntimeError: dictionary changed size during iteration
```

I am pretty sure that previously the stateengine logger (latest develop version) got listed in custom loggers. It isn't now. Maybe the reason for that is the error above? Maybe I should have waited longer before accessing the logger list after a restart?
Revisiting the page later (>5m after shng restart) doesn't bring up the error again - but also not the stateengine logger.

**Comment by msinn** [comment]
v1.9 is released
