### ISSUE TITLE
tools.dt2ts gives back wrong timestamp (in summer)

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#412]
I guess it is a daylight saving problem as it only appeared after changing time to summer time.
```
    def dt2ts(self, dt):
        return time.mktime(dt.timetuple())
```
gives back a timestamp that is 1 hour later than it should.
I guess this would be a reasonable solution?
```
    def dt2ts(self, dt):
        return dt.timestamp()
```

**Comment by msinn** [comment]
Fixed in develop

**Comment by msinn** [comment]
v1.9 is released
