### ISSUE TITLE
Longer (dict) values get cut off in admin interface

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#424]
<img width="775" alt="cutoff_dict" src="https://user-images.githubusercontent.com/7084934/138164431-b9916881-03b4-4c25-ac86-e90be8c4592a.png">
Especially the UZSU plugin demands long dict entries. It's cut off in the admin IF in all occasions (last value, current value form field, etc.)

**Comment by wvhn** [comment]
Not the length of the dict but the content is causing this problem. Some special characters like`>` and `<` need to be  escaped for a proper display.

**Comment by msinn** [comment]
Which special char are causing the cut in the example above?

**Comment by wvhn** [comment]
As of now we use only `>` and `<` in the sun events.  
see error description in knx user forum starting here:
https://knx-user-forum.de/forum/supportforen/smarthome-py/1364692-supportthread-f%C3%BCr-uzsu-plugin?p=1642235#post1642235. There is evidence that only the display in the admin interface is faulty while the Dict handling inside shNG is working properly.

**Comment by msinn** [comment]
@Onkelandy can you give more information (how the item is defined)?

For items defined as string, I have tried to reproduce the cutting of, but it works fine for me (develop branch).

I pasted a string conteining ``<`` into an item (through admin GUI):
```
{"cmd": "item", "items": [["eg.esszimmer.licht.fenster.uzsu",[MARKIEREN] {"interpolation": {"type": "none", "initialized": false, "itemtype": "num", "interval": "", "initage": ""}, "list": [{"active": true, "rrule": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU", "value": "2", "calculated": "21:30", "time": "16:30[/MARKIEREN]<sunset<21:30"}, {"active": true, "rrule": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU", "value": "0", "time": "21:35"}], "active": false, "sunrise": "06:36", "sunset": "20:13", "lastvalue": null}]]}
```

and changed the value afterwards. -> last value (Letzter Wert) showed the hole string.

**Comment by onkelandy** [comment]
Hi! The items are defined as DICT.
Indeed I had to use a html.escape(json.dumps(self._items[item])) for the plugin webif to work. Guess it will need something similar for the Admin IF.

**Comment by msinn** [comment]
It is not simple to implement a solution:

1.) escaping can only be done on Strings
2.) when converting the dict to a string (by str() or json.dumps()) and escaping that string, all quotes used by json are escaped too, so it won't work

So a solution has to identify all strings in the dict structure and escape them one by one ...

**Comment by msinn** [comment]
A crude solution could be:

- convert dict to str
- replace only ``<`` and ``>`` by ``&lt;`` and ``&gt;`` 
- convert the resulting sting to a dict by using ast.literal_eval()

But for the moment I am not sure how to do a safe unescape for that.
Only escaping would lead to ``&lt;`` and ``&gt;``  being displayed, but the information would not be cut any more.

**Comment by msinn** [comment]
Mist, die krude Version geht nicht, da json.dumps() die mühsam durch ``&lt;`` und ``&gt;`` ersetzten ``<`` und ``>`` zurückübersetzt und dann werden sie in nicht-escaped gesendet.

**Comment by msinn** [comment]
I found a way to fix it. The solution has been pushed to develop

**Comment by wvhn** [comment]
great job! Thanks!

**Comment by onkelandy** [comment]
Thanks! The current value field actually seems to work perfectly, however the previous value still has issues.
While this string within a dict is no problem 'sunrise-120m<05:30' this one still is: '06:30<sunrise<08:00'

**Comment by msinn** [comment]
Ok, then I have to make the stunt for the previous value field too.

**Comment by msinn** [comment]
I have pushed an update that does html escape for dicts and lists for last_value and previous_value too.

**Comment by onkelandy** [comment]
Everything perfect now, thx

**Comment by msinn** [comment]
v1.9 is released
