### ISSUE TITLE
f-Strings einsetzen?

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#425]
Hallo zusammen,
es gibt in Python seit einigen Versionen die Möglichkeiten f-Strings einzusetzen um damit str.format(...) zu sparen.

Leider haben die f-Strings die unschöne Eigenschaft, das sie nicht lokalisierbar sind. 

Die Frage wäre wie wir damit umgehen wollen. Grundsätzlich Logging Meldungen von Core und Plugins nur in Englisch? Dann können wir überall f-Strings einsetzen.
Oder Logging Meldungen lokalisieren z.B. in Plugins mit der zuständigen locale.yaml? Dann sollten wir f-Strings nicht einsetzen.

**Comment by psilo909** [comment]
Hmm ne ich würde Logmeldungen nicht Lokalisieren. Ne Exception wäre ja auch nur auf Englisch. 

Fehler die der Anwender bspw. in der GUI sieht natürlich schon lokalisiert. 

Aber jeder der auf Loglevel Ebene unterwegs ist, sollte ja eigentlich Englisch können?

**Comment by msinn** [comment]
Wieso kann man f-strings nicht lokalisieren?

Ich habe das im develop branch in **lib.userfunctions** bereits gemacht.

Beispiele:
```
    _logger.warning(translate('No userfunctions are loaded, nothing to reload'))

    ...

    # userlib ist die Variable, die den Modulnamen enthält
    _logger.error(translate("Reload: Userfunctions '{module}' do not exist", {'module': userlib})) 
```

Die Übersetzungen in der locale.yaml sehendafür folgendermaßen aus:
```
    "No userfunctions are loaded, nothing to reload":
        'de': "Es existieren keine Userfunctions, es gibt nichts für einen Reload"
        'en': '='

    "Reload: Userfunctions '{module}' do not exist":
        'de': "Userfunctions '{module}' existieren nicht"
        'en': '='
```

**Comment by msinn** [comment]
Nachtrag:

Natürlich geht auch sowas:

```
    _logger.info(f“… {translate(mystr)} …“)
```

**Comment by msinn** [comment]
Ich bin gerade dabei lib.scene auf Mehrsprachigkeit umzustellen. Ich habe mich entschieden nicht alle Logeinträge zu übersetzen.

Mit Übersetzung:

- critical
- error
- warning
- notice

Ohne Übersetzung:

- info
- debug

**Comment by msinn** [comment]
Gibt es dazu noch Klärungsbedarf oder können wir den Punkt zumachen?

**Comment by bmxp** [comment]
ich schaue mir mal an wie Du das gelöst hast und schliesse das hier wenn ich keinen weiteren Klärungsbedarf sehe.

**Comment by bmxp** [comment]
Ich habe mir das noch einmal angeschaut und im Prinzip ist der Vorteil der f-Strings ja das die aktuell verfügbaren Variablen direkt ersetzt werden.
Was Du in translate(txt,vars) machst hat IMHO aber nichts mit f-Strings zu tun sondern Du übergibst den zu übersetzenden Text und die zu ersetzenden Variablen in einem dict als Argumente an die translate Funktion.
Das kann auch mit str.format gemacht werden. Der Vorteil die Befüllung mit den Variablen innerhalb der translate liegt darin das Du einen Fehler ausgibst wenn eine benötigte Variable nicht vorhanden ist oder aber kein dict übergeben wurde.

Ich teile die Einschätzung das nicht alle logging Mitteilungen übersetzt werden müssen.

Für zeitkritische Abschnitte fände ich es sinnvoll die Praktiken hier https://docs.python.org/3.9/howto/logging.html#optimization zu benutzen, insbesondere auch das eventuelle Zwischenspeichern des Logging Levels isEnabledFor(). Gerade das Aufbereiten eines komplexen dict könnte auf einem schwachbrüstigen Raspi einiges an Rechenzeit konsumieren. 

Ich habe gerade keine Idee ob und wo wir dazu etwas in der Doku notieren könnten/sollten. Vorschläge?

**Comment by msinn** [comment]
> Was Du in translate(txt,vars) machst hat IMHO aber nichts mit f-Strings zu tun sondern Du übergibst den zu übersetzenden Text und die zu ersetzenden Variablen in einem dict als Argumente an die translate Funktion.

Stimmt, das zweite Beispiel von mir aber schon:
```
_logger.info(f“… {translate(mystr)} …“)
```

> Für zeitkritische Abschnitte fände ich es sinnvoll die Praktiken hier

Bei Code Optimierungen zur Geschwindigkeitssteigerung bin ich eher skeptisch. Die Diskussion hatten wir vor diversen Jahren schon mal. Am Ende der Diskussion stellte sich heraus, dass mit der dann aktuellen Python Version der nicht optimierte Code schneller war als der optimierte Code.
Das ist ein Schießen auf bewegliche Ziele, da unter der Oberfläche von Python von Release zu Release viel passiert. Da müsste man bei jeder neuen Python Version prüfen, ob die Optimierungen noch einen Vorteil bieten oder vielleicht sogar inzwischen einen Nachteil darstellen.

Die Optimierungen können auch den Supportaufwand erhöhen. Du  hattest irgendwo ``if logger.isEnabledFor()`` bereits eingebaut. Das führte zu 2 Anfragen bei mir, was das denn solle. Einer der Anfragenden fragte sogar, ob er einen PR stellen solle, um das auszubauen.

> Gerade das Aufbereiten eines komplexen dict könnte auf einem schwachbrüstigen Raspi einiges an Rechenzeit konsumieren.

Da sollten wir eher die Hardware als nicht supported klassifizieren. Solche Probleme sehe ich nur bei Raspberry PI 2 und davor. Wenn man bedenkt, dass der Raspberry PI 3 bereits vor knapp 6 Jahren erschien und es den PI 4 auch schon seit ca. 2 1/2 Jahren gibt...

Für die Nutzung von ``if logger.isEnabledFor()`` würde ich erstmal eine Guideline haben wollen, in welchen Fällen ein Problem auftaucht und wo diese Optimierung dann hilft. Erst dann hätte ich eine Idee, was man dazu in der Doku schreiben könnte.

**Comment by onkelandy** [comment]
Bin grad zufällig über das flynt Modul für Python gestoßen.. https://github.com/ikamensh/flynt
Hat das schon mal jemand getestet..? Sollen wir das im größeren Stile mal auf Plugins anwenden oder dann doch lieber nicht..?

**Comment by msinn** [comment]
Du scheinst lange Wile zu haben 😉 
Wir haben so schon mehr Themen als wir wegtragen können. Da sollten wir nicht anfangen den Code von über 100 Plugins zu modifizieren und hinterher testen ob sie noch alles tun was sie sollen.

**Comment by Morg42** [comment]
Also, wenn ich Code anpasse oder überarbeite (oder neu schreibe), und in dem Zusammenhang viele format()-Strings sehe, baue ich die meist in dem Zusammenhang eben um. Ob das jetzt per Hand, per sed, Cmd-F/R oder flynt passiert, ist letztlich relativ wurscht. In einem größeren Plugin habe ich das mit regex-Suchen/Ersetzen gemacht ;)

Eine Notwendigkeit, den gesamten Code zu durchforsten und zu überarbeiten, nur um format() durch f'' zu ersetzen, sehe ich nicht. Da gäbe es wichtigerere Dinge (generelle Codequalität, Lesbarkeit/Wartbarkeit, Dokumentation usw).

Ich würds - erstmal - lassen und bei Bedarf Zug um Zug umbauen.

**Comment by bmxp** [comment]
Also ich fände das gut, wenn wir das Ergebnis hier in der Doku irgendwo reinpacken können. Ich bin mir sonst sicher das das sondt irgendwann wieder aufpoppen wird als Unklarheit. Vermutlich im Entwicklungsteil am Besten aufgehoben. @msinn kannst Du das da mit unterbringen? Du bist da gerade am Schrauben ...?
Wenn erledigt, können wir das hier bitte schliessen

**Comment by msinn** [comment]
Die f-String Nutzung ist in den Referenzteil der Doku eingefolssen.
