### ISSUE TITLE
User defined attributes do not work any more for SHNG 1.8 and up

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#426]
Just like https://knx-user-forum.de/forum/supportforen/smarthome-py/1705683-logik-nachdimmen-von-leuchten#post1706151 show there was a breaking change introduced in 1.8 which prevents user attributes to work when included as watch items.

Furthermore the admin interface does not allow regex expressions including an attribute as described here https://www.smarthomeng.de/dev/user/beispiele/logiken/beispiel_nachdimmen.html

**Comment by msinn** [comment]
For now user defined attributes have to have a name that starts with my_ to be accepted.

For the regex expressions: It has nothing to do with the admin Interface

1. SmartHomeNG does not support regex expressions in the item definitions. Only some kind of wildcards are implemented
2. when the attribute name starts with my_ , it should work as before.

**Comment by msinn** [comment]
lib.metadata adds 'my_' attribute prefix to list of defined prefixes, so usind ``my_`` prefix works without defining it in a dummy plugin.

**Comment by msinn** [comment]
SmartHomeNG v1.9.2 with the resolution has been released
