### ISSUE TITLE
lib.network autoreconnect from plugins not working

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#427]
Issue 1 with squeezebox plugin:
Assume, at start of shng the connection to the server is possible. After the some time the connection is broken (e.g., the logitech media server is restarting). The problem is that the plugin doesn't realise that the connection is broken, meaning self._squeezebox_tcp_connection.connected() is still true. The command is sent "normally" and the autoreconnect function of the plugin doesn't trigger. The log file of lib.network states:
```
lib.network       No connection to 10.0.0.100, cannot send data b'02%3A00%3A09%3Ae1%3Ae4%3A2c time %3F\r\n'. Error: [Errno 32] Datenübergabe unterbrochen (broken pipe)
```
and there is no way to reconnect to the server except restarting shng. The lib should somehow inform the plugin that the pipe is broken and let the plugin reconnect. 

Issue 2 with knxd plugin:
Assume everything is working fine at the beginning but after some time the system where shng is running on loses the network connection temporarily. Here again the lib.network logs the same error as above and "blocks" the reconnection of the knxd plugin.

**Comment by bmxp** [comment]
Maybe it's a good idea that the creators of lib.network have a look at the problem

**Comment by Foxi352** [comment]
Hallo @Morg42 

Hab mir das mal (ganz) kurz angekuckt. Ich denke in der `def send(self, message):` sollte prinzipiell der äussere except block ungefähr folgendermassen umgeändert werden (ungetestet) :

```
except Exception as e:
    self.logger.warning(f'No connection to {self._host}, cannot send data {message}. Error: {e}')
    self._is_connected = false
    self._disconnected_callback and self._disconnected_callback(self)
    if self._autoreconnect:
        self.logger.debug(f'Autoreconnect enabled for {self._host}')
        self.connect()
    return False
```

Allerdings müsste man noch die exception number mit einem IF kontrollieren und die neuen Anweisungen nur ausführen wenn die Verbindung unterbrochen ist und nicht sonst irgendein Fehler vorliegt. Eigentlich dachte ich, dass das Empfangsthread den Verbindungsabbruch erkennen würde und reconnecten würde (falls autoreconnect gesetzt ist).

Was meinst du ?

**Comment by Morg42** [comment]
Sorry, erster PR ging gegen master, obwohl ich vorher develop ausgewählt hatte...

**Comment by Morg42** [comment]
Bin von Foxis Vorschlag abgewichen:
- 1. ausdrücklich auf broken pipe (= remote disconnect) prüfen, dann entsprechend behandeln wie vorgeschlagen
- 2. andere Fehler (unbekannt, keine "richtige" Behandlung bekannt) loggen und Exception werfen, damit ggf. ein Debugging möglich ist

**Comment by Foxi352** [comment]
Naja, du bist nicht wirklich abgeweicht :-) Ich schrieb ja "Allerdings müsste man noch die exception number mit einem IF kontrollieren und die neuen Anweisungen nur ausführen wenn die Verbindung unterbrochen ist und nicht sonst irgendein Fehler vorliegt.". Irgendwie ist es je genau das was du getan hast. Für mich jedenfalls sehr gut so wie es ist. Mal schauen ob @onkelandy nach den Tests bestätigen kann, dass es so funzt ... 

Danke @Morg42 !!

**Comment by msinn** [comment]
v1.9 is released
