### ISSUE TITLE
Mehrfach Zuweisung von 1-Wire Sensoren auf Items

### ISSUE THREAD

**Issue by cstrassburg** [smarthomeNG/smarthome#43]
Siehe:
https://knx-user-forum.de/forum/supportforen/smarthome-py/944688-problem-beim-auslesen-eines-einzelnen-1wire-sensors

Spricht etwas dagegen die Werte von 1-Wire Sensoren auf mehrere Items zu konfigurieren? 
Würde ich sonst als eine Erweiterung des onewire Plugins sehen.
Ob das Sinn macht zwei mal die gleichen Werte zu haben ist ein anderes Thema. Wenn das Plugin es aber zuweist, hat man eine Supportanfrage weniger.

**Comment by bmxp** [comment]
Nein, ich denke das ist ein Bug...

**Comment by cstrassburg** [comment]
Ich habe einen Fix für diesen Bug gemacht: branch:  hotfix_1w_#43 
Kann das bitte jemand testen.

**Comment by psilo909** [comment]
habe leider kein 1wire. vielleicht sollten wir die bitte ins forum posten?

**Comment by msinn** [comment]
@Foxi352 Du hast anscheinend das OneWire Plugin im Einsatz. Kannst Du den Fix im branch **hotfix_1w_#43** testen?

Ich würde gerne den Fix übernehmen oder verwerfen, damit wir den Branch loswerden.

**Comment by Foxi352** [comment]
Mach ich. Werd mich hier melden...

**Comment by Foxi352** [comment]
Rebasen oder mergen war nicht so einfach möglich da inzwischen zuviele Änderungen an der Datei vorgenommen wurden. Ich hab den Fix deshalb bei mir manuell nochmal in die aktuelle dev eingepflegt. Der Fix macht, soweit ich das in de rkurzen Zeit feststellen kann, an sich einfach nichts, weder positiv noch negativ. Das "Problem" wird nicht gelöst.

Ich hab mir den Sourcecode mal angesehen, und das Problem liegt IMHO schon in der ```parse_item(self, item)```.

```
        if addr in table:
            table[addr][key] = {'item': item, 'path': path}
        else:
            table[addr] = {key: {'item': item, 'path': path}}
```

Wenn Item mit der gleichen OneWire Adresse wie ein anderes auftaucht wird in der Tabelle einfach das erste Item durch das letzte ersetzt. Will heissen pro 1-Wire Adresse wird immer das zuletzt eingelesene Item das diese Adresse enthält behalten. (Key ist einfach nicht der Sensortyp, also T für Temperatur z.B.)

**Comment by msinn** [comment]
Aus Deinem Feedback schließe ich, dass wir den Branch löschen können, unabhängig davon wie wir mit diesem Issue umgehen?

**Comment by Foxi352** [comment]
Genau. Ich mache die MacOS Änderungen erstmal damit wir den OSX branch im shng löschen können, danach schaue ich mir dieses Issue mal an und ob der Aufwand sich lohnt. Es wird wohl eher selten sein, dass jemand den gleichen Sensor in mehreren Items nutzt.

**Comment by msinn** [comment]
Zumal die Nutzung in mehreren Items über
- eval / eval_trigger
- on_update / on_change

möglich ist.

**Comment by bmxp** [comment]
Man muß halt die Items speichern als [ item: ow-id, ... ] und nicht die ow-id und danach das item suchen, dann klappt das auch. Ich habe bei mir Onewire nicht mehr mit USB & Co laufen, hier steht ein Wiregate und zu Hause ist ein natives KNX Bastelmodul im Einsatz.

**Comment by Foxi352** [comment]
Oder die items als array unter der ow-id speichern. Aber egal wie, est ist relativ viel umzubauen um wieder potentiell Bugs in etwas stabiles reinzubringen. Deshalb frage ich mich halt, ob der Aufwand die Vorteile überwiegt. Und vor allem: Wer nutzt sowas, und wenn dann hat er ja schon Alternativen wie @msinn schon treffend beschrieben hat.

Ehrlich gesagt, momentan bin ich eher dafür das Issue als wontfix zu schliessen und die Sache zu belassen wie es ist.

**Comment by msinn** [comment]
Since we don't have a maintainer right now and there are work arounds, I added the label **wontfix**
