### ISSUE TITLE
"NaN" item value problems (with database plugin and Admin IF)

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#430]
My KNX actor sends as DPT 14 "nan" instead of a real float value (as there is no value available). It seems that "nan" is a valid num value in python and so I think the value is fine for num items in shng. It is not "None" but "nan" indeed.

Problem 1: 
Such an item having the value set to "nan" can't be accessed in the Admin IF. It is listed in the item tree but clicking on it creates an empty preview (as if the item does not exist). If the value is changed to a real number the problem exists because nan is still the "previous value". After 3 updates with real values the item is shown again. So "nan" in one of the three values (current, last, prev) means a problem.

Problem 2: 
When writing such an item into the database I receive this error: ('val_str', None), ('val_num', nan), ('val_bool', 1), ('duration', 346791), ('changed', 1637828068371)])): nan can not be used with MySQL

Not sure what should happen with such a value. It somehow makes sense to stick to the "nan" value but prevent writing that to the database? Would be nice to fix the issue for the Admin IF, for sure. Thx!

**Comment by msinn** [comment]
NaN is defined though IEEE 754 (siehe https://de.wikipedia.org/wiki/IEEE_754) for float values, but:
- SmartHomeNG does non support NaN (Not a Number) for Item type **num**. So the value shouldn't be in the item in the first place
- As you write, MySQL, doesn't seem to support NaN either

The solution would be to keep a value of NaN out of num-type items in SmartHomeNG.
The Warning your get with the database plugin and the Admin GUI are follow up problems of having a a not supported value in SmartHomeNG.

**Comment by onkelandy** [comment]
So in the end the best idea might be to check in the item casting if it's nan and if so convert it to None..?

**Comment by bmxp** [comment]
No, the best idea will be to just suppress the NaN before it enters the items value. It is of no use for you, especially with an energy meter.

**Comment by msinn** [comment]
Since NaN (Not-a-Number) is not supported for numbers in SmartHomeNG there is nothing to fix in the core. It has to be ensured, that this value isn't assigned as an item value by logics or plugins.

For this reason I would close this issue, if no objections are raised.

**Comment by onkelandy** [comment]
You don't like the idea to convert NaN to None for num items in item.py for example?

**Comment by msinn** [comment]
No, None is not supported by SmartHomeNG either.

Btw.: What would it be good for? For what would you need that value anyhow?

**Comment by onkelandy** [comment]
To prevent the mentioned issues. I'll try a "manual" conversion with an eval then to fix the problem with the KNX device then..

**Comment by msinn** [comment]
I don't understand. If NaN is prevented to enter SmartHomeNG there is no issue, or?

Converting it to None would to no good. Since the value of an Item is internally handled as a string, None is converted to an empty sting, which is converted to 0 for numeric items. And having a value of 0 wouldn't do you any good in your case.

The only way would be, to modify the knx plugin to ignore received NaN values (and log a warning). But that would be an issue for the knx plugin, not the core.

**Comment by bmxp** [comment]
I have implemented a check for a NaN in datapoint 14 within knx plugin. It will not enter the items value this way. If needed we can extend this to other datapoint types.
If it works for you @onkelandy you might want to close this issue

**Comment by onkelandy** [comment]
Thanks, knx seems to work.
One could still "eliminate" an item in the Admin IF by assigning nan to a value via visu, cli or AdminIF - but well, you get what you deserve.

**Comment by msinn** [comment]
What do you mean by "eliminate"?

Btw.: How do you assign nan to a numeric value through the AdminIF? If I try, I get an error dialog.

**Comment by onkelandy** [comment]
You are right.. I did it with the CLI then...
Eliminate means this:
<img width="810" alt="Screenshot 2021-12-28 at 08 51 04" src="https://user-images.githubusercontent.com/7084934/147542243-4b73b1e2-d63f-4d66-bbba-00e6b88d956a.png">

This is shown although the item (with nan value) is selected in the tree. Stays like that until all possible values (prev, etc.) don't have nan anymore.
