### ISSUE TITLE
Update dateutil

### ISSUE THREAD

**Issue by Bonze255** [smarthomeNG/smarthome#44]
Newest version 2.5 , used version 2.0
Lib/3rd/dateutil

**Comment by psilo909** [comment]
führt bei mir schonmal direkt zu einem
Traceback (most recent call last):
  File "/volume1/python/smarthome/bin/smarthome.py", line 60, in <module>
    from dateutil.tz import gettz
  File "/volume1/python/smarthome/lib/3rd/dateutil/tz.py", line 78
    `self._name`,
    ^
SyntaxError: invalid syntax

**Comment by psilo909** [comment]
zudem sollte die lizenz geprüft werden

__license__ = "PSF License"
=>
__license__ = "Simplified BSD"

**Comment by psilo909** [comment]
kann es sein, dass nur 2.0 auf py3 portiert wurde?
https://pypi.python.org/pypi/python-dateutil

**Comment by Bonze255** [comment]
Da steht doch bei 2.5 unterstuetzung bis 3.5? Oder seh ich das falsch ?

**Comment by psilo909** [comment]
wo liest du das? ich sehe zwar categories, aber nichts von konkreter unterstützung. meines wissens ist der fehler der bei mir gerade geworfen wurden auf 2er syntax zurückzuführen

**Comment by Bonze255** [comment]
Mh dann tut mir das leid, wusste ich nich ... Dachte wenn wir smarthome aktualisieren, sollten die externen sachen auch aktuell sein ..

**Comment by psilo909** [comment]
man könnte es auch selber umschreiben, so viel code ists ja nicht und man hat ja das 2.0er.. aber fände es besser wenn die 3rd party lib extern gebaut bleibt..

bin jetzt auch nicht mega py experte.. kann sich ja jemand mit mehr einblick nochmal ansehen

**Comment by psilo909** [comment]
bei ubuntu schreiben sie was von 2.4.2: http://www.ubuntuupdates.org/package/core/xenial/universe/base/python3-dateutil

**Comment by psilo909** [comment]
kracht aber gleich wieder wegen  `self._name` vs  repr(self._name),

**Comment by msinn** [comment]
@Bonze255: Welche Vorteile bietet der Einsatz von v2.5 denn gegenüber v2.0?

**Comment by Bonze255** [comment]
ausser bugfixes keine, 
dachte nur man sollte vl auf den neusten Stand updaten....
