### ISSUE TITLE
Relative Items using sh..self can not be addressed directly in eval expressions

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#481]
This was most likely never an issue but now as user functions are available it might be useful to send the current item itself to a user function such as
```
uf.bla.bla(sh..self)
```

This currently gets "expanded" to sh.itemname.self instead of sh.itemname.
It works well with sh..self.property.whatever but not without additional .property after .self

Only workaround currently is to use sh..self.property.path and use return_item in the user function. However, a direct "sending" of the item itself would be helpful.

**Comment by msinn** [comment]
Fixed with commit https://github.com/smarthomeNG/smarthome/commit/aa385020fe327cc0f34660ada28389b449feeadb

**Comment by msinn** [comment]
SmartHomeNG v1.9.2 with the resolution has been released
