### ISSUE TITLE
evaluate eval when triggered via eval_trigger only

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#483]
There is the wish to change items having an eval attribute manually - without evaluating the eval expression.
https://knx-user-forum.de/forum/supportforen/smarthome-py/1748372-eval-%C3%BCberschreiben-userfunktion-flexibler/

Though this can be done using if/else there are different ideas to make it more intuitive and easy to use
Different ideas:
- simple eval_on_trigger_only: True/False -> if attribute does not exist this should be False by default to keep existing behaviour
- eval_calc_by using a list of all trigger_by variations (very specific and detailed, not very userfriendly):
   - onchange (mit der Möglichkeit, auch genauer zu spezifizieren, z.B. onchange:Item1)
   - item1 (zB ident wie in eval_trigger)
   - Database:init
   - ...
 - a parameter in the eval function after "," maybe just True or False (similar to eval_on_trigger_only)
 - have a new eval attribute called eval_on_trigger or similar that only evaluates when item was triggered by eval_trigger items

**Comment by Tom-Bom-badil** [comment]
+1

IMHO a new attribute `eval_on_trigger_only: True/False` would be easiest to implement (likely just a few lines of code), with best backwards compatibility.

/tom

**Comment by Morg42** [comment]
eval_on_trigger_only is implemented now
