### ISSUE TITLE
lib.network: KNX plugin: Thread can only be started once

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#494]
Not totally sure what leads to that error.. maybe we can at least catch the error in a nice error message?
```
Jun 07 00:15:51 ERROR    KNX poll jalousien.og.westen_fluegel.hoehe Method KNX poll jalousien.og.westen_fluegel.hoehe exception: threads can only be started once
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 659, in _task
    obj(**value)
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 252, in _poll
    self.groupread(kwargs['ga'])
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 243, in groupread
    self._send(pkt)
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 191, in _send
    self._client.send(send)
  File "/usr/local/smarthome/lib/network.py", line 680, in send
    self.connect()
  File "/usr/local/smarthome/lib/network.py", line 650, in connect
    self.__connect_thread.start()
  File "/usr/lib/python3.9/threading.py", line 869, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```

**Comment by bmxp** [comment]
Did you get this error again?

**Comment by msinn** [comment]
Is this issue still relevant?

**Comment by Morg42** [comment]
Catching the error is trivial (enclosing the thread.start-call in try..except), but I'd like to find out the reason for multiple starts. This might be a timing problem on short interval disconnects and sends or restarts (via adminUI or stopping and starting on the console?)

Also see gitter ;)

**Comment by Morg42** [comment]
Found 2 occurrences on 2022-02-15, but not anymore since. Always current master version

**Comment by onkelandy** [comment]
Currently can't reproduce the issue with latest develop.. not sure if it's fixed..?

**Comment by msinn** [comment]
I am going to close the issue as resolved. If it should happen again, the issue can be reopened.

**Comment by Morg42** [comment]
Its plain to see that two KNX poll requests are submitted at "the same time" (at least inside the same second as the whole "incident") - both requests initiate autoreconnect, trigger connect, trigger connection_cycle_start. 

Maybe switching from a locking flag to using "real" locks might solve this, maybe just try/excepting the thread start call might achieve similar results.

I'll take another look into lib.network.

(I'm wondering why the connection is dropped in the first place...?)

**Comment by Morg42** [comment]
Proposed fix https://github.com/smarthomeNG/smarthome/pull/543

**Comment by Morg42** [comment]
As long as no further negative feedback is given, I'll close this as resolved.

**Comment by onkelandy** [comment]
Hm, didn't we have to revert the fix? Don't think this issue is really fixed.. Let me know, we close it again if I'm wrong ;)

**Comment by Morg42** [comment]
those who (still) have the issue, please test if the fix works for you

**Comment by onkelandy** [comment]
with the latest commit I think this issue is gone..let's test some more days/weeks and then close. Thx
