### ISSUE TITLE
Multiple Log entries created due to multiple event listener

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#496]
This issue is a reminder for discussion thread [Widget status.log: Mehrfache identische Einträge](https://knx-user-forum.de/forum/supportforen/smartvisu/1779494-widget-status-log-mehrfache-identische-einträge) in KNX User Forum.

The driver side of SmartVISU was reviewed by @wvhn and found that the multiple log entries are caused SmartHomeNG

@aschwith examined the problem and pushed a [fix into develop](https://github.com/smarthomeNG/smarthome/commit/6a0c2f00ac508a9b87e05675e691fe093a6f8f5b) which is supposed to fix the multiple log entries.

However @onkelandy reports further problem which might have a total different cause.

It would be great to have a review from @msinn here.

**Comment by msinn** [comment]
The fix of @aschwith is included in the v1.9.3 master.
Can this issue be closed or are there any other reports with v1.9.3?

> However @onkelandy reports further problem which might have a total different cause.

This is so general, that I can't use it to hunt a bug, that maybe still exists.

@wvhn Are there still multiple entries with v1.9.3?

**Comment by wvhn** [comment]
I haven't seen the multiple log entries any more after the fix.

**Comment by aschwith** [comment]
Neither have I. From my perspective, this issue can be closed.
