### ISSUE TITLE
extend websocket protocol for series

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#502]
Plots in SmartVISU show time series of SHNG stored in database. To compare different times for the same item it would be needed to extend the websocket protocol to be able to receive different time slices for the same item.

**Comment by wvhn** [comment]
The same item can be subscibed at shNG mutliple times with different durations. I am working on the plot widget to allow this. A websocket protocol extension is not needed.

**Comment by bmxp** [comment]
Ok, then we can close this issue :-)
