### ISSUE TITLE
implement suspend/resume for plugins

### ISSUE THREAD

**Issue by Morg42** [smarthomeNG/smarthome#529]
Feature request by bmxp:

> Would you please be so kind to include a kind of suspend() and activate() function within your thoughts?
> There are plugins that need a suspend sometimes, just think of receivers that are switch controlled and are offline suddenly. One would like to not have a couple of errors within the logs.
> When you rework the plugin please have this in mind....
> ---
> I think it is not. suspend() means the plugin will neither take action nor respond but still has the ability to listen to the changes for items etc. Its just not querying actively.
>
> stop and run normally will also end the plugins thread I think which is not wanted
> ---
> Imagine knx as readonly. It listens but does not take action.
> Or russound: It listens to the receiver but gives no commands and thus does not raise errors, but will detect when items change that should probably be sent after plugin is not suspended any more
>

@bmxp : Please supply precise instructions, what may/may not happen during suspend?

**Comment by bmxp** [comment]
Any plugin may itself decide what to do and what not. In general being suspendend should mean "do not take action towards any item or logic but keep an eye on what's going on and care for internal records"

**Comment by msinn** [comment]
One assumption in the feature request is false. The plugin thread is neither started by run() nor killed by stop().

run() and stop() should only tell the plugin to start or end processing.

All plugin threads are started before the run() method of the first plugin is called. The thread of a plugin is stopped only, when the unload_plugin() method in lib.plugin is called with the config-name of the plugin as a parameter or when SmartHomeNG is terminating.

**Comment by Morg42** [comment]
@bmxp: so if a suspended plugin receives a message, e.g. knx receives a telegram setting 1/3/4 from 0 to 1, it should not change any associated items. After resuming, the internal cache of the plugin might be updated (if present), but the state of any associated item is ... compromised; restarting shng with cache or database enabled might then cause switch actions to be sent to the knx network.

To be honest, stopping the plugin and restarting it later will have more or less the same effect...

resp. your russound example: you would have to implement a plugin-internal (item) cache to store all "suspended data" occurrences and "replay" this later. Implementing this might be relatively easy, but replaying all missed changes in rapid succession might even have more severe consequences....

I understand the idea to stop plugins from querying (thus creating errors for non-connected devices).

This might easily be circumvented by a simple member variable besides `self.alive`, e.g. `self.active`. This, set to False, could prevent / skip any network requests. That would leave open the question on how to set/unset it. Accessing it via the webif everytime I switch on/off my AV receiver seems unpractical.

Possibly the plugin could check for a "control item" (fixed item path or configured via plugin.yaml), and before each (network) action it queries the item, just like `self.active` in the previous example.

**Comment by Morg42** [comment]
(esp. at @bmxp ) If the actual functionality is described, i.e.
- what may the plugin do in suspended
- what must it not do in suspended
- how should it behave in not explicitly specified situations (e.g., "default behaviour")

I could implement this for the smartplugin class, trying to find a way to make it "not break" anything (at least too much ;) ).

Switching would be via a class member, optionally you could set an item via plugin function or plugin config which works as a switch (see previous comment).

But frankly, as I don't see added value, I will not invest if the requirements are not described in detail :)

**Comment by Morg42** [comment]
Im sdp als umfangreichem Framework ist das mittlerweile enthalten und nutzbar, steuerbar über ein Item. Suspend (dort: "standby") heißt, dass die (Netzwerk)Verbindungen geschlossen werden und beim Verlassen des Standby wieder geöffnet.

Für das "reguläre" SmartPlugin ist eine generische Implementation in der Plugin-Klasse wenig hilfreich, da die meisten Methoden, die angepasst werden müssen (__init__, run, send, connect usw), alle nicht existieren und erst vom Plugin-Autor geschrieben werden. Insofern müsste der jeweilige Plugin-Autor das im jeweiligen Code selbst implementieren. Aus dem gleichen Grund ist auch der (schon begonnene...) Versuch, das im Core abzubilden, hinfällig. Ein "hartes" stop/start ist bei restartable-Plugins relativ problemlos.

Vielleicht kann sdp dort als Vorlage bzw. Anregung dienen.

@bmxp Hilft dir das? Brauchst du noch weitere Infos oder Sonstiges? Ansonsten würde ich empfehlen, das hier zu schließen.

**Comment by bmxp** [comment]
Naja ich bin schon der Meinung das Suspend und Resume Funktionen auch im Smartplugin sinnvoll sind. Sie müssen ja nicht implementiert werden sondern können als pure Funktionen dienen. Aber mit der Sicherheit das sie für jedes Plugin aufgerufen werden können. Da ich aktuell aber keine Zeit für solche Arbeit sehe würde ich das auf eine zukünftige Version verschieben und in der Zwischenzeit für das Plugin was es betreffen würde einfach was implementieren wenn wieder etwas Luft ist

**Comment by Morg42** [comment]
Ich sage nicht, dass es nicht sinnvoll wäre. Man kann die API (zwei Funktionen und eine Variable) in smartplugin.py einbauen - aber die eigentliche Implementierung muss für jedes Plugin einzeln und jedesmal von Neuem erfolgen. 

Mindestens run, connect, send und update_item müssen angepasst werden, wenn das funktionieren soll, und die schreibt der Plugin_Autor selber.

Wenn ich die Idee ablehnen würde, hätte ich es ja nicht implementiert 😉

**Comment by bmxp** [comment]
Für das knx nicht, das war das [Russound Plugin ](https://knx-user-forum.de/forum/supportforen/smarthome-py/1795133-shng-st%C3%BCrzt-ab-worker-threads-error-modules-websocket-update_item?p=1804829#post1804829)
