### ISSUE TITLE
Fehlerhafte Onewire-Werte

### ISSUE THREAD

**Issue by pfischi** [smarthomeNG/smarthome#54]
Hi,

eine Sache bei der Verarbeitung von Onewire-Sensordaten ist mir aufegfallen, die ich bisher durch manuelle Anpassungen umgangen habe. Jetzt wird es Zeit das ins Repo zu holen.

Bei default-Einstellungen werden bei mir reproduzierbar falsche Werte (vor allem bei Feuchtigkeutssensoren) in das entsprechende Item geschrieben. Als Beispiel:

30% Luftfeuchte im sh-Item, 38% per Abfrage auf der owserver http-Oberfläche. Nach stundenlangen Ausprobieren habe ich den starken Verdacht, das es ein Timing-Promblem beim Pollen das Onewire-Bus ist. Setze ich im Onewire-Plugin-Code ein Sleep von 1sek zwischen der Verarbeitung der einzelnen Werte des Busses, tritt dieser Fehler nicht auf.

Am Onewire-Bus hängen 8-10 Sensoren, der Fehler ist bei mir reproduzierbar.

Gruss,

Stefan

**Comment by JanT112** [comment]
Hallo Stefan,

sind die falsche Werte Ausreißer oder liegen die gelesene Werte kontinuierlich daneben? Mit welcher Intervall liest Du Werte? 

Ich betreibe mehr als 100 Sensoradressen über 2x ow Plugin (cycle=13 für ein par wenige Sensoren, cycle=293 für den rest), allerdings mit Wiregate als owserver und kaum parasitär versorgte Sensoren. Dein Fehlerbeschreibung kann ich nicht nachvollziehen. Ausreißer kriege ich wenn ich die cycle-zeit zu weit runtersetze - als erstes an "durchwachsene" Busse. Die Item-Werte hast Du mit den uncached-Werte vom owserver verglichen?

Ein Sleep zu sezten ist ungunstig bei vielen Sensoren, da die effektive cycle-Zeit damit noch höher wird - es sei dem die cycle-Zeit kann mit ein Sleep-Patch deutlich heruntergesetzt werden.

Viele Grüße,

Jan

**Comment by bmxp** [comment]
@pfischi Was genau hast Du denn geändert?

**Comment by bmxp** [comment]
Der ursprüngliche Grund des Issues konnte auf einen vermutlich defekten Sensor zurückgeführt werden. Daher schließen wir das hier mal.
