### ISSUE TITLE
Issues with (re)loading logics from the editor page of the admin gui

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#552]
```

Apr 29 21:31:53 ERROR    lib.logic         Exception: invalid syntax (squeezebox.py, line 65)
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/logic.py", line 1253, in _generate_bytecode
    self._bytecode = compile(code, self._pathname, 'exec')
  File "/usr/local/smarthome/logics/squeezebox.py", line 65
    sh.squeezebox_wc.control.volume_fading.fade(sh..self.goal(), 5, 0.5)
                                                   ^
SyntaxError: invalid syntax
```
The sh.. throws an error, no matter if .self or sh..goal() is used. The resulting item exists and the eval syntax checker works. When I use the full path it also works.

The logic then (correctly) gets into the "not loaded" section in the Admin Interface. As soon as I change the "wrong" parts and want to reload the logic I get this error in the admin interface:
Error: No logic with name "undefined" found. The log says: WARNING  modules.admin.logics REST_dispatch_execute: squeezebox: 'name'

I realize that this behaviour is somehow correct.. as the logic isn't added yet but maybe in the admin interface the button could then be greyed out or changed to "reload and add"?

After going back to the overview and clicking on "+" everything is fine again.

**Comment by msinn** [comment]
You can't use relative Item References in Logics. (Relative to what???)

> I realize that this behaviour is somehow correct.. as the logic isn't added yet but maybe in the admin interface the button could then be greyed out or changed to "reload and add"?

That can't be done without knowing, that the logic contains a fatal error and that is only detected by trying to load that logic.

**Comment by onkelandy** [comment]
Not sure what I was expecting regarding relative items in logics (I know what I expected but it's bullshit of course)
Regarding the other issue..
When I am in the logic editor and f** up the code and I save and reload the logic gets checked and unloaded. However, I don't get any feedback on that in the admin interface. I can still try to run the logic, etc. The feedback is only in the log but it would be very helpful to get that in the interface.

Another usability improvement would be to have a different button in a logic that was disabled. Let's say I change I messed up logic. Right now I have to save it, go back to the overview and add it manually. Instead of "save and reload" it would be great to have a button "save and add".

**Comment by msinn** [comment]
I have already an entry in my backlog to be able to load a logic that has been unloaded due to a fatal error from the editor screen.

For the usability improvement:
> Another usability improvement would be to have a different button in a logic that was disabled.

When a logic is disabled (paused), the Icon of the button changes from "pause" to "play" to reflect the actual status.

**Comment by msinn** [comment]
Changed title of issue to reflect the issue discussed here.

**Comment by onkelandy** [comment]
Nach dem Update gab es beim Start einen Fehler wegen der fehlenden admin.yaml Datei. Hab die aus dem test Ordner mal ins etc Verzeichnis kopiert, dann startet es.

Der Rest sieht nun sehr gut aus. Alert wird angezeigt bei einer kaputten Logik und nach dem Fixen und nun auch ein Neuladen möglich, top.

**Comment by msinn** [comment]
Die admin.yaml ist nun auch da (wird, falls sie nicht existiert, von der admin.yaml.default kopiert.
