### ISSUE TITLE
Websocket crashed

### ISSUE THREAD

**Issue by mm2706** [smarthomeNG/smarthome#580]
Websocket crashed wenn ein Reconnect von einem iPhone passiert. Passiert nur bei TLS-Verbindungen

>2023-08-20`  16:40:07 ERROR    websockets.server   connection handler failed
> Traceback (most recent call last):
>   File "/home/smarthome/.local/lib/python3.11/site-packages/websockets/legacy/server.py", line 240, in handler
>     await self.ws_handler(self)
>   File "/home/smarthome/.local/lib/python3.11/site-packages/websockets/legacy/server.py", line 1186, in _ws_handler
>     return await cast(
>            ^^^^^^^^^^^
>   File "/usr/local/smarthome/modules/websocket/__init__.py", line 298, in handle_new_connection
>     await self.register(websocket)
>   File "/usr/local/smarthome/modules/websocket/__init__.py", line 323, in register
>     await self.log_connection_event('added', websocket)
>   File "/usr/local/smarthome/modules/websocket/__init__.py", line 349, in log_connection_event
>     self.logger.dbghigh(f"- user: {self.client_address(u)}    path: {u.path}    secure: {u.secure}    port: {u.port}")
>                                    ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/smarthome/modules/websocket/__init__.py", line 356, in client_address
>     if websocket.remote_address is None:
>        ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/smarthome/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 421, in remote_address
>     return transport.get_extra_info("peername")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/sslproto.py", line 91, in get_extra_info
>     return self._ssl_protocol._get_extra_info(name, default)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute '_get_extra_info'

**Comment by msinn** [comment]
Vorab: Aus dem Dump kann ich bereits sehen, dass Du Python 3.11 einsetzt. Es gibt bisher keine Version von SmartHomeNG, die Python 3.11 offiziell unterstützt (siehe [Dokumentation](https://docs.smarthomeng.de/installation/anforderungen.html#python-versionen)) Bisher werden für Releases Python Versionen bis maximal 3.9 offiziell unterstützt. SmartHomeNG 1.10 wird Python 3.10 unterstützen.

Generell brauche ich, um eine solche Exception einordnen zu können, außer der eingesetzten Python Version sowie der SmartHomeNG Version, auch die Versionen der installierten Python Packages, die an der websocket Kommunikation beteiligt sind:
- asynicio
- websockets
- cryptography (oder des sonst eingesetzten Packages für ssl Unterstützung)

**Comment by mm2706** [comment]
Danke für den Hinweis, habe ein Downgrade auf  Python auf 3.9 vorgenommen. Jetzt funktioniert es ohne Probleme.

Kurz zum Hintergrund, ich hatte Debian 12 verwendet und alles nach der Anleitung installiert.

**Comment by msinn** [comment]
Es wäre für mich trotzdem hilfreich, wenn Du die verwendeten Versionen der oben genannten Packages nennen könntest, mit denen unter Python 3.11 das Problem auftrat.

**Comment by mm2706** [comment]
Habe nochmal die alte VM wiederhergestellt, hoffe das passt so. 

![Bildschirmfoto 2023-08-27 um 20 35 41](https://github.com/smarthomeNG/smarthome/assets/34599725/c0a9cdf7-68d5-48a0-ab7c-00e8760813ca)
![Bildschirmfoto 2023-08-27 um 20 36 03](https://github.com/smarthomeNG/smarthome/assets/34599725/e05fc4a1-5349-4c41-8071-cbc2624f4797)
![Bildschirmfoto 2023-08-27 um 20 39 56](https://github.com/smarthomeNG/smarthome/assets/34599725/54a222c7-78f3-402a-8732-a20cc4178871)
