### ISSUE TITLE
Lizenzheader vereinheitlichen

### ISSUE THREAD

**Issue by encbladexp** [smarthomeNG/smarthome#59]
Gegenwärtig haben wir unterschiedliche Lizenzheader, dies führt zu folgenden Situationen:
- Ungültige Einschränkungen für die GPL Version (z.B. AVM Plugin)
- In den Core Files wird nur der aktuelle Main Author genannt, nicht die Leute mit Contributions.

Eine mögliche Lösung hierfür:
- [ ] Lizenzheader Projektweit einheitlich
- [ ] Author der Projektdateien ist immer "The Smarthome.py Team"
- [ ] AUTHORS Datei im Projektroot hat eine Liste der Authoren
- [ ] Es werden nur noch neue Projektdateien gemerged wenn diese sich an den Standard halten (d.h. Erwähnung dieses Verfahrens im Contribution Guide)

Auf diese Art können wir Lizenzwildwuchs vermeiden, und haben alles an einer zentralen Stelle dokumentiert.

**Comment by psilo909** [comment]
Vorschlag für den konkreten Header?

**Comment by encbladexp** [comment]
Ich mach keine PRs mehr ohne zu wissen was gewünscht ist. Kostet mich nur Zeit und ich schreibe ständig Dinge neu.

**Comment by psilo909** [comment]
Du musst ja keinen PR machen, kannst ja von irgendwo ein Beispiel zitieren ;)

**Comment by encbladexp** [comment]
```
# -*- coding: utf-8 -*-
"""
    inyoka.portal.views
    ~~~~~~~~~~~~~~~~~~~

    All views for the portal including the user control panel, private messages,
    static pages and the login/register.

    :copyright: (c) 2007-2016 by the Inyoka Team, see AUTHORS for more details.
    :license: BSD, see LICENSE for more details.
"""
```
Von diesem besagten anderen Projekt. Es ist noch ein altes Python 2 Projekt.

**Comment by ohinckel** [comment]
Vorschlag finde ich gut, kurz und knapp. Koennte dan so ausehen:

```
"""
    This file is part of SmartHome.py - https://github.com/smarthomeNG/smarthome

    SmartHome.py is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SmartHome.py is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    :copyright: (c) 2013 - 2016 Marcus Popp <marcus@popp.mx>
    :copyright: (c) 2016 - 2016 The SmartHomeNG team
    :license: GPL, see LICENSE file for more details.
"""
```

Fragen die sich mir stellen:
* brauchen wir den Text zur Lizenzierung immer nochmal im Header?
* ist die warranty notwendig aufzunehmen, oder kann man das evtl. auch in eine WARRANTY Datei packen? Steht vielleicht schon in der Lizenz mit drin?
* wollen wir mehrere Copyrights aufnehmen? Geht das in dem Format?
* Soll eine Beschreibung des Package rein oder reicht die Doku bei der Implementierung (z.B Klassen, Funktionen)

**Comment by psilo909** [comment]
und: wie gehen wir mit Plugins um, v.A. mit Plugins die jetzt schon drin sind oder die das SmartHomeNG Team angepasst hat? Da können wir die Lizenz ja nicht einfach ändern

**Comment by encbladexp** [comment]
Für die Autoren hat sich eine AUTHORS Datei und verweis darauf als am besten herausgestellt. Der Lizenzhinweis muss in den Header jeder Datei die zum Projekt gehört und Code enthält.

In der Lizenz (GPL-3) gibt es ja ein Muster was man reinkopieren soll, das sollten wir dann auch 1:1 so machen.

Bei bestehenden Plugins braucht man die Zustimmung der Autoren zum Lizenzwechsel falls nötig. Man sollte innerhalb eines Projektes nicht unnötig Lizenzen mischen.

**Comment by psilo909** [comment]
Wäre für mich ok. Was sagt denn @cstrassburg  dazu?

**Comment by encbladexp** [comment]
Gibt es schon was neues zu diesem Issue?

**Comment by psilo909** [comment]
aktuell hat sich wohl eher das hier eingebürgert, oder? wir sollten aber unbedingt konsistent werden

#########################################################################
#  Copyright 2016 xxxx                                                                                                                xxx(a)xxx.xxx
#  Version 1.1.11
#########################################################################
#
#  This file is part of SmartHomeNG.
#
#  SmartHomeNG is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  SmartHomeNG is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with SmartHomeNG. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

**Comment by cstrassburg** [comment]
Was hat die Versionsnummer im Lizenheader zu suchen?

**Comment by psilo909** [comment]
@cstrassburg mind beim Plugin muss die ja auch im File irgendwo rein. oder beschränken wir uns dort auf das Attribut? Mir auch recht.

**Comment by encbladexp** [comment]
Versionsnummern sollten wir in den Dateien nach Möglichkeit garnicht haben. Ergibt sich ja ohnehin aus der git Historie und der Versionsnummer von sh.py.

**Comment by psilo909** [comment]
mir recht, dann raus damit.. im smartplugin haben wir sowieso das attribut..

**Comment by cstrassburg** [comment]
Die Versionsnummer im Attribut reicht doch auch. Bei zwei Versionsnummern stehen in der Regel zwei unterschiedliche drin ;-)

**Comment by ohinckel** [comment]
Ja, Redundanz vermeiden. Welches Format wollen wir verwenden? Ich hatte mal eines mit einem doc-string [vorgeschlagen](https://github.com/smarthomeNG/smarthome/issues/59#issuecomment-244590278). Das koennte spaeter mal fuer eine erzeugte Referenzdokumentation von  Vorteil sein. So ein Format sollten wir auch an anderen Stellen verwenden, nicht nur dass wir eine gute Dokumentation bekommen und besser den Ueberblick behalten wenn wir weiterentwickeln, sondern auch Plugin-Entwickler Hilfestellung dadurch bekommen. Ist aber ein anderes Thema...

**Comment by encbladexp** [comment]
Normal ist der Lizenheader ein Kommentar (# am Anfang der Zeilen). Dort drin soll auch keine Dokumentation sein, sondern nur rechtliche Informationen. Als Docstring würde das bei jedem Modul, ohne Mehrwert, gerendert werden wenn wir Sphinx mal fertig haben.

**Comment by bmxp** [comment]
Gibt es aus rechtlicher Sicht nun die Möglichkeit den Lizenzheader zu vereinfachen? Macht das Sinn sich da weiter Gedanken drüber zu machen oder schließen wir dieses Issue?

**Comment by msinn** [comment]
Ich bin dafür das Issue zu schließen.

**Comment by bmxp** [comment]
Ich fasse zusammen: 
* Lizenzheader als Kommentar, nicht als Docstring
* Keine Versionsnummern, die stehen bei Plugins zukünftig in plugin.yaml und für den Core reicht git

**Comment by ohinckel** [comment]
Hmm, schade. Es gibt durchaus noch andere sinnvolle Punkte die das ganze vereinheitlichen (sollten). Ich bin z.B. kein Freund von "Copyright .... Name mail@mail". Bei Core Dateien sollte immer das Team referenziert werden.
