### ISSUE TITLE
    smarthome/doc/user/source/beispiele/eval.rst Beispiel "Enumeration über Liste" funktioniert nicht

### ISSUE THREAD

**Issue by lgb-this** [smarthomeNG/smarthome#604]
Das Beispiel im Abschnitt "Enumeration über Liste" funktioniert so nicht.

In der Zeile <<eval: ['Ausgeschaltet','Heizung startet','Heizung läuft'][value]>> fehlen die Anführungszeichen. Korrekt ist:

<<eval: "['Ausgeschaltet','Heizung startet','Heizung läuft'][value]">>

**Comment by aschwith** [comment]
Danke für den Hinweis. Ist im Develop jetzt korrigiert und wird mit dem nächsten Release gefixt.
