### ISSUE TITLE
Delay in scenes

### ISSUE THREAD

**Issue by CaeruleusAqua** [smarthomeNG/smarthome#612]
Hello everyone

Do you think it makes sense to include a possibility to define a delay in the scenes?

The background is that I currently have some Ikea lights here which do not allow me to change the color temperature until the last transition has been completed. I therefore need a delay between setting the brightness and the color temperature.

I am currently working on a workaround with a logic but 
such a function might also be helpful for other things.

**Comment by Morg42** [comment]
I'm guessing this might better be fixed in the plugin responsible for controlling the light bulb.

I don't think scenes are well designed to include such flexibility; especially, if there is not a lot more effect.

Maybe this can be solved for you with two scenes - one only with brightness and the other with color temp (or vice versa)...?

**Comment by CaeruleusAqua** [comment]
I'm not looking for an alternative solution, I've already given it a lot of thought. Multiple scenes don't make sense because I would like to control both parameters via a KNX scene. I can't fix it in the plugin because the light bulb is controlled directly via Zigbee2Mqtt. As already described, I already have a workaround with a logic that solves the problem. I wanted to propose a feature and present a use case so that others could solve the problem with much less effort.

If you want, I can also implement the feature myself and propose it again.

I just don't want to invest time if the PR is rejected either way.

Of course, we can also discuss beforehand how this could look in the configuration.

**Comment by msinn** [comment]
From the original design in KNX, scenes are thought of as doing everything at once. There is no idea of a timeline. Without a timeline a delay has nothing to act on.
