### ISSUE TITLE
KNX Plugin - missing knx_dpt should raise a warning

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#65]
When items are parsed within the knx plugin that do not have knx_dpt then the parsing is already done.
We should however consider to first check any other knx_... entries first and just when the datapoint was forgotten to raise a warning or an error.

**Comment by psilo909** [comment]
bitte nachtesten https://github.com/smarthomeNG/smarthome/commit/2c940d8b480f936a14591d0c9d170975446686a1

**Comment by bmxp** [comment]
Maybe ```elif **'knx_dpt' not in item.conf and** (
'knx_status' in item.conf or 'knx_send' in item.conf or 'knx_reply' in item.conf or 'knx_listen' in item.conf or 'knx_init' in item.conf or 'knx_cache' in item.conf):```
the first condition should not be needed ...?

**Comment by ohinckel** [comment]
Yes, not really needed.

**Comment by psilo909** [comment]
bereits ausgebaut

**Comment by bmxp** [comment]
My test case showed the warning as intended when opening this issue. Thus I close it here.
