### ISSUE TITLE
Cycle between calculation of sun position is too long

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#66]
The cyclus between two calculations of the suns position is too long. Right now it is calculated every 30 minutes. That means e.g. an azimuth change of more than 10° which is too much.

<pre>
[env_loc]
    filename = location.py
    crontab = init | sunrise+1m | sunset+1m | sunrise-5 | sunset-7
    cycle = 1800
</pre>

I would suggest to decouple the sunrise/sunset functions into one script which will be executed just around sunrise/sunset times and shortly afterwards. And then put two further scripts into the game, one for azimuth and one for elevation. 
The one for azimuth should update the azimuth every two minutes, this way we can keep the angle deviation below 1°.
The one for elevation should update the elevation every five minutes so to keep the angle deviation below 1°.

And furthermore which might be even more important: The script uses the smarthome sun object to do the calculations. When modifying the UZSU plugin I needed to create a new sun object since sharing it with the rest of SmartHomeNG can yield very strange and unexpected results.

<pre>
#relevant code is here:
        # create an own sun object:
        try:
            #longitude = self._sh.sun.long
            #latitude = self._sh.sun.lat
            #elevation = self._sh.sun.elevation
            longitude = self._sh.sun._obs.long
            latitude = self._sh.sun._obs.lat
            elevation = self._sh.sun._obs.elev
            uzsu_sun = lib.orb.Orb('sun', longitude, latitude, elevation)
            self.logger.debug("Created a new sun object with latitude={}, longitude={}, elevation={}".format(latitude, longitude, elevation)) 
        except Exception as e:
            self.logger.error("Error '{}' creating a new sun object. You could not use sunrise/sunset as UZSU entry.".format(e))
            return
</pre>

**Comment by smaiLee** [comment]
What is the reason for _sunrise-5 | sunset-7_?
The result of sunrise and sunest functions don't change between sunrise+1m and the next sunrise-5, do they?
In addition there's a sunset+1m between sunrise+1m and next sunrise. So sunrise is recalculated once more at the evening.
And why is it sunrise-**_5_** but sunset-**_7_**?

This was added by [commit 828b636](https://github.com/smarthomeNG/smarthome/commit/828b636217aef14d73101961e142994409e3d37b) and im sure there was an issue. But what was it?

**Comment by msinn** [comment]
@bmxp Is this issue still relevant?

**Comment by bmxp** [comment]
Yes. I have implemented the first solution and test it now. I'll push it when ready.

**Comment by msinn** [comment]
sunrise-5 and sunset-7 have been added (by mknx?) to ensure civil dusk/dawn are calculated correctly. Some users (including me) don‘t use sunrise and sunset for automation. I use civil and nautical dusk/dawn for automation.

**Comment by bmxp** [comment]
Ok, I've tested and pushed, should be finer for sun position now. If there is not another bug I don't bother to change the trigger times. You might close if it's ok for you.
