### ISSUE TITLE
delay plugin startup

### ISSUE THREAD

**Issue by cstrassburg** [smarthomeNG/smarthome#67]
Ich lese mit dem MBUS Plugin und IR Leseköpfen 4 Wärmemengezähler aus - klappt auch super, allerdings passiert es von Zeit zu Zeit, dass bei einem Neustart von Smarthome.py ein Treiberfehler auftaucht, den ich nicht wegbekomme (unable to enable UART). Ich vermute es liegt daran, dass das Plugin in der Startphase geladen wird und die WMZ auslesen will, da das System in der Startphase ausgelastet ist, gibt es anscheinend Fehler in der Kommunikation und die Leseköpfe klinken sich danach aus (und lassen sich nur durch ein - und ausstecken des USB-Steckers wieder aktivieren -> extrem unsmart).
Ich würde nun das Plugin gerne verzögert starten lassen, also nicht zu Beginn von Smarthome.py sondern z.B. erst nach 120 Sekunden - ist das Möglich (Ich könnte in das Plugin zu Beginn ein time.sleep enfügen - das finde ich aber wenig elegant.

**Comment by ohinckel** [comment]
> Ich vermute es liegt daran, dass das Plugin in der Startphase geladen wird und die
> WMZ auslesen will

Wenn das nur eine Vermutung ist, weiss ich nicht ob wir sowas implementieren sollen. Klar wenn jemand Zeit und Lust hat, kann man das gerne mal tun. Um zu pruefen ob das tatsaechlich ein Problem ist, koennte man temporaer auch in das entsprechende Plugin eine Verzoegerung mal einbauen und damit erstmal testen. Damit waere dann sichergestellt, dass das auch etwas bringt.

Ich habe auch ein USB-Device, was ab und an mal nicht mehr funktioniert (aber ziemlich selten). Loesen laesst sich das auch nur mit aus- und wieder einstecken. Ich vermute aber, dass es nicht am Neustart liegt, sondern eher am Device oder den Treibern selber, die sich in irgendeiner Konstallaktion "verhaken" und dann einen "Reset" brauchen. Daher die Befuerchtung, dass die Verzoegerung nicht helfen wird.

**Comment by bmxp** [comment]
There is already the possibility to give the sheduler an offset. What needs to be done within each plugin is to put an offset in the plugin configuration and when sheduling the first query or interaction, we can pass the offset to the sheduler.

**Comment by bmxp** [comment]
There is already the possibility to give the scheduler an offset. What needs to be done within each plugin is to put an offset in the plugin configuration and when scheduling the first query or interaction, we can pass the offset to the scheduler.

**Comment by ohinckel** [comment]
So this is more a "first cycle update delay" for the mentioned plugin and not a general feature to delay the whole plugin startup (delay the start of a plugin thread).

I guess  @cstrassburg thought about to have a general solution to delay the whole plugin startup instead of doing a delay within the plugin implementation when adding scheduler tasks. But the latter could also "solve" the problem from the reporter.

But: @cstrassburg did you checked if a delay really solve your problem?

**Comment by msinn** [comment]
For me it looks like the solution could be implemented in the run method of the plugin that has this problem.

instead of setting `self.alive = True` instantly, start a scheduler, that calls a methond `run2` which then sets `self.alive = True`.

**Comment by ohinckel** [comment]
The feature request was created based upon an assumption which could completely be wrong. It's still not verified that the root cause is the system load. So I suggest to close this feature request if no body else requires such a plugin startup delay.

**Comment by bmxp** [comment]
The suggestion of @msinn makes sense to me. As @cstrassburg will be able to implement this by himself if he has some time again I will close this issue now and we can reawake it if needed later on.

**Comment by psilo909** [comment]
@bmxp will he?

**Comment by bmxp** [comment]
Nope. @msinn favours a solution within the core, not the plugins.

**Comment by msinn** [comment]
And we should define the use-case more precise.

If you want a delay to startup different instances of a plugin to different times so message don't collide on the serial bus both instances share (eg. RS485), it might not be a good idea. On startup the collision is avoided, but it will hit during the runtime.

If you need a delay to ensure some other software or hardware has to become ready first, a delay might be a good idea. To get some control if the initialization is  done, it should not be done in the plugins but it should be controlled by lib.plugin.
