### ISSUE TITLE
Backend: enhance cache checking user possibilities

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#74]
- It would be great to present a button for every cache item to delete it. 
- It would be nice to have a button for "delete all orphans"
- It would be great to display all cache items with their value and not only the orphaned ones

**Comment by psilo909** [comment]
How do others see this feature? Triggering a system delete command - from my point of view - is too invasive for a web based backend due to security reasons.

**Comment by bmxp** [comment]
Maybe it should only be offered for the backend if there is a user and password set?

**Comment by psilo909** [comment]
which (not really) makes it much more secure ;)

**Comment by msinn** [comment]
To be on the safe side, these functions could be turned on or off by a plugin.conf parameter. This way, every user can decide, if he wants the functionality or not.

But I don't see any special risks in an usual SmartHomeNG environment. If someone hat access to the Backend plugin, he hat access to the local network. (I don't hope someone gives access to the Backend plugin from the internet without using a vpn).

If someone is on the local network, he can do many other things than deleting cache files, which are recreated. He can manipulate the KNX bus without a password. Or even simpler, he can manipulate every SmartHomeNG item through the websocket interface.

**Comment by onkelandy** [comment]
Would also love the possibility to see the value of every cache entry.

**Comment by psilo909** [comment]
das löschen pushe ich gleich in den dev, aber nur für dateien die nicht die normalen cache dateien sind. wie würdet ihr letztere auslesen? die sind ja binaries.. irgendwie über das item abfragen? geht das?

**Comment by ohinckel** [comment]
Das Auslesen des Caches wuerde ich im Item sehen. Dort koennte man drei Funktionen anbieten:
* `read_cache_value()` - liest den Wert aus dem Cache und uebernimmt diesen ins item (fuer die Initialisierung des Items)
* `write_cache_value()` - schreibt den aktuellen Wert des Items in den Cache (fuer Stoppen von SH um den Cache zu schreiben)
* `get_cache_value()` - liefert den aktuellen Wert des Caches zurueck (fuer das Auslesen bspw. im Backend)

**Comment by msinn** [comment]
What happened with this issue in the meantime? 

I can only see 10 orphan cache-items, but my cache directory has lots of cache files that were not updated for several month. It could be, that those Items still exist but are configured for caching any more.

**Comment by psilo909** [comment]
@msinn u mean we should also check the cache attribute of each item and delete the cache file, even when the item exists, but cache attribut is removed?

i am not sure if that is the wanted behavior?!

**Comment by msinn** [comment]
At least give the option to delete those cache files like for orphan cache files.

**Comment by ohinckel** [comment]
We could list and show all orphan cache files to the user before deleting them. The user can decide if they should be deleted or not.

**Comment by psilo909** [comment]
just had a look in the code.. isnt this already done? https://github.com/smarthomeNG/plugins/blob/develop/backend/BackendItems.py#L106

**Comment by msinn** [comment]
It is already implemented:

![capto_capture 2018-05-12_11-15-04_pm](https://user-images.githubusercontent.com/452067/39961613-5b34238c-563a-11e8-8164-7bcfe915f266.jpg)

**Comment by ohinckel** [comment]
Looks great. Maybe a delete all button could be helpful in case the user has a lot of items.

**Comment by onkelandy** [comment]
Or even better checkboxes on the left to select specific entries and a "Delete selected" button? Checkbox above the first entry makes it possible to check all.

**Comment by psilo909** [comment]
@ohinckel what should this button do? There could be also files not related to former items. these are also shown in the list.
the button would then delete really all files. do u think that behavior is ok?! we could add at least a javascript "confirm" dialogue before..

**Comment by psilo909** [comment]
yea i also prefer the checkboxes.. including an "select all" button

**Comment by psilo909** [comment]
pushed a prototype of the checkboxes

**Comment by msinn** [comment]
Feature made it to the v1.5 release
