### ISSUE TITLE
Item configuration: Relative item references

### ISSUE THREAD

**Issue by msinn** [smarthomeNG/smarthome#75]
It would be great, if it would be possible to reference items with a relative reference.

This could be helpful especially for eval and eval_trigger entries in the etc/item.conf file but also for other entires (eg. sv_widget). This way it would be much simpler to copy parts of the item config structure.

The relative references should be converted to absolute references while loading the item.conf file. This way, all other item handling in SmartHomeNG can be left unchanged.

**Comment by msinn** [comment]
Suggestion for implementation:
- relative references start with a point (.)
- To reference a level higher, a point has to be added for every level
- relative parts of a path can be added to the point(s).

For instance, if you have an item subtree in the following form:

```
[level_1]
    [[level_2]]
        [[[item_1]]]
            eval_trigger = 
           [[[[subitem_1]]]]
        [[[item_2]]]
           [[[[subitem_2]]]]

```

the ``eval_trigger`` statement can reference
- ``level_1.level_2.item_1``-> ``.``
- ``level_1.level_2.item_1.subitem_1`` -> ``.subitem_1``
- ``level_1.level_2``-> ``..``
- ``level_1.level_2.item_2`` -> ``..item_2``
- ``level_1.level_2.item_2.subitem_2`` -> ``..item_2.subitem_2``
- ``level_1``-> ``...``

**Comment by bmxp** [comment]
This is my current implementation:
<pre>
        #############################################################
        # Item Attributes
        #############################################################
        for attr, value in config.items():
            if not isinstance(value, dict):
                if attr in ['cycle', 'eval', 'name', 'type', 'value']:
                    setattr(self, '_' + attr, value)
                elif attr in ['cache', 'enforce_updates']:  # cast to bool
                    try:
                        setattr(self, '_' + attr, _cast_bool(value))
                    except:
                        logger.warning("Item '{0}': problem parsing '{1}'.".format(self._path, attr))
                        continue
                elif attr in ['eval_trigger']:  # cast to list
                    ## extend here for two dots '..' which means parent
                    ## this will result in a lot of writing work less when you have 
                    ## an item which is to be triggered by its parent
                    if isinstance(value, str):
                        if value == '..':
                            logger.info("Parsing {0} we found eval_trigger = ..  will be converted to its parent: {1}".format(self.id(), self.id()))
                            value = self.return_parent().id()
                        value = [value, ]
                    setattr(self, '_' + attr, value)
                elif attr in ['crontab']:  # cast to list
                    if isinstance(value, str):
                        value = [value, ]
                    setattr(self, '_' + attr, value)
                elif attr == 'autotimer':
                    time, __, value = value.partition('=')
                    if value is not None:
                        self._autotimer = time, value
                elif attr == 'threshold':
                    low, __, high = value.rpartition(':')
                    if not low:
                        low = high
                    self._threshold = True
                    self.__th_crossed = False
                    self.__th_low = float(low.strip())
                    self.__th_high = float(high.strip())
                    logger.debug("Item {}: set threshold => low: {} high: {}".format(self._path, self.__th_low, self.__th_high))
                else:
                    self.conf[attr] = value
</pre>

And this is a typical application for it:

<pre>
                [[[[[Ausfall]]]]]
                    # Ausfall = 1
                    name = Ausfall Stellgröße Heizkreis Windfang
                    visu_acl = rw
                    type = bool
                    knx_dpt = 1
                    knx_init = 5/3/25
                    [[[[[[LastUpdate]]]]]]
                        name = letztes Update von
                        type = foo
                        cache = yes
                        eval = self.return_parent().last_update().strftime('%a %d.%m. %H:%M:%S')
                        eval_trigger = ..
</pre>

**Comment by msinn** [comment]
I am thinking of isolating the conversion itself to a method, which can be used by plugins. The parse_item method of a plugin could call the conversion method to support relative references for the item attributed of the plugin.

**Comment by onkelandy** [comment]
That would be a nice feature.. The autoblind plugin is using this method successfully.

**Comment by msinn** [comment]
Feature implementation: PR https://github.com/smarthomeNG/smarthome/pull/94

(German) documentation is here: https://github.com/smarthomeNG/smarthome/wiki/Items:-Relative-Item-Referenzen

**Comment by ohinckel** [comment]
I guess we can close this issue, right?

**Comment by msinn** [comment]
Right!
