### ISSUE TITLE
BUG: Mail Plugin error (alive problem and NoneType object)

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#76]
Starting the mail plugin gives the following error:
ERROR    IMAP         Method IMAP exception: 'IMAP' object has no attribute 'alive'
Putting a self.alive in the init function fixes the problem for me.

Sometimes I also get the error message:
IMAP: problem parsing message b'3428': 'NoneType' object is not subscriptable

As far as I could research a standard "except" instead of "except Exception as e" could fix the problem.

**Comment by msinn** [comment]
Fixed Bug 'Scheduler starting too soon'. 

Please Test

**Comment by msinn** [comment]
About: IMAP: problem parsing message b'3428': 'NoneType' object is not subscriptable

Using 'except' instead of 'except Exception as e' does nothing to the error but hiding it. Because the variable e is not set, the following instruction 

```
logger.exception("IMAP: problem parsing message {}: {}".format(uid, e))
```
fails.

Why would you hide an error that is occurring in the communication with the mail server anyway?

**Comment by onkelandy** [comment]
It's not about hiding the exception, it's about catching all problems.
Implementing a line like this gets the error message written in the log:
except: # catch *all* exceptions
     e = sys.exc_info()[0]

That should avoid the problem that python shows some error messages - and redirect the message to the log output

**Comment by msinn** [comment]
Please elaborate. I don`t understand the problem you are having. Please post the part of your log file.

**Comment by onkelandy** [comment]
I have no idea what really causes the error but right now it is not correctly caught by the python code. The log looks like this (so first line is smarthome log, rest is python error):

2016-07-11  15:01:33 ERROR    IMAP         IMAP: problem parsing message b'3406': 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/smarthome/plugins/mail/__init__.py", line 88, in _cycle
    mail = email.message_from_bytes(data[0][1])
TypeError: 'NoneType' object is not subscriptable

**Comment by msinn** [comment]
The exception is correctly caught. The author of the plugin wanted to throw an exception. The call to logger.exception() does exact this:

```
logger.exception("IMAP: problem parsing message {}: {}".format(uid, e))
```

This way the user can see which line of  the try/except block causes the error.

So this is not a bug. It works as designed. It could be debated, if this design user friendly.

**Comment by onkelandy** [comment]
Ohhhh okay, got it.. thanks - didn't know that the "execption" part was the "problem" ;)
So this can be marked as fixed as the newest version doesn't have the "alive" problem anymore. Thanks!

**Comment by msinn** [comment]
Nach der Rückmeldung mach ich hier zu. 😄
