### ISSUE TITLE
UPDATE: Operationlog plugin

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#78]
Could you please update the operationlog plugin to this release here?
https://github.com/JanT112/smarthome/tree/feature-operationlog-plugin-add-itemlogtext

Thanks!

**Comment by msinn** [comment]
This should be done by the author/maintainer of the plugin. Have you contacted him?

**Comment by bmxp** [comment]
Just written a PN. Let's wait and see....

**Comment by onkelandy** [comment]
Don that 3 weeks ago, no repsone.. Put a pull request out there, hope that is okay.

**Comment by ohinckel** [comment]
Someone received a feedback already?

**Comment by onkelandy** [comment]
Ja, schon vor ner ganzen Weile:
ich habe gerade Bernd auch beantwortet. Ich habe momentan eine längeren "Pause" und bin noch nicht auf NG umgestiegen. Es wäre mir lieb wenn ihr die notwendigen Änderungen/Patches durchführen.

Mein Pull Request wurde aber soweit ich das sehe eh akzeptiert, sprich das Plugin läuft.

**Comment by ohinckel** [comment]
OK, wo war der Pull Request? Koennte man hier noch referenzieren und damit das Issue dann schliessen.

**Comment by onkelandy** [comment]
https://github.com/smarthomeNG/smarthome/pull/96
