### ISSUE TITLE
Startup Error with SQLite plugin

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#82]
Sometimes when startin SmarthomeNG fresh I get the following error message. Doesn't seem to be a real problem but it's still an error ;)

2016-07-25  10:57:47 ERROR    SQLite dump  Method SQLite dump exception: dictionary changed size during iteration
Traceback (most recent call last):
  File "/usr/smarthome/lib/scheduler.py", line 371, in _task
    obj()
  File "/usr/smarthome/plugins/sqlite/__init__.py", line 169, in _dump
    for item in self._buffer:
RuntimeError: dictionary changed size during iteration

**Comment by ohinckel** [comment]
This happens when the dump is running, but the internal buffer of values changes. Usually this should not happen since a lock is used to make the internal buffer exclusive for some process and other will not be able to change it.

It could be that some location in this plugin is not handling the lock correctly.

**Comment by ohinckel** [comment]
The [_maintain()](https://github.com/smarthomeNG/smarthome/blob/develop/plugins/sqlite_visu2_8/__init__.py#L284) (sqlite_visu2_8) and [_dump()](https://github.com/smarthomeNG/smarthome/blob/develop/plugins/sqlite/__init__.py#L168) (sqlite) methods are not locking while iterating over the buffer.

**Comment by onkelandy** [comment]
He there.. should the last commit already fix the problem? Because I still get the error :(

**Comment by ohinckel** [comment]
No, this does not fix it. It fixed one issue from #83, but I wrote the wrong issue number into the commit message.

To fix this the locking should be changed or the items should be copied to another list while holding a short lock on the buffer. Something like the implementation in [DB-API  PR @ mknx](https://github.com/mknx/smarthome/pull/69/files#diff-e884be5f7eda6ab398c5566f0a988fd8R193).

**Comment by ohinckel** [comment]
> To fix this the locking should be changed or the items should be copied to another list while
> holding a short lock on the buffer.

Done via PR #133. Please test!

**Comment by ohinckel** [comment]
Any tests so far? Can we merge the PR?

**Comment by psilo909** [comment]
should be tested by someone who is using old sqlite plugin, like @bmxp or @msinn :) @onkelandy and i are testing your db PR

**Comment by ohinckel** [comment]
Acording to comment in #133 the fix is working. Closing this issue now.
