### ISSUE TITLE
datalog plugin: error when defining just one filepattern in plugin.conf

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#86]
Hi!
When I start the datalog plugin without additional parameters everything works fine. As soon as I uncomment the standard parameters for filepatterns and logpatterns I get the following error message:

2016-08-01 13:46:24 ERROR    plugin       Main         Plugin datalog exception: string indices must be integers -- plugin.py:__init__:67
Traceback (most recent call last):
  File "/usr/smarthome/lib/plugin.py", line 63, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance)
  File "/usr/smarthome/lib/plugin.py", line 108, in __init__
    exec("self.plugin.__init__(smarthome{0})".format(args))
  File "<string>", line 1, in <module>
  File "/usr/smarthome/plugins/datalog/__init__.py", line 56, in __init__
    ext = self.filepatterns[log].split('.')[-1]
TypeError: string indices must be integers

**Comment by bmxp** [comment]
you need to give more info: Which entries are in your plugin.conf? E.g. your filepatterns=?

**Comment by bmxp** [comment]
Well, there is a bug. It seems as if never anyone tried to pass a single filepattern. See what happens, if you give two filepatterns 
<pre>
filepatterns = default:{log}-{year}-{month}-{day}.csv | default2:{log}-{year}-{month}-{day}.csv
</pre>
(use it as a workaround unless there is an official fix)

**Comment by ohinckel** [comment]
I just provided a fix for this in a new PR.

**Comment by bmxp** [comment]
Your fix looks prettier than mine so I keep it for myself :-)

**Comment by ohinckel** [comment]
Fix was merged alread. I'll close this issue now.
