### ISSUE TITLE
Move Plugin/Skeleton.py to dev

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/smarthome#92]
plugin/skeleton and dev/skeleton schould be merged. Maybe move plugin/skeleton into dev?

**Comment by psilo909** [comment]
+1 - wer machts :)

**Comment by smaiLee** [comment]
I suggest the following changes:

1. Move folder `/plugins/skeleton/` to `/dev/plugin_skeleton/`.
1. Replace the moved `/dev/plugin_skeleton/__init__.py` by `/dev/skeleton.py`. This is the current version based on SmartPlugin and IMHO theres nothing relevant in \__init\__.py that's not in skeleton.py.
1. Change paths in /dev/README.md.

I would left unchanged the rest of the two READMEs. The one in `/plugins/skeleton/` is actually a skeleton for new plugins and the one in `/dev/` is the how-to for developpping a plugin.

If you agree to that i make the changes.

**Comment by ohinckel** [comment]
I did not check the code in both folders, but I think we should only have *one* skeleton for plugin and *one* documentation/howto.

But I prefer to put documentation and howtos into the wiki instead into the codebase. Skeleton seems to be OK in the code, but could also be moved into the wiki, so the whole stuff is in the wiki and not in the codebase. Just another idea.

**Comment by bmxp** [comment]
Ok, just integrated the two and created a new dir ```dev/sample_plugin```. I really did not like the word skeleton. The both +.py were different not only in documentation but also in code. I think I saved the most of it but I would feel better if someone has a look over it and maybe has some improvement here or there.
If I do not get any more input, I will close this issue on Sunday evening.

**Comment by msinn** [comment]
@bxmp: Looks good. I am gonna make a few additions and push it to develop too.

- The SmartPlugin Object defines the logger already, so we can remove it from the sample. (I'll test that)
- The SmartPlugin Object defines __sh (with double '_') and has a method to set it. It's not clear to me if this ist just unfinished work (It is not initialized automatically)

**Comment by msinn** [comment]
In plugin.py __sh should be set but neither self.__sh nor the predefined self.logger from SmartPlugin Object do work. So the sample_plugin can stay as it is for the time being. 

If some has lots of time, he can try to find out why self.__sh and self.logger don't work by inheritance.

**Comment by msinn** [comment]
@bmxp You didn't close the issue on last sunday... Just close it on next sunday 😉
